<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Elementary Statistics with R</title>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
  <meta name="description" content="These are course notes for MAT 111 at Georgetown College. They are greatly in need of revision.">
  <meta name="generator" content="bookdown 0.0.71 and GitBook 2.6.7">

  <meta property="og:title" content="Elementary Statistics with R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="These are course notes for MAT 111 at Georgetown College. They are greatly in need of revision." />
  <meta name="github-repo" content="homerhanumat/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Elementary Statistics with R" />
  
  <meta name="twitter:description" content="These are course notes for MAT 111 at Georgetown College. They are greatly in need of revision." />
  

<meta name="author" content="Rebekah Robinson and Homer White">

<meta name="date" content="2016-05-18">

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="relationships-between-two-factor-variables.html">
<link rel="next" href="sampling-and-surveys.html">

<script src="book_assets/jquery-2.2.3/jquery.min.js"></script>
<link href="book_assets/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>


  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Elementary Statistics With R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#what-are-r-and-rstudio"><i class="fa fa-check"></i><b>1.1</b> What are R and RStudio?</a><ul>
<li class="chapter" data-level="1.1.1" data-path="index.html"><a href="index.html#panels-and-tabs"><i class="fa fa-check"></i><b>1.1.1</b> Panels and Tabs</a></li>
<li class="chapter" data-level="1.1.2" data-path="index.html"><a href="index.html#differences-between-rscript-and-rmarkdown-files"><i class="fa fa-check"></i><b>1.1.2</b> Differences Between RScript and RMarkdown Files</a></li>
<li class="chapter" data-level="1.1.3" data-path="index.html"><a href="index.html#basic-r"><i class="fa fa-check"></i><b>1.1.3</b> Basic R</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#lets-play-cards"><i class="fa fa-check"></i><b>1.2</b> Let’s play cards!</a><ul>
<li class="chapter" data-level="1.2.1" data-path="index.html"><a href="index.html#the-game"><i class="fa fa-check"></i><b>1.2.1</b> The Game</a></li>
<li class="chapter" data-level="1.2.2" data-path="index.html"><a href="index.html#the-results"><i class="fa fa-check"></i><b>1.2.2</b> The Results</a></li>
<li class="chapter" data-level="1.2.3" data-path="index.html"><a href="index.html#the-conclusion"><i class="fa fa-check"></i><b>1.2.3</b> The Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#statistics"><i class="fa fa-check"></i><b>1.3</b> Statistics</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#thoughts-on-r"><i class="fa fa-check"></i><b>1.4</b> Thoughts on R</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html"><i class="fa fa-check"></i><b>2</b> Describing Patterns in Data</a><ul>
<li class="chapter" data-level="2.1" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#data-basics"><i class="fa fa-check"></i><b>2.1</b> Data Basics</a><ul>
<li class="chapter" data-level="2.1.1" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#getting-data-in-r"><i class="fa fa-check"></i><b>2.1.1</b> Getting Data in R</a></li>
<li class="chapter" data-level="2.1.2" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#variable-types"><i class="fa fa-check"></i><b>2.1.2</b> Variable Types</a></li>
<li class="chapter" data-level="2.1.3" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#descriptive-statistics"><i class="fa fa-check"></i><b>2.1.3</b> Descriptive Statistics</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#outline"><i class="fa fa-check"></i><b>2.2</b> Outline</a></li>
<li class="chapter" data-level="2.3" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#one-factor-variable"><i class="fa fa-check"></i><b>2.3</b> One Factor Variable</a><ul>
<li class="chapter" data-level="2.3.1" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#tables"><i class="fa fa-check"></i><b>2.3.1</b> Tables</a></li>
<li class="chapter" data-level="2.3.2" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#barcharts."><i class="fa fa-check"></i><b>2.3.2</b> Barcharts.</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#two-factor-variables"><i class="fa fa-check"></i><b>2.4</b> Two Factor Variables</a><ul>
<li class="chapter" data-level="2.4.1" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#two-way-tables"><i class="fa fa-check"></i><b>2.4.1</b> Two-Way Tables</a></li>
<li class="chapter" data-level="2.4.2" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#barcharts-again"><i class="fa fa-check"></i><b>2.4.2</b> Barcharts Again</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#one-numerical-variable"><i class="fa fa-check"></i><b>2.5</b> One Numerical Variable</a><ul>
<li class="chapter" data-level="2.5.1" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#numerical-measures"><i class="fa fa-check"></i><b>2.5.1</b> Numerical Measures</a></li>
<li class="chapter" data-level="2.5.2" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#graphical-tools"><i class="fa fa-check"></i><b>2.5.2</b> Graphical Tools</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#factor-and-numerical-variable"><i class="fa fa-check"></i><b>2.6</b> Factor and Numerical Variable</a><ul>
<li class="chapter" data-level="2.6.1" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#numerical-tools"><i class="fa fa-check"></i><b>2.6.1</b> Numerical Tools</a></li>
<li class="chapter" data-level="2.6.2" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#graphical-tools-1"><i class="fa fa-check"></i><b>2.6.2</b> Graphical Tools</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#choice-of-measures"><i class="fa fa-check"></i><b>2.7</b> Choice of Measures</a><ul>
<li class="chapter" data-level="2.7.1" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#mean-median-and-skewness"><i class="fa fa-check"></i><b>2.7.1</b> Mean, Median and Skewness</a></li>
<li class="chapter" data-level="2.7.2" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#mean-median-and-outliers"><i class="fa fa-check"></i><b>2.7.2</b> Mean, Median and Outliers</a></li>
<li class="chapter" data-level="2.7.3" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#meansd-vs.medianiqr"><i class="fa fa-check"></i><b>2.7.3</b> Mean/SD vs. Median/IQR</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#bell-shaped-distributions"><i class="fa fa-check"></i><b>2.8</b> Bell-Shaped Distributions</a><ul>
<li class="chapter" data-level="2.8.1" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#the-68-95-rule"><i class="fa fa-check"></i><b>2.8.1</b> The 68-95 Rule</a></li>
<li class="chapter" data-level="2.8.2" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#z-scores"><i class="fa fa-check"></i><b>2.8.2</b> <span class="math inline">\(z\)</span>-scores</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#reading-in-statistics"><i class="fa fa-check"></i><b>2.9</b> Reading in Statistics</a></li>
<li class="chapter" data-level="2.10" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#thoughts-on-r-1"><i class="fa fa-check"></i><b>2.10</b> Thoughts on R</a><ul>
<li class="chapter" data-level="2.10.1" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#new-r-functions"><i class="fa fa-check"></i><b>2.10.1</b> New R Functions</a></li>
<li class="chapter" data-level="2.10.2" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#those-pesky-formulas"><i class="fa fa-check"></i><b>2.10.2</b> Those Pesky Formulas!</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="relationships-between-two-factor-variables.html"><a href="relationships-between-two-factor-variables.html"><i class="fa fa-check"></i><b>3</b> Relationships Between Two Factor Variables</a><ul>
<li class="chapter" data-level="3.1" data-path="relationships-between-two-factor-variables.html"><a href="relationships-between-two-factor-variables.html#introduction-1"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="relationships-between-two-factor-variables.html"><a href="relationships-between-two-factor-variables.html#the-descriptive-aspect"><i class="fa fa-check"></i><b>3.2</b> The Descriptive Aspect</a><ul>
<li class="chapter" data-level="3.2.1" data-path="relationships-between-two-factor-variables.html"><a href="relationships-between-two-factor-variables.html#terminology-for-two-way-tables"><i class="fa fa-check"></i><b>3.2.1</b> Terminology for Two-Way Tables</a></li>
<li class="chapter" data-level="3.2.2" data-path="relationships-between-two-factor-variables.html"><a href="relationships-between-two-factor-variables.html#detecting-and-describing-relationships"><i class="fa fa-check"></i><b>3.2.2</b> Detecting and Describing Relationships</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="relationships-between-two-factor-variables.html"><a href="relationships-between-two-factor-variables.html#the-idea-of-inference"><i class="fa fa-check"></i><b>3.3</b> The Idea of Inference</a></li>
<li class="chapter" data-level="3.4" data-path="relationships-between-two-factor-variables.html"><a href="relationships-between-two-factor-variables.html#tests-of-significance"><i class="fa fa-check"></i><b>3.4</b> Tests of Significance</a><ul>
<li class="chapter" data-level="3.4.1" data-path="relationships-between-two-factor-variables.html"><a href="relationships-between-two-factor-variables.html#five-step-procedure"><i class="fa fa-check"></i><b>3.4.1</b> Five Step Procedure</a></li>
<li class="chapter" data-level="3.4.2" data-path="relationships-between-two-factor-variables.html"><a href="relationships-between-two-factor-variables.html#more-on-the-chi-square-statistic"><i class="fa fa-check"></i><b>3.4.2</b> More on the Chi-Square Statistic</a></li>
<li class="chapter" data-level="3.4.3" data-path="relationships-between-two-factor-variables.html"><a href="relationships-between-two-factor-variables.html#chisqtestgc"><i class="fa fa-check"></i><b>3.4.3</b> <code>chisqtestGC()</code></a></li>
<li class="chapter" data-level="3.4.4" data-path="relationships-between-two-factor-variables.html"><a href="relationships-between-two-factor-variables.html#working-with-summary-data"><i class="fa fa-check"></i><b>3.4.4</b> Working With Summary Data</a></li>
<li class="chapter" data-level="3.4.5" data-path="relationships-between-two-factor-variables.html"><a href="relationships-between-two-factor-variables.html#simulating-p-values"><i class="fa fa-check"></i><b>3.4.5</b> Simulating P-Values</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="relationships-between-two-factor-variables.html"><a href="relationships-between-two-factor-variables.html#simpsons-paradox"><i class="fa fa-check"></i><b>3.5</b> Simpson’s Paradox</a></li>
<li class="chapter" data-level="3.6" data-path="relationships-between-two-factor-variables.html"><a href="relationships-between-two-factor-variables.html#thoughts-on-r-2"><i class="fa fa-check"></i><b>3.6</b> Thoughts on R</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="relationships-between-two-numerical-variables.html"><a href="relationships-between-two-numerical-variables.html"><i class="fa fa-check"></i><b>4</b> Relationships Between Two Numerical Variables</a><ul>
<li class="chapter" data-level="4.1" data-path="relationships-between-two-numerical-variables.html"><a href="relationships-between-two-numerical-variables.html#outline-1"><i class="fa fa-check"></i><b>4.1</b> Outline</a></li>
<li class="chapter" data-level="4.2" data-path="relationships-between-two-numerical-variables.html"><a href="relationships-between-two-numerical-variables.html#statistical-relationships"><i class="fa fa-check"></i><b>4.2</b> Statistical Relationships</a><ul>
<li class="chapter" data-level="4.2.1" data-path="relationships-between-two-numerical-variables.html"><a href="relationships-between-two-numerical-variables.html#scatterplots"><i class="fa fa-check"></i><b>4.2.1</b> Scatterplots</a></li>
<li class="chapter" data-level="4.2.2" data-path="relationships-between-two-numerical-variables.html"><a href="relationships-between-two-numerical-variables.html#correlation"><i class="fa fa-check"></i><b>4.2.2</b> Correlation</a></li>
<li class="chapter" data-level="4.2.3" data-path="relationships-between-two-numerical-variables.html"><a href="relationships-between-two-numerical-variables.html#regression-equation"><i class="fa fa-check"></i><b>4.2.3</b> Regression Equation</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="relationships-between-two-numerical-variables.html"><a href="relationships-between-two-numerical-variables.html#cautions"><i class="fa fa-check"></i><b>4.3</b> Cautions</a><ul>
<li class="chapter" data-level="4.3.1" data-path="relationships-between-two-numerical-variables.html"><a href="relationships-between-two-numerical-variables.html#extrapolation"><i class="fa fa-check"></i><b>4.3.1</b> Extrapolation</a></li>
<li class="chapter" data-level="4.3.2" data-path="relationships-between-two-numerical-variables.html"><a href="relationships-between-two-numerical-variables.html#influential-observations"><i class="fa fa-check"></i><b>4.3.2</b> Influential Observations</a></li>
<li class="chapter" data-level="4.3.3" data-path="relationships-between-two-numerical-variables.html"><a href="relationships-between-two-numerical-variables.html#association-versus-causation"><i class="fa fa-check"></i><b>4.3.3</b> Association versus Causation</a></li>
<li class="chapter" data-level="4.3.4" data-path="relationships-between-two-numerical-variables.html"><a href="relationships-between-two-numerical-variables.html#simpsons-paradox-1"><i class="fa fa-check"></i><b>4.3.4</b> Simpson’s Paradox</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="relationships-between-two-numerical-variables.html"><a href="relationships-between-two-numerical-variables.html#curvilinear-fits"><i class="fa fa-check"></i><b>4.4</b> Curvilinear Fits</a></li>
<li class="chapter" data-level="4.5" data-path="relationships-between-two-numerical-variables.html"><a href="relationships-between-two-numerical-variables.html#thoughts-on-r-3"><i class="fa fa-check"></i><b>4.5</b> Thoughts on R</a><ul>
<li class="chapter" data-level="4.5.1" data-path="relationships-between-two-numerical-variables.html"><a href="relationships-between-two-numerical-variables.html#new-r-functions-1"><i class="fa fa-check"></i><b>4.5.1</b> New R Functions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="sampling-and-surveys.html"><a href="sampling-and-surveys.html"><i class="fa fa-check"></i><b>5</b> Sampling and Surveys</a><ul>
<li class="chapter" data-level="5.1" data-path="sampling-and-surveys.html"><a href="sampling-and-surveys.html#introduction-2"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="sampling-and-surveys.html"><a href="sampling-and-surveys.html#population-versus-sample"><i class="fa fa-check"></i><b>5.2</b> Population versus Sample</a></li>
<li class="chapter" data-level="5.3" data-path="sampling-and-surveys.html"><a href="sampling-and-surveys.html#types-of-samples"><i class="fa fa-check"></i><b>5.3</b> Types of Samples</a><ul>
<li class="chapter" data-level="5.3.1" data-path="sampling-and-surveys.html"><a href="sampling-and-surveys.html#random-sampling"><i class="fa fa-check"></i><b>5.3.1</b> Random Sampling</a></li>
<li class="chapter" data-level="5.3.2" data-path="sampling-and-surveys.html"><a href="sampling-and-surveys.html#comparison-of-sampling-methods"><i class="fa fa-check"></i><b>5.3.2</b> Comparison of Sampling Methods</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="sampling-and-surveys.html"><a href="sampling-and-surveys.html#bias-in-surveys"><i class="fa fa-check"></i><b>5.4</b> Bias in Surveys</a><ul>
<li class="chapter" data-level="5.4.1" data-path="sampling-and-surveys.html"><a href="sampling-and-surveys.html#selection-bias"><i class="fa fa-check"></i><b>5.4.1</b> Selection Bias</a></li>
<li class="chapter" data-level="5.4.2" data-path="sampling-and-surveys.html"><a href="sampling-and-surveys.html#nonresopnse-bias"><i class="fa fa-check"></i><b>5.4.2</b> Nonresopnse Bias</a></li>
<li class="chapter" data-level="5.4.3" data-path="sampling-and-surveys.html"><a href="sampling-and-surveys.html#response-bias"><i class="fa fa-check"></i><b>5.4.3</b> Response Bias</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="sampling-and-surveys.html"><a href="sampling-and-surveys.html#thoughts-on-r-4"><i class="fa fa-check"></i><b>5.5</b> Thoughts on R</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="design-of-studies.html"><a href="design-of-studies.html"><i class="fa fa-check"></i><b>6</b> Design of Studies</a><ul>
<li class="chapter" data-level="6.1" data-path="design-of-studies.html"><a href="design-of-studies.html#observational-studies-and-experiments"><i class="fa fa-check"></i><b>6.1</b> Observational Studies and Experiments</a></li>
<li class="chapter" data-level="6.2" data-path="design-of-studies.html"><a href="design-of-studies.html#why-perform-experiments"><i class="fa fa-check"></i><b>6.2</b> Why Perform Experiments?</a></li>
<li class="chapter" data-level="6.3" data-path="design-of-studies.html"><a href="design-of-studies.html#experimental-designs"><i class="fa fa-check"></i><b>6.3</b> Experimental Designs</a><ul>
<li class="chapter" data-level="6.3.1" data-path="design-of-studies.html"><a href="design-of-studies.html#completely-randomized-designs"><i class="fa fa-check"></i><b>6.3.1</b> Completely Randomized Designs</a></li>
<li class="chapter" data-level="6.3.2" data-path="design-of-studies.html"><a href="design-of-studies.html#randomized-block-designs"><i class="fa fa-check"></i><b>6.3.2</b> Randomized Block Designs</a></li>
<li class="chapter" data-level="6.3.3" data-path="design-of-studies.html"><a href="design-of-studies.html#matched-pair-designs"><i class="fa fa-check"></i><b>6.3.3</b> Matched Pair Designs</a></li>
<li class="chapter" data-level="6.3.4" data-path="design-of-studies.html"><a href="design-of-studies.html#repeated-measure-designs"><i class="fa fa-check"></i><b>6.3.4</b> Repeated-Measure Designs</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="design-of-studies.html"><a href="design-of-studies.html#considerations-about-experiments"><i class="fa fa-check"></i><b>6.4</b> Considerations About Experiments</a><ul>
<li class="chapter" data-level="6.4.1" data-path="design-of-studies.html"><a href="design-of-studies.html#reproducibility"><i class="fa fa-check"></i><b>6.4.1</b> Reproducibility</a></li>
<li class="chapter" data-level="6.4.2" data-path="design-of-studies.html"><a href="design-of-studies.html#subjects-and-the-population"><i class="fa fa-check"></i><b>6.4.2</b> Subjects and the Population</a></li>
<li class="chapter" data-level="6.4.3" data-path="design-of-studies.html"><a href="design-of-studies.html#statistical-significance"><i class="fa fa-check"></i><b>6.4.3</b> Statistical Significance</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="design-of-studies.html"><a href="design-of-studies.html#terminology-for-experiments"><i class="fa fa-check"></i><b>6.5</b> Terminology for Experiments</a></li>
<li class="chapter" data-level="6.6" data-path="design-of-studies.html"><a href="design-of-studies.html#thoughts-on-r-5"><i class="fa fa-check"></i><b>6.6</b> Thoughts on R</a><ul>
<li class="chapter" data-level="6.6.1" data-path="design-of-studies.html"><a href="design-of-studies.html#new-r-functions-2"><i class="fa fa-check"></i><b>6.6.1</b> New R-functions</a></li>
<li class="chapter" data-level="6.6.2" data-path="design-of-studies.html"><a href="design-of-studies.html#book-chapter-notation"><i class="fa fa-check"></i><b>6.6.2</b> “Book-Chapter” Notation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="basic-probability.html"><a href="basic-probability.html"><i class="fa fa-check"></i><b>7</b> Basic Probability</a><ul>
<li class="chapter" data-level="7.1" data-path="basic-probability.html"><a href="basic-probability.html#introduction-3"><i class="fa fa-check"></i><b>7.1</b> Introduction</a></li>
<li class="chapter" data-level="7.2" data-path="basic-probability.html"><a href="basic-probability.html#probability"><i class="fa fa-check"></i><b>7.2</b> Probability</a><ul>
<li class="chapter" data-level="7.2.1" data-path="basic-probability.html"><a href="basic-probability.html#subjective-probability"><i class="fa fa-check"></i><b>7.2.1</b> Subjective Probability</a></li>
<li class="chapter" data-level="7.2.2" data-path="basic-probability.html"><a href="basic-probability.html#theoretical-probability"><i class="fa fa-check"></i><b>7.2.2</b> Theoretical Probability</a></li>
<li class="chapter" data-level="7.2.3" data-path="basic-probability.html"><a href="basic-probability.html#long-run-frequency-probability"><i class="fa fa-check"></i><b>7.2.3</b> Long-run Frequency Probability</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="basic-probability.html"><a href="basic-probability.html#what-is-a-random-variable"><i class="fa fa-check"></i><b>7.3</b> What is a Random Variable?</a><ul>
<li class="chapter" data-level="7.3.1" data-path="basic-probability.html"><a href="basic-probability.html#notation"><i class="fa fa-check"></i><b>7.3.1</b> Notation</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="basic-probability.html"><a href="basic-probability.html#discrete-random-variables"><i class="fa fa-check"></i><b>7.4</b> Discrete Random Variables</a><ul>
<li class="chapter" data-level="7.4.1" data-path="basic-probability.html"><a href="basic-probability.html#probability-distribution-functions-for-discrete-random-variables"><i class="fa fa-check"></i><b>7.4.1</b> Probability Distribution Functions for Discrete Random Variables</a></li>
<li class="chapter" data-level="7.4.2" data-path="basic-probability.html"><a href="basic-probability.html#expectation-of-discrete-random-variables"><i class="fa fa-check"></i><b>7.4.2</b> Expectation of Discrete Random Variables</a></li>
<li class="chapter" data-level="7.4.3" data-path="basic-probability.html"><a href="basic-probability.html#standard-deviation-of-discrete-random-variables"><i class="fa fa-check"></i><b>7.4.3</b> Standard Deviation of Discrete Random Variables</a></li>
<li class="chapter" data-level="7.4.4" data-path="basic-probability.html"><a href="basic-probability.html#using-ev-and-sd-to-evaluate-a-game"><i class="fa fa-check"></i><b>7.4.4</b> Using EV and SD to Evaluate a Game</a></li>
<li class="chapter" data-level="7.4.5" data-path="basic-probability.html"><a href="basic-probability.html#independence"><i class="fa fa-check"></i><b>7.4.5</b> Independence</a></li>
<li class="chapter" data-level="7.4.6" data-path="basic-probability.html"><a href="basic-probability.html#a-special-discrete-random-variable-binomial-random-variable"><i class="fa fa-check"></i><b>7.4.6</b> A Special Discrete Random Variable: Binomial Random Variable</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="basic-probability.html"><a href="basic-probability.html#continuous-random-variables"><i class="fa fa-check"></i><b>7.5</b> Continuous Random Variables</a><ul>
<li class="chapter" data-level="7.5.1" data-path="basic-probability.html"><a href="basic-probability.html#probability-density-functions-for-continuous-random-variables"><i class="fa fa-check"></i><b>7.5.1</b> Probability Density Functions for Continuous Random Variables</a></li>
<li class="chapter" data-level="7.5.2" data-path="basic-probability.html"><a href="basic-probability.html#a-special-continuous-random-variable-normal-random-variable"><i class="fa fa-check"></i><b>7.5.2</b> A Special Continuous Random Variable: Normal Random Variable</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="basic-probability.html"><a href="basic-probability.html#approximating-binomial-probabilities"><i class="fa fa-check"></i><b>7.6</b> Approximating Binomial Probabilities</a></li>
<li class="chapter" data-level="7.7" data-path="basic-probability.html"><a href="basic-probability.html#thoughts-on-r-6"><i class="fa fa-check"></i><b>7.7</b> Thoughts on R</a><ul>
<li class="chapter" data-level="7.7.1" data-path="basic-probability.html"><a href="basic-probability.html#new-r-functions-3"><i class="fa fa-check"></i><b>7.7.1</b> New R Functions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html"><i class="fa fa-check"></i><b>8</b> Probability in Sampling</a><ul>
<li class="chapter" data-level="8.1" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#the-population-and-the-sample"><i class="fa fa-check"></i><b>8.1</b> The Population and the Sample</a><ul>
<li class="chapter" data-level="8.1.1" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#parameters"><i class="fa fa-check"></i><b>8.1.1</b> Parameters</a></li>
<li class="chapter" data-level="8.1.2" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#statistics-1"><i class="fa fa-check"></i><b>8.1.2</b> Statistics</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#from-questions-to-parameters"><i class="fa fa-check"></i><b>8.2</b> From Questions to Parameters</a><ul>
<li class="chapter" data-level="8.2.1" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#one-mean"><i class="fa fa-check"></i><b>8.2.1</b> One Mean</a></li>
<li class="chapter" data-level="8.2.2" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#one-proportion"><i class="fa fa-check"></i><b>8.2.2</b> One Proportion</a></li>
<li class="chapter" data-level="8.2.3" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#difference-of-two-means"><i class="fa fa-check"></i><b>8.2.3</b> Difference of Two Means</a></li>
<li class="chapter" data-level="8.2.4" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#difference-of-two-proportions"><i class="fa fa-check"></i><b>8.2.4</b> Difference of Two Proportions</a></li>
<li class="chapter" data-level="8.2.5" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#mean-of-differences"><i class="fa fa-check"></i><b>8.2.5</b> Mean of Differences</a></li>
<li class="chapter" data-level="8.2.6" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#the-basic-five-parameters"><i class="fa fa-check"></i><b>8.2.6</b> The “Basic Five” Parameters</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#parameters-in-experiments"><i class="fa fa-check"></i><b>8.3</b> Parameters in Experiments</a><ul>
<li class="chapter" data-level="8.3.1" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#anchoring-in-m111survey"><i class="fa fa-check"></i><b>8.3.1</b> Anchoring in m111survey</a></li>
<li class="chapter" data-level="8.3.2" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#knife-or-gun-again"><i class="fa fa-check"></i><b>8.3.2</b> Knife or Gun (Again)</a></li>
<li class="chapter" data-level="8.3.3" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#more-anchoring"><i class="fa fa-check"></i><b>8.3.3</b> More Anchoring</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#ev-and-sd-of-estimators"><i class="fa fa-check"></i><b>8.4</b> EV and SD of Estimators</a><ul>
<li class="chapter" data-level="8.4.1" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#estimating-one-mean"><i class="fa fa-check"></i><b>8.4.1</b> Estimating One Mean</a></li>
<li class="chapter" data-level="8.4.2" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#estimating-the-difference-of-two-means"><i class="fa fa-check"></i><b>8.4.2</b> Estimating the Difference of Two Means</a></li>
<li class="chapter" data-level="8.4.3" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#estimating-one-proportion"><i class="fa fa-check"></i><b>8.4.3</b> Estimating One Proportion</a></li>
<li class="chapter" data-level="8.4.4" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#estimating-the-difference-of-two-proportions"><i class="fa fa-check"></i><b>8.4.4</b> Estimating the Difference of Two Proportions</a></li>
<li class="chapter" data-level="8.4.5" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#estimating-the-mean-of-differences"><i class="fa fa-check"></i><b>8.4.5</b> Estimating the Mean of Differences</a></li>
<li class="chapter" data-level="8.4.6" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#properties-of-ev-and-sd-of-estimators"><i class="fa fa-check"></i><b>8.4.6</b> Properties of EV and SD of Estimators</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#estimators-shape-of-the-distribution"><i class="fa fa-check"></i><b>8.5</b> Estimators: Shape of the Distribution</a></li>
<li class="chapter" data-level="8.6" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#probability-for-estimators"><i class="fa fa-check"></i><b>8.6</b> Probability for Estimators</a></li>
<li class="chapter" data-level="8.7" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#inference-with-estimators"><i class="fa fa-check"></i><b>8.7</b> Inference With Estimators</a><ul>
<li class="chapter" data-level="8.7.1" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#we-are-not-deities"><i class="fa fa-check"></i><b>8.7.1</b> We Are Not Deities</a></li>
<li class="chapter" data-level="8.7.2" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#practice-with-estimator-and-se"><i class="fa fa-check"></i><b>8.7.2</b> Practice With Estimator and SE</a></li>
<li class="chapter" data-level="8.7.3" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#the-68-95-rule-for-estimation"><i class="fa fa-check"></i><b>8.7.3</b> The 68-95 Rule for Estimation</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#summary-of-formulas"><i class="fa fa-check"></i><b>8.8</b> Summary of Formulas</a></li>
<li class="chapter" data-level="8.9" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#thoughts-on-r-7"><i class="fa fa-check"></i><b>8.9</b> Thoughts on R</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="confidence-intervals.html"><a href="confidence-intervals.html"><i class="fa fa-check"></i><b>9</b> Confidence Intervals</a><ul>
<li class="chapter" data-level="9.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#introduction-4"><i class="fa fa-check"></i><b>9.1</b> Introduction</a></li>
<li class="chapter" data-level="9.2" data-path="confidence-intervals.html"><a href="confidence-intervals.html#chapter-outline"><i class="fa fa-check"></i><b>9.2</b> Chapter Outline</a></li>
<li class="chapter" data-level="9.3" data-path="confidence-intervals.html"><a href="confidence-intervals.html#one-population-mean-mu"><i class="fa fa-check"></i><b>9.3</b> One Population Mean <span class="math inline">\(\mu\)</span></a><ul>
<li class="chapter" data-level="9.3.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#the-four-steps"><i class="fa fa-check"></i><b>9.3.1</b> The Four Steps</a></li>
<li class="chapter" data-level="9.3.2" data-path="confidence-intervals.html"><a href="confidence-intervals.html#under-the-hood"><i class="fa fa-check"></i><b>9.3.2</b> Under the Hood</a></li>
<li class="chapter" data-level="9.3.3" data-path="confidence-intervals.html"><a href="confidence-intervals.html#additional-example-and-further-ideas"><i class="fa fa-check"></i><b>9.3.3</b> Additional Example, and Further Ideas</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="confidence-intervals.html"><a href="confidence-intervals.html#difference-of-two-population-means-mu_1-mu_2"><i class="fa fa-check"></i><b>9.4</b> Difference of Two Population Means, <span class="math inline">\(\mu_1-\mu_2\)</span></a><ul>
<li class="chapter" data-level="9.4.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#the-four-steps-1"><i class="fa fa-check"></i><b>9.4.1</b> The Four Steps</a></li>
<li class="chapter" data-level="9.4.2" data-path="confidence-intervals.html"><a href="confidence-intervals.html#under-the-hood-1"><i class="fa fa-check"></i><b>9.4.2</b> Under the Hood</a></li>
<li class="chapter" data-level="9.4.3" data-path="confidence-intervals.html"><a href="confidence-intervals.html#additional-example"><i class="fa fa-check"></i><b>9.4.3</b> Additional Example</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="confidence-intervals.html"><a href="confidence-intervals.html#mean-of-differences-mu_d"><i class="fa fa-check"></i><b>9.5</b> Mean of Differences, <span class="math inline">\(\mu_d\)</span></a><ul>
<li class="chapter" data-level="9.5.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#the-four-steps-2"><i class="fa fa-check"></i><b>9.5.1</b> The Four Steps</a></li>
<li class="chapter" data-level="9.5.2" data-path="confidence-intervals.html"><a href="confidence-intervals.html#under-the-hood-2"><i class="fa fa-check"></i><b>9.5.2</b> Under the Hood</a></li>
<li class="chapter" data-level="9.5.3" data-path="confidence-intervals.html"><a href="confidence-intervals.html#additional-example-1"><i class="fa fa-check"></i><b>9.5.3</b> Additional Example</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="confidence-intervals.html"><a href="confidence-intervals.html#one-population-proportion-p"><i class="fa fa-check"></i><b>9.6</b> One Population Proportion, <span class="math inline">\(p\)</span></a><ul>
<li class="chapter" data-level="9.6.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#the-four-steps-3"><i class="fa fa-check"></i><b>9.6.1</b> The Four Steps</a></li>
<li class="chapter" data-level="9.6.2" data-path="confidence-intervals.html"><a href="confidence-intervals.html#under-the-hood-3"><i class="fa fa-check"></i><b>9.6.2</b> Under the Hood</a></li>
<li class="chapter" data-level="9.6.3" data-path="confidence-intervals.html"><a href="confidence-intervals.html#additional-example-2"><i class="fa fa-check"></i><b>9.6.3</b> Additional Example</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="confidence-intervals.html"><a href="confidence-intervals.html#difference-of-two-population-proportions-p_1-p_2"><i class="fa fa-check"></i><b>9.7</b> Difference of Two Population Proportions, <span class="math inline">\(p_1-p_2\)</span></a><ul>
<li class="chapter" data-level="9.7.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#the-four-steps-4"><i class="fa fa-check"></i><b>9.7.1</b> The Four Steps</a></li>
<li class="chapter" data-level="9.7.2" data-path="confidence-intervals.html"><a href="confidence-intervals.html#under-the-hood-4"><i class="fa fa-check"></i><b>9.7.2</b> Under the Hood</a></li>
<li class="chapter" data-level="9.7.3" data-path="confidence-intervals.html"><a href="confidence-intervals.html#additional-example-3"><i class="fa fa-check"></i><b>9.7.3</b> Additional Example</a></li>
</ul></li>
<li class="chapter" data-level="9.8" data-path="confidence-intervals.html"><a href="confidence-intervals.html#thoughts-on-r-8"><i class="fa fa-check"></i><b>9.8</b> Thoughts on R</a><ul>
<li class="chapter" data-level="9.8.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#new-r-functions-4"><i class="fa fa-check"></i><b>9.8.1</b> New R Functions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html"><i class="fa fa-check"></i><b>10</b> Tests of Significance</a><ul>
<li class="chapter" data-level="10.1" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#introduction-5"><i class="fa fa-check"></i><b>10.1</b> Introduction</a></li>
<li class="chapter" data-level="10.2" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#one-population-mean-mu-1"><i class="fa fa-check"></i><b>10.2</b> One Population Mean <span class="math inline">\(\mu\)</span></a><ul>
<li class="chapter" data-level="10.2.1" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#introductory-research-question"><i class="fa fa-check"></i><b>10.2.1</b> Introductory Research Question</a></li>
<li class="chapter" data-level="10.2.2" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#the-five-steps"><i class="fa fa-check"></i><b>10.2.2</b> The Five Steps</a></li>
<li class="chapter" data-level="10.2.3" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#under-the-hood-and-further-ideas"><i class="fa fa-check"></i><b>10.2.3</b> Under the Hood, and Further Ideas</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#difference-of-two-population-means-mu_1-mu_2-1"><i class="fa fa-check"></i><b>10.3</b> Difference of Two Population Means, <span class="math inline">\(\mu_1-\mu_2\)</span></a><ul>
<li class="chapter" data-level="10.3.1" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#the-difference-of-two-means"><i class="fa fa-check"></i><b>10.3.1</b> The Difference of Two Means</a></li>
<li class="chapter" data-level="10.3.2" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#the-five-steps-1"><i class="fa fa-check"></i><b>10.3.2</b> The Five Steps</a></li>
<li class="chapter" data-level="10.3.3" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#under-the-hood-5"><i class="fa fa-check"></i><b>10.3.3</b> Under the Hood</a></li>
<li class="chapter" data-level="10.3.4" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#additional-examples"><i class="fa fa-check"></i><b>10.3.4</b> Additional Examples</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#mean-of-differences-mu_d-1"><i class="fa fa-check"></i><b>10.4</b> Mean of Differences <span class="math inline">\(\mu_d\)</span></a><ul>
<li class="chapter" data-level="10.4.1" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#introductory-research-question-1"><i class="fa fa-check"></i><b>10.4.1</b> Introductory Research Question</a></li>
<li class="chapter" data-level="10.4.2" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#the-five-steps-2"><i class="fa fa-check"></i><b>10.4.2</b> The Five Steps</a></li>
<li class="chapter" data-level="10.4.3" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#under-the-hood-6"><i class="fa fa-check"></i><b>10.4.3</b> Under the Hood</a></li>
<li class="chapter" data-level="10.4.4" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#additional-examples-1"><i class="fa fa-check"></i><b>10.4.4</b> Additional Examples</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#one-population-proportion-p-1"><i class="fa fa-check"></i><b>10.5</b> One Population Proportion <span class="math inline">\(p\)</span></a><ul>
<li class="chapter" data-level="10.5.1" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#the-five-steps-3"><i class="fa fa-check"></i><b>10.5.1</b> The Five Steps</a></li>
<li class="chapter" data-level="10.5.2" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#under-the-hood-7"><i class="fa fa-check"></i><b>10.5.2</b> Under the Hood</a></li>
<li class="chapter" data-level="10.5.3" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#additional-examples-2"><i class="fa fa-check"></i><b>10.5.3</b> Additional Examples</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#difference-of-two-proportions-p_1-p_2"><i class="fa fa-check"></i><b>10.6</b> Difference of Two Proportions <span class="math inline">\(p_1-p_2\)</span></a><ul>
<li class="chapter" data-level="10.6.1" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#the-five-steps-4"><i class="fa fa-check"></i><b>10.6.1</b> The Five Steps</a></li>
<li class="chapter" data-level="10.6.2" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#working-with-summary-data-1"><i class="fa fa-check"></i><b>10.6.2</b> Working With Summary Data</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#further-considerations-about-significance-tests"><i class="fa fa-check"></i><b>10.7</b> Further Considerations About Significance Tests</a><ul>
<li class="chapter" data-level="10.7.1" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#types-of-error"><i class="fa fa-check"></i><b>10.7.1</b> Types of Error</a></li>
<li class="chapter" data-level="10.7.2" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#the-dangers-of-limited-reporting"><i class="fa fa-check"></i><b>10.7.2</b> The Dangers of Limited Reporting</a></li>
<li class="chapter" data-level="10.7.3" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#the-dangers-of-data-snooping"><i class="fa fa-check"></i><b>10.7.3</b> The Dangers of Data-Snooping</a></li>
</ul></li>
<li class="chapter" data-level="10.8" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#thoughts-about-r"><i class="fa fa-check"></i><b>10.8</b> Thoughts About R</a><ul>
<li class="chapter" data-level="10.8.1" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#new-code-to-learn"><i class="fa fa-check"></i><b>10.8.1</b> New Code to Learn?</a></li>
<li class="chapter" data-level="10.8.2" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#old-descriptive-friends"><i class="fa fa-check"></i><b>10.8.2</b> Old Descriptive Friends</a></li>
<li class="chapter" data-level="10.8.3" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#adding-a-variable-to-a-data-frame"><i class="fa fa-check"></i><b>10.8.3</b> Adding a Variable to a Data Frame</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="goodness-of-fit.html"><a href="goodness-of-fit.html"><i class="fa fa-check"></i><b>11</b> Goodness of Fit</a><ul>
<li class="chapter" data-level="11.1" data-path="goodness-of-fit.html"><a href="goodness-of-fit.html#the-gamblers-die"><i class="fa fa-check"></i><b>11.1</b> The Gambler’s Die</a></li>
<li class="chapter" data-level="11.2" data-path="goodness-of-fit.html"><a href="goodness-of-fit.html#chisqtestgc-for-goodness-of-fit"><i class="fa fa-check"></i><b>11.2</b> chisqtestGC() for Goodness of Fit</a><ul>
<li class="chapter" data-level="11.2.1" data-path="goodness-of-fit.html"><a href="goodness-of-fit.html#the-gamblers-die-as-a-test-of-significance"><i class="fa fa-check"></i><b>11.2.1</b> The Gambler’s Die as a Test of Significance</a></li>
<li class="chapter" data-level="11.2.2" data-path="goodness-of-fit.html"><a href="goodness-of-fit.html#facts-about-chi2-goodness-of-fit"><i class="fa fa-check"></i><b>11.2.2</b> Facts About <span class="math inline">\(\chi^2\)</span> Goodness of Fit</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="goodness-of-fit.html"><a href="goodness-of-fit.html#further-example-seating-preference"><i class="fa fa-check"></i><b>11.3</b> Further Example: Seating Preference</a></li>
<li class="chapter" data-level="11.4" data-path="goodness-of-fit.html"><a href="goodness-of-fit.html#further-example-nexus-attendance"><i class="fa fa-check"></i><b>11.4</b> Further Example: Nexus Attendance</a></li>
<li class="chapter" data-level="11.5" data-path="goodness-of-fit.html"><a href="goodness-of-fit.html#further-example-too-good-to-be-true"><i class="fa fa-check"></i><b>11.5</b> Further Example: Too Good to be True?</a></li>
<li class="chapter" data-level="11.6" data-path="goodness-of-fit.html"><a href="goodness-of-fit.html#thoughts-about-r-1"><i class="fa fa-check"></i><b>11.6</b> Thoughts About R</a><ul>
<li class="chapter" data-level="11.6.1" data-path="goodness-of-fit.html"><a href="goodness-of-fit.html#names-for-elements-in-a-list"><i class="fa fa-check"></i><b>11.6.1</b> Names for Elements in a List</a></li>
<li class="chapter" data-level="11.6.2" data-path="goodness-of-fit.html"><a href="goodness-of-fit.html#quick-null-probabilities"><i class="fa fa-check"></i><b>11.6.2</b> Quick Null Probabilities</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html"><i class="fa fa-check"></i><b>12</b> Appendix: Geek Notes</a><ul>
<li class="chapter" data-level="12.1" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#chapter-2"><i class="fa fa-check"></i><b>12.1</b> Chapter 2</a><ul>
<li class="chapter" data-level="12.1.1" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#more-on-structure"><i class="fa fa-check"></i><b>12.1.1</b> More on Structure</a></li>
<li class="chapter" data-level="12.1.2" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#fancier-histograms"><i class="fa fa-check"></i><b>12.1.2</b> Fancier Histograms</a></li>
<li class="chapter" data-level="12.1.3" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#combined-plots"><i class="fa fa-check"></i><b>12.1.3</b> Combined Plots</a></li>
<li class="chapter" data-level="12.1.4" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#adding-rugs"><i class="fa fa-check"></i><b>12.1.4</b> Adding Rugs</a></li>
<li class="chapter" data-level="12.1.5" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#tuning-density-plots"><i class="fa fa-check"></i><b>12.1.5</b> Tuning Density Plots</a></li>
<li class="chapter" data-level="12.1.6" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#more-on-standard-deviation"><i class="fa fa-check"></i><b>12.1.6</b> More on Standard Deviation</a></li>
<li class="chapter" data-level="12.1.7" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#cleveland-dotplots"><i class="fa fa-check"></i><b>12.1.7</b> Cleveland Dotplots</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#chapter-3"><i class="fa fa-check"></i><b>12.2</b> Chapter 3</a><ul>
<li class="chapter" data-level="12.2.1" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#fixed-and-random-effects-in-simulation"><i class="fa fa-check"></i><b>12.2.1</b> Fixed and Random effects in Simulation</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#chapter-4"><i class="fa fa-check"></i><b>12.3</b> Chapter 4</a><ul>
<li class="chapter" data-level="12.3.1" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#point-shapes-in-scatterplots-using-pch"><i class="fa fa-check"></i><b>12.3.1</b> Point Shapes in Scatterplots using <code>pch</code></a></li>
<li class="chapter" data-level="12.3.2" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#scatterplot-matrix"><i class="fa fa-check"></i><b>12.3.2</b> Scatterplot Matrix</a></li>
<li class="chapter" data-level="12.3.3" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#the-rationale-for-values-of-the-correlation-coefficient-r"><i class="fa fa-check"></i><b>12.3.3</b> The Rationale for Values of the Correlation Coefficient, <span class="math inline">\(r\)</span></a></li>
<li class="chapter" data-level="12.3.4" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#computation-of-the-coefficients-in-the-regression-equation"><i class="fa fa-check"></i><b>12.3.4</b> Computation of the Coefficients in the Regression Equation</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#chapter-5"><i class="fa fa-check"></i><b>12.4</b> Chapter 5</a><ul>
<li class="chapter" data-level="12.4.1" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#the-rbind-function"><i class="fa fa-check"></i><b>12.4.1</b> The <code>rbind()</code> Function</a></li>
<li class="chapter" data-level="12.4.2" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#the-cbind-function"><i class="fa fa-check"></i><b>12.4.2</b> The <code>cbind()</code> Function</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#chapter-6"><i class="fa fa-check"></i><b>12.5</b> Chapter 6</a><ul>
<li class="chapter" data-level="12.5.1" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#the-role-of-limits-in-density-plots"><i class="fa fa-check"></i><b>12.5.1</b> The Role of Limits in Density Plots</a></li>
<li class="chapter" data-level="12.5.2" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#more-about-legends"><i class="fa fa-check"></i><b>12.5.2</b> More about Legends</a></li>
<li class="chapter" data-level="12.5.3" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#more-on-strip-plots"><i class="fa fa-check"></i><b>12.5.3</b> More on Strip-plots</a></li>
<li class="chapter" data-level="12.5.4" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#assessing-statistical-significance"><i class="fa fa-check"></i><b>12.5.4</b> Assessing Statistical Significance</a></li>
<li class="chapter" data-level="12.5.5" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#interaction"><i class="fa fa-check"></i><b>12.5.5</b> Interaction</a></li>
</ul></li>
<li class="chapter" data-level="12.6" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#chapter-8"><i class="fa fa-check"></i><b>12.6</b> Chapter 8</a><ul>
<li class="chapter" data-level="12.6.1" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#we-lied-about-the-sd-formulas"><i class="fa fa-check"></i><b>12.6.1</b> We Lied About the SD Formulas!</a></li>
<li class="chapter" data-level="12.6.2" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#are-we-only-ever-interested-in-population-parameters"><i class="fa fa-check"></i><b>12.6.2</b> Are We Only Ever Interested in Population Parameters?</a></li>
</ul></li>
<li class="chapter" data-level="12.7" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#chapter-9"><i class="fa fa-check"></i><b>12.7</b> Chapter 9</a><ul>
<li class="chapter" data-level="12.7.1" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#distinction-between-t-and-z-in-confidence-intervals-for-means"><i class="fa fa-check"></i><b>12.7.1</b> Distinction Between <span class="math inline">\(t\)</span> and <span class="math inline">\(z\)</span> in Confidence Intervals for Means</a></li>
<li class="chapter" data-level="12.7.2" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#how-does-r-find-df"><i class="fa fa-check"></i><b>12.7.2</b> How Does R Find <span class="math inline">\(df\)</span>?</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Elementary Statistics with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="relationships-between-two-numerical-variables" class="section level1">
<h1><span class="header-section-number">Chapter 4</span> Relationships Between Two Numerical Variables</h1>
<div id="outline-1" class="section level2">
<h2><span class="header-section-number">4.1</span> Outline</h2>
<p>In the previous chapter, we investigated methods for describing relationships between two <em>factor</em> variables, using</p>
<ul>
<li>twoway tables and row percents for numerical desriptive statistics;</li>
<li>barcharts for graphical descitpive statistics;</li>
<li>the chi-square test, for inference.</li>
</ul>
<p>In this chapter, we are interested in describing relationships between <strong>two</strong> <em>numerical</em> variables.</p>
<p>In chapter 2, we learned about methods to graphically and numerically summarize <strong>one</strong> numerical variable. The methods we used were:</p>
<p><strong>Graphical</strong></p>
<ul>
<li>Histogram</li>
<li>Density Plot</li>
<li>Stem Plot</li>
<li>Box Plot (and the really cool Violin Plot)</li>
</ul>
<p><strong>Numerical</strong></p>
<ul>
<li>Median</li>
<li>Percentiles (quantiles)</li>
<li>5-number summary</li>
<li>Mean</li>
<li>SD</li>
<li>IQR</li>
</ul>
<p>We will now be learning to describe how <em>two numerical variables</em> relate to one another. Throughout this chapter, we’re going to work with three different datasets: <code>m111survey</code>, <code>pennstate1</code>, and <code>ucdavis1</code>. The datasets <code>pennstate1</code> and <code>ucdavis1</code> are both surveys of students at their respective schools, very similar to what we’ve seen in <code>m111survey</code>. You can put these datasets into your Global Environment, take a quick look at them, and learn more about them with:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(m111survey)
<span class="kw">View</span>(m111survey)
<span class="kw">help</span>(m111survey)

<span class="kw">data</span>(pennstate1)
<span class="kw">View</span>(pennstate1)
<span class="kw">help</span>(pennstate1)

<span class="kw">data</span>(ucdavis1)
<span class="kw">View</span>(ucdavis1)
<span class="kw">help</span>(ucdavis1)</code></pre></div>
</div>
<div id="statistical-relationships" class="section level2">
<h2><span class="header-section-number">4.2</span> Statistical Relationships</h2>
<p>When we look at relationships between numerical variables, there are 2 main kinds of relationships that interest us.</p>
<ul>
<li><em>Deterministic</em> relationships</li>
<li><em>Statistical</em> relationships</li>
</ul>
<p><em>Deterministic</em> relationships are the type you are used to seeing in algebra class. In this kind of relationship, the value of one variable can be <em>exactly</em> determined by the value of the other variable.</p>
<p>For example, consider the relationship between degrees Fahrenheit and degrees Celcius. If <span class="math inline">\(y= ^\circ\)</span> C and <span class="math inline">\(x= ^\circ\)</span> F, the deterministic relationship can be written</p>
<p><span class="math display">\[y=\frac{5}{9}(x-32).\]</span></p>
<p>The degrees Celcius (<span class="math inline">\(y\)</span>) is <em>exactly</em> determined by knowing the degrees Fahrenheit (<span class="math inline">\(x\)</span>). The graph of this equation is a line. See Figure [Deterministic Relationship].</p>
<div class="figure"><span id="fig:fcplot"></span>
<img src="bookdown-demo_files/figure-html/fcplot-1.png" alt="Deterministic Relationship.  This graph shows the relationship between Fahrenheit and Celcius." width="672" />
<p class="caption">
Figure 4.1: Deterministic Relationship. This graph shows the relationship between Fahrenheit and Celcius.
</p>
</div>
<p>We can see from the graph that there is no variation in the pattern. Every temperature in Fahrenheit has exactly one corresponding temperature in Celcius. We might regard Fahrenheit and Celcius as having a perfect relationship.</p>
<p><em>Statistical</em> relationships are the ones that we will study in this class. In this kind of relationship, there is variation from the average pattern. If we know the value of one variable, we can <em>estimate</em> the typical value of the other variable. However, this is only an estimation. There is no certainty!</p>
<p>For example, suppose we want to use the length of a person’s right handspan (the measurement of one’s outstretched right hand from thumb to pinky) to predict the person’s height. There is certainly a <em>relationship</em> between the length of one’s handspan and their height. People with large hands tend to be taller than people with small hands. However, there is not an equation (or a line) that will <em>exactly</em> tell us the height of a person with a certain handspan. Not every person with a handspan of 20 centimeters is exactly the same height. There is variation in their heights. What we’ve just described is a statistical relationship.</p>
<p>There are 3 tools that we will use to describe <em>statistical</em> relationships:</p>
<ul>
<li>Scatterplots</li>
<li>Correlation</li>
<li>Regression Equation</li>
</ul>
<div id="scatterplots" class="section level3">
<h3><span class="header-section-number">4.2.1</span> Scatterplots</h3>
<p>As we just discussed, our intuition tells us that a person with a large right handspan tends to be tall. Let’s investigate this idea with the following research question.</p>
<blockquote>
<p><strong>Research Question</strong>: At Pennstate, how is a student’s right handspan related to his/her height?</p>
</blockquote>
<p>A <em>scatterplot</em> is how we will graphically display the relationship between two numerical variables. Scatterplots allow us to visually identify</p>
<ul>
<li>overall patterns,</li>
<li>directions, and</li>
<li>strength of association</li>
</ul>
<p>between two numerical variables. The best way to get a feel for the relationship between two numerical variables is to take a look at the scatterplot.</p>
<div id="overall-patterns" class="section level4">
<h4><span class="header-section-number">4.2.1.1</span> Overall Patterns</h4>
<p>Let’s use the function <code>xyplot()</code> in <code>R</code> to create a scatterplot of the variables <strong>RtSpan</strong> and <strong>Height</strong> from the <code>pennstate1</code> dataset.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">xyplot</span>(Height~RtSpan,<span class="dt">data=</span>pennstate1,
       <span class="dt">xlab=</span><span class="st">&quot;Right Handspan (cm)&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;Height (in)&quot;</span>) </code></pre></div>
<div class="figure"><span id="fig:xyhandheight"></span>
<img src="bookdown-demo_files/figure-html/xyhandheight-1.png" alt="Hand/Height Scatterplot.  Relationship Between Right Handspan and Height" width="672" />
<p class="caption">
Figure 4.2: Hand/Height Scatterplot. Relationship Between Right Handspan and Height
</p>
</div>
<p>Each point, (<span class="math inline">\(x,y\)</span>), that you see on the scatterplot represents an individual in the dataset - one of the 190 Penn State students in the survey. The <span class="math inline">\(x\)</span>-coordinate of the point is that student’s right handspan, in centimeters. The <span class="math inline">\(y\)</span>-coordinate of the point is that student’s height, in inches.</p>
<p>The ‘formula-data’ input syntax for <code>xyplot()</code> should be starting to become familiar to you. This is the same syntax that we used to produce the graphical outputs from chapter 2. <code>R</code> will plot the variable in front of the <code>~</code> along the vertical axis and the variable behind the <code>~</code> along the horizontal axis. Typically, we put the explanatory variable along the horizontal axis and the response variable along the vertical axis.</p>
<p>You can control how the points in the scatterplot appear using <code>pch</code> and <code>col</code> in the <code>xyplot()</code> function. For example, we can make the scatterplot have solid red points. See Figure[Red Points].</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">xyplot</span>(Height~RtSpan,<span class="dt">data=</span>pennstate1,
       <span class="dt">xlab=</span><span class="st">&quot;Right Handspan (cm)&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;Height (in)&quot;</span>, 
       <span class="dt">col=</span><span class="st">&quot;red&quot;</span>,<span class="dt">pch=</span><span class="dv">19</span>) </code></pre></div>
<div class="figure"><span id="fig:xyhandheightred"></span>
<img src="bookdown-demo_files/figure-html/xyhandheightred-1.png" alt="Red Points:  Relationship Between Right Handspan and Height using solid red points" width="672" />
<p class="caption">
Figure 4.3: Red Points: Relationship Between Right Handspan and Height using solid red points
</p>
</div>
<p><strong>Note</strong>: If you are interested in making fancier scatterplots, there are different values of <code>pch</code> that produce various shapes for the points in the scatterplot. To learn more, consult GeekNotes. <code>R</code> will also provide a complete list of all available colors with:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">colors</span>()</code></pre></div>
<p>When we look at the overall pattern in the scatterplot in Figure[Hand/Height Scatterplot], it appears that students with large right handspans also tend to be tall. One question that may arise is whether this observed relationship is simply the result of the student’s sex. On average, males tend to have larger hands than females and also tend to be taller than females. As we did in chapter 2, we can look at parallel scatterplots in separate panels by “conditioning” on a category, such as <strong>Sex</strong>. See Figure[Parallel Hand/Height by Sex].</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">xyplot</span>(Height~RtSpan|Sex,<span class="dt">data=</span>pennstate1,
       <span class="dt">xlab=</span><span class="st">&quot;Right Handspan (cm)&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;Height (in)&quot;</span>,<span class="dt">pch=</span><span class="dv">19</span>)</code></pre></div>
<div class="figure"><span id="fig:parallelxyhandheight"></span>
<img src="bookdown-demo_files/figure-html/parallelxyhandheight-1.png" alt="Parallel Hand/Height by Sex:  Scatterplots showing the relationship between one's right handspan and height appear in separate panels." width="672" />
<p class="caption">
Figure 4.4: Parallel Hand/Height by Sex: Scatterplots showing the relationship between one’s right handspan and height appear in separate panels.
</p>
</div>
<p>We can see that the relationship we observed in the original scatterplot seems to hold separately for both males and females.</p>
<p>Parallel scatterplots can sometimes be hard to compare since they have separate x-axes. We can “overlay” these scatterplots, using one color for the points representing the males and another color for the points representing the females. Overlaying can be accomplished using the <em>groups</em> argument. See Figure[Overlayed Hand/Height by Sex].</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">xyplot</span>(Height~RtSpan,<span class="dt">groups=</span>Sex,<span class="dt">data=</span>pennstate1,
       <span class="dt">xlab=</span><span class="st">&quot;Right Handspan (cm)&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;Height (in)&quot;</span>,
       <span class="dt">pch=</span><span class="dv">19</span>,<span class="dt">auto.key=</span><span class="ot">TRUE</span>)</code></pre></div>
<div class="figure"><span id="fig:overlayedxyhandheight"></span>
<img src="bookdown-demo_files/figure-html/overlayedxyhandheight-1.png" alt="Overlayed Hand/Height by Sex:  One scatterplot showing the relationship between right handspan and height colored by sex." width="672" />
<p class="caption">
Figure 4.5: Overlayed Hand/Height by Sex: One scatterplot showing the relationship between right handspan and height colored by sex.
</p>
</div>
<p><strong>Note</strong>: Given several numerical variables, R can produce a group of scatterplots, one for each pair of variables—all in one graph. Such a graph is called a <em>scatterplot matrix</em>. For more information, consult GeekNotes.</p>
</div>
<div id="direction" class="section level4">
<h4><span class="header-section-number">4.2.1.2</span> Direction</h4>
<p>Viewing the scatterplot allows us to detect overall patterns. One way to describe the scatterplot is by giving a name to the <em>direction</em> of the observed pattern.</p>
<p>In the scatterplot Figure[Hand/Height Scatterplot], we could say that the variables <code>RtSpan</code> and <code>Height</code> are <em>positively associated</em> since students with larger handspans tend to be on the tall side and students with smaller handspans tend to be on the short side.</p>
<dl>
<dt>Positive Linear Association</dt>
<dd><p>Two numerical variables have a <em>positive linear association</em> if high values of one variable tend to accompany high values of the other and low values of one variable tend to accompany low values of the other.</p>
</dd>
</dl>
<p>To give a visualization for positively associated variables, let’s add a vertical line that marks the <em>mean</em> of the right handspans and a horizontal line that marks the <em>mean</em> of the heights to break the scatterplot into four “boxes”. See Figure[Positive Association].</p>
<div class="figure"><span id="fig:positivexyhandheight"></span>
<img src="bookdown-demo_files/figure-html/positivexyhandheight-1.png" alt="Positive Association: Most of the points are in the upper right and lower left box showing a positive association between the variables." width="672" />
<p class="caption">
Figure 4.6: Positive Association: Most of the points are in the upper right and lower left box showing a positive association between the variables.
</p>
</div>
<p>Notice that there are more points in the upper right box and lower left box than in the other two boxes. The upper right box includes points from individuals with higher than average right handspans <strong>and</strong> higher than average heights. The lower left box includes points from individuals with lower than average right handspans <strong>and</strong> lower than average heights. When most of the points in a scatterplot are located in these two boxes, the variables have a positive linear association.</p>
<dl>
<dt>Negative Linear Association</dt>
<dd><p>Two variables have a <em>negative linear association</em> if high values of one variable tend to accompany low values of the other and low values of one variable tend to accompany high values of the other.</p>
</dd>
</dl>
<p>Let’s take a look at an example of negatively associated variables from the <code>m111survey</code> dataset - <code>GPA</code> and <code>height</code>.</p>
<div class="figure"><span id="fig:negativexyhandheight"></span>
<img src="bookdown-demo_files/figure-html/negativexyhandheight-1.png" alt="Negative Association: Most of the points are in the lower right and upper left box showing a negative association between the variables." width="672" />
<p class="caption">
Figure 4.7: Negative Association: Most of the points are in the lower right and upper left box showing a negative association between the variables.
</p>
</div>
<p>Notice that in this scatterplot, there are more points in the upper left box and the lower right box. (See Figure[Negative Association].) The upper left box includes points from individuals with lower than average GPA’s <strong>and</strong> higher than average heights. The lower right box includes points from individuals with higher than average GPA’s <strong>and</strong> lower than average heights. When most of the points in a scatterplot are located in these two boxes, the variables have a <em>negative linear association</em>.</p>
<dl>
<dt>No Associaton</dt>
<dd><p>Two variables have <em>no association</em> if there is no apparent relationship between the two variables.</p>
</dd>
</dl>
<p>Let’s look at the <em>association</em> between an individual’s height, <code>Height</code>, and the hours of sleep they got last night, <code>HrsSleep</code>, from the <code>pennstate1</code> dataset.</p>
<div class="figure"><span id="fig:noassocxyhandheight"></span>
<img src="bookdown-demo_files/figure-html/noassocxyhandheight-1.png" alt="No Association: There is no apparent pattern in where the points lie." width="672" />
<p class="caption">
Figure 4.8: No Association: There is no apparent pattern in where the points lie.
</p>
</div>
<p>In the scatterplot in Figure[No Association], it appears that all of the boxes have <em>about</em> the same number of points in them. When this is the case, the variables have <em>no linear association</em>.</p>
<p>So far we have been interested in variables that appear to have a <em>linear association</em>, and our goal has been to describe the linear association that we see in a scatterplot using the equation of straight line. Data with nonlinear association certainly exists! For example, <em>curvilinear</em> data follows the trend of a curve, rather than a line. You can see an example of this by looking at the <code>fuel</code> dataset. Read the <code>help</code> file on this data to understand what the variables are.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(fuel)
<span class="kw">View</span>(fuel)
<span class="kw">help</span>(fuel)</code></pre></div>
<div class="figure"><span id="fig:xyfuel"></span>
<img src="bookdown-demo_files/figure-html/xyfuel-1.png" alt="Curvilinear: Efficiency (liters of fuel required to travel 100 kilometers) versus Speed (kilometers per hour)" width="672" />
<p class="caption">
Figure 4.9: Curvilinear: Efficiency (liters of fuel required to travel 100 kilometers) versus Speed (kilometers per hour)
</p>
</div>
<p>The scatterplot clearly shows that this data would not be well represented by a line. (See Figure[Curvilinear].) As a vehicle’s speed increases up to about 60 kph, the amount of fuel required to travel 100 kilometers decreases. However, as a vehicle’s speed increases from about 60 kph, the fuel efficiency increases: this is one type of curvilinear relationship. We will offer a rudimentary discussion of nonlinear relationships later on in this Chapter.</p>
<p>For now, we’ll stick with linear relationships.</p>
</div>
</div>
<div id="correlation" class="section level3">
<h3><span class="header-section-number">4.2.2</span> Correlation</h3>
<div id="strength-of-association" class="section level4">
<h4><span class="header-section-number">4.2.2.1</span> Strength of Association</h4>
<p>So far, we’ve investigated relationships between two numerical variables by looking at the scatterplot and making note of the observed pattern of the points, and their direction of association. However, as we can see in the following scatterplots, we should also consider the <em>strength</em> of association between two variables. See Figure<a href="relationships-between-two-numerical-variables.html#strength-of-association">Strength of Association</a>.</p>
<div class="figure"><span id="fig:twopositivexy"></span>
<img src="bookdown-demo_files/figure-html/twopositivexy-1.png" alt="Strength of Association:  Two examples of pairs of variables with positive linear association.  The first scatterplot shows a positive linear association between Height (in) and Fastest Speed Ever Driven (mph).  The second scatterplot shows a stronger positive linear association between Height (in) and Ideal Height (in)." width="268.8" />
<p class="caption">
Figure 4.10: Strength of Association: Two examples of pairs of variables with positive linear association. The first scatterplot shows a positive linear association between Height (in) and Fastest Speed Ever Driven (mph). The second scatterplot shows a stronger positive linear association between Height (in) and Ideal Height (in).
</p>
</div>
<div class="figure"><span id="fig:twopositivexy"></span>
<img src="bookdown-demo_files/figure-html/twopositivexy-2.png" alt="Strength of Association:  Two examples of pairs of variables with positive linear association.  The first scatterplot shows a positive linear association between Height (in) and Fastest Speed Ever Driven (mph).  The second scatterplot shows a stronger positive linear association between Height (in) and Ideal Height (in)." width="268.8" />
<p class="caption">
Figure 4.11: Strength of Association: Two examples of pairs of variables with positive linear association. The first scatterplot shows a positive linear association between Height (in) and Fastest Speed Ever Driven (mph). The second scatterplot shows a stronger positive linear association between Height (in) and Ideal Height (in).
</p>
</div>
<p>These scatterplots both display 2 variables that are <em>positively</em> associated, but there is less “scatter” in the second plot. The variable <strong>height</strong> appears to have a stronger association with <strong>ideal_ht</strong> than it does with <strong>fastest</strong>. To distinguish between the amount of “scatter” in a plot, it is useful to assign a numerical value to the strength of association.</p>
<dl>
<dt>Correlation</dt>
<dd><p><em>Correlation</em> is the numerical measure of the direction and strength of the linear association between two numerical variables.</p>
</dd>
</dl>
<p>The formula for the <em>correlation coefficient</em>, <span class="math inline">\(r\)</span>, is written:</p>
<p><span class="math display">\[ r=\frac{1}{n-1}\sum{\bigg(\frac{x_i-\bar{x}}{s_x}\bigg)\bigg(\frac{y_i-\bar{y}}{s_y}\bigg)}\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(n\)</span> denotes the number of values in the list</li>
<li><span class="math inline">\(\sum\)</span> means summing</li>
<li><span class="math inline">\(x_i\)</span> denotes the individual <span class="math inline">\(x\)</span> values</li>
<li><span class="math inline">\(\bar{x}\)</span> denotes the average of the <span class="math inline">\(x\)</span>’s</li>
<li><span class="math inline">\(s_x\)</span> denotes the SD of the <span class="math inline">\(x\)</span>’s</li>
<li><span class="math inline">\(y_i\)</span> denotes the individual <span class="math inline">\(y\)</span> values</li>
<li><span class="math inline">\(\bar{y}\)</span> denotes the average of the <span class="math inline">\(y\)</span>’s</li>
<li><span class="math inline">\(s_y\)</span> denotes the SD of the <span class="math inline">\(y\)</span>’s</li>
</ul>
<p>Since this calculation can be cumbersome, we will use R’s built in function, <code>cor()</code>. The correlation coefficient for the variables <strong>height</strong> and <strong>fastest</strong> from the <code>m111survey</code> dataset plotted in the first scatterplot in Figure<a href="relationships-between-two-numerical-variables.html#strength-of-association">Strength of Association</a> can be found by:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(fastest~height,<span class="dt">data=</span>m111survey,<span class="dt">use=</span><span class="st">&quot;na.or.complete&quot;</span>)</code></pre></div>
<pre><code>## [1] 0.1708742</code></pre>
<p>Let’s compare this to the correlation coefficient for the variables <strong>height</strong> and <strong>ideal_ht</strong> from the <code>m111survey</code> dataset plotted in the second scatterplot in Figure<a href="relationships-between-two-numerical-variables.html#strength-of-association">Strength of Association</a>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(ideal_ht~height,<span class="dt">data=</span>m111survey,<span class="dt">use=</span><span class="st">&quot;na.or.complete&quot;</span>)</code></pre></div>
<pre><code>## [1] 0.832047</code></pre>
<p>What we’ve just observed holds true in general.</p>
<ul>
<li><p><em>Positively associated</em> variables have a <em>positive</em> correlation coefficient, <span class="math inline">\(r&gt;0\)</span>. Consult Geek Notes for a detailed explanation.</p></li>
<li><p>The stronger the association is between variables, the larger the correlation coefficient, <span class="math inline">\(r\)</span>, will be.</p></li>
</ul>
<p>The same ideas hold true for <em>negatively</em> associated variables and variables with <em>no</em> association. Let’s summarize all of the properties of the correlation coefficient, <span class="math inline">\(r\)</span>.</p>
<p><strong>Properties of <span class="math inline">\(r\)</span></strong></p>
<ul>
<li><p><span class="math inline">\(r\)</span> always falls between 1 and -1.</p></li>
<li><p>The sign of r indicates the <em>direction</em> of the relationship.</p>
<ul>
<li><span class="math inline">\(r&gt;0\)</span> indicates a <em>positive linear association</em></li>
<li><span class="math inline">\(r&lt;0\)</span> indicates a <em>negative linear association</em></li>
</ul></li>
<li><p>The <em>magnitude</em> of r indicates the <em>strength</em> of the relationship. See Figure[Correlation Values].</p>
<ul>
<li><span class="math inline">\(r = 1\)</span> indicates a <em>perfect positive</em> linear relationship. All points fall exactly on a line sloping upward.</li>
<li><span class="math inline">\(r = -1\)</span> indicates a <em>perfect negative</em> linear relationship. All points fall exactly on a line sloping downward.</li>
<li><span class="math inline">\(r = 0\)</span> indicates <em>no</em> linear relationship.</li>
</ul></li>
</ul>
<div class="figure"><span id="fig:correlationvalues"></span>
<img src="bookdown-demo_files/figure-html/correlationvalues-1.png" alt="Correlation Values:  The first scatterplot represents two variables that have a perfect positive linear relationship, $r=1$.  The second scatterplot represents two variables that have a perfect negative linear relationship, $r=-1$.  The third scatterplot represents two variables that have no linear relationship, $r=0$." width="672" />
<p class="caption">
Figure 4.12: Correlation Values: The first scatterplot represents two variables that have a perfect positive linear relationship, <span class="math inline">\(r=1\)</span>. The second scatterplot represents two variables that have a perfect negative linear relationship, <span class="math inline">\(r=-1\)</span>. The third scatterplot represents two variables that have no linear relationship, <span class="math inline">\(r=0\)</span>.
</p>
</div>
<p>You can investigate this with the following app, as well.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">require</span>(manipulate)
<span class="kw">VaryCorrelation</span>()</code></pre></div>
<p>Let’s look at an example.</p>
<blockquote>
<p><strong>Research Question</strong>: At UCDavis, how is a student’s mom’s height (<strong>momheight</strong>) related to their dad’s height (<strong>dadheight</strong>)?</p>
</blockquote>
<p>Since we are interested in how a mother’s height is related to a father’s height, we will treat <strong>dadheight</strong> as the explanatory variable and <strong>momheight</strong> as the response variable. We will start by taking a look at the scatterplot. See Figure[Mom/Dad Height].</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">xyplot</span>(momheight~dadheight,<span class="dt">data=</span>ucdavis1)</code></pre></div>
<div class="figure"><span id="fig:xymomdadheight"></span>
<img src="bookdown-demo_files/figure-html/xymomdadheight-1.png" alt="Mom/Dad Height" width="672" />
<p class="caption">
Figure 4.13: Mom/Dad Height
</p>
</div>
<p>Since our cloud of points seems to be somewhat shaped upward to the right, it seems that students with tall dads tend to have tall moms as well and students with short dads also have short moms. This suggests that the correlation coefficient will be positive. However, since the cloud of points is not very tightly clustered, we might think that this association is not very strong. We might predict that the correlation coefficient, <span class="math inline">\(r\)</span>, will be positive but closer to 0 than it is to 1. Let’s find out.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(momheight~dadheight,<span class="dt">data=</span>ucdavis1,<span class="dt">use=</span><span class="st">&quot;na.or.complete&quot;</span>)</code></pre></div>
<pre><code>## [1] 0.2571501</code></pre>
</div>
</div>
<div id="regression-equation" class="section level3">
<h3><span class="header-section-number">4.2.3</span> Regression Equation</h3>
<p><em>Regression analysis</em> is used to numerically explain the linear relationship between two numerical variables using the equation of a line. It is much more specific than the visual analysis we’ve been making by looking at scatterplots.</p>
<p>Recall that the equation of the line <span class="math inline">\(y=\frac{5}{9}(x-32)\)</span> was used to describe the <em>deterministic</em> relationship between degrees Celcius and degrees Fahrenheit. This equation let us determine the <em>exact</em> temperature in Celcius by knowing the temperature in Fahrenheit.</p>
<p>The <em>regression equation</em> is the equation of a line that is used to <em>predict</em> the value for the response variable (<span class="math inline">\(y\)</span>) from a known value of the explanatory variable (<span class="math inline">\(x\)</span>) in a <em>statistical</em> relationship. It describes how, <em>on average</em>, the response variable is related to the explanatory variable.</p>
<p>In general, the equation of the regression line is</p>
<p><span class="math display">\[\hat{y}=a+bx,\]</span></p>
<p>where:</p>
<ul>
<li><p><span class="math inline">\(a\)</span> is the <em><span class="math inline">\(y\)</span>-intercept</em>. (The <span class="math inline">\(y\)</span>-intercept is the point where the line crosses the vertical axis. It is the height of the line at <span class="math inline">\(x=0\)</span>.)</p></li>
<li><p><span class="math inline">\(b\)</span> is the <em>slope</em>. (The slope is the inclination or orientation of the line. It is calculated by the ratio <span class="math inline">\(\frac{\mbox{rise}}{\mbox{run}}\)</span>.)</p></li>
<li><p><span class="math inline">\(x\)</span> is the known value of the explanatory variable.</p></li>
<li><p><span class="math inline">\(\hat{y}\)</span> is the <em>predicted</em> value of the response variable.</p></li>
</ul>
<p>The regression line is the line that best approximates the data in the scatterplot. Returning to our original research question involving the variables <strong>Height</strong> and <strong>RtSpan</strong> from the <code>pennstate1</code> dataset, let’s take a look at the regression line. See Figure[Hand/Height Regression Line].</p>
<div class="figure"><span id="fig:regressionlineheightrtspan"></span>
<img src="bookdown-demo_files/figure-html/regressionlineheightrtspan-1.png" alt="Hand/Height Regression Line:  The regression line is plotted on the scatterplot showing the relationship between right handspan and height." width="672" />
<p class="caption">
Figure 4.14: Hand/Height Regression Line: The regression line is plotted on the scatterplot showing the relationship between right handspan and height.
</p>
</div>
<p>Each point <span class="math inline">\((x,y)\)</span> on the scatterplot is an observation—known <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>-values. These points correspond to the measurements for an actual individual in the sample. Each point <span class="math inline">\((x,\hat{y})\)</span> on the regression line is a known <span class="math inline">\(x\)</span>-value and its predicted response, <span class="math inline">\(\hat{y}\)</span>.</p>
<div id="residuals" class="section level4">
<h4><span class="header-section-number">4.2.3.1</span> Residuals</h4>
<p>You can see how the regression line in Figure[Hand/Height Regression Line] seems to do a good job describing the trend of the points in the scatterplot. In fact, it “best fits” the data. The regression (best fit) line is the line that is collectively the closest, in terms of vertical measurement, to all of the points on the scatterplot. These vertical measurements are called <em>residuals</em>. Residuals measure the size of the prediction errors.</p>
<dl>
<dt>Residuals</dt>
<dd><p>For a given data point <span class="math inline">\((x,y)\)</span>, the <em>residual</em> is the difference between the observed response and the response that is predicted by the regression line.</p>
</dd>
</dl>
<p>This can be written</p>
<p><span class="math display">\[y - \hat{y}.\]</span></p>
<p>On the graph, a residual is the vertical distance between a point and the regression line. Several residuals are plotted on the scatterplot shown in Figure<a href="relationships-between-two-numerical-variables.html#residuals">Residuals</a>.</p>
<pre><code>## Predict Height is about 58.07,
## give or take 3.285 or so for chance variation.</code></pre>
<pre><code>## Predict Height is about 61.79,
## give or take 3.209 or so for chance variation.</code></pre>
<pre><code>## Predict Height is about 63.03,
## give or take 3.191 or so for chance variation.</code></pre>
<div class="figure"><span id="fig:handheightresiduals"></span>
<img src="bookdown-demo_files/figure-html/handheightresiduals-1.png" alt="Residuals" width="672" />
<p class="caption">
Figure 4.15: Residuals
</p>
</div>
<p>A residual can be computed for every point on the scatterplot. The regression line <span class="math inline">\(\hat{y} = a + bx\)</span> is determined by choosing <span class="math inline">\(a\)</span> (intercept) and <span class="math inline">\(b\)</span> (slope) so that the sum of the (squared) residuals is minimized.</p>
<p><span class="math display">\[\mbox{Sum of Squares }= \sum(\mbox{ residuals})^2 = \sum(y_i-\hat{y})^2 \]</span></p>
<p>Investigate how to minimize the sum of squared residuals with the following app.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">require</span>(manipulate)
<span class="kw">FindRegLine</span>()</code></pre></div>
<p>If you are interested in how the actual values of <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> are calculated, consult Geek Notes.</p>
</div>
<div id="predictions" class="section level4">
<h4><span class="header-section-number">4.2.3.2</span> Predictions</h4>
<p>Now that we know what the regression equation means and how it is found, let’s use it to make some statements about the Pennstate scatterplot of heights and right handspans.</p>
<blockquote>
<p><strong>Research Question</strong>: What is the predicted height of a Pennstate student with a right handspan measurement of 22 cm?</p>
</blockquote>
<p>We have already seen the graph of the regression line in Figure[Hand/Height Regression Line]. Now, we would like to know the equation for this line. R has a built in function, <code>lmGC()</code>, to compute this equation. (The <code>lm</code> stands for “linear model”.) This function also has the option to graph the regression line (set <code>graph=TRUE</code>).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">lmGC</span>(Height~RtSpan,<span class="dt">data=</span>pennstate1,<span class="dt">graph=</span><span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## 
##  Linear Regression
## 
## Correlation coefficient r =  0.6314 
## 
## Equation of Regression Line:
## 
##   Height = 41.9593 + 1.2394 * RtSpan 
## 
## Residual Standard Error: s   = 3.1486 
## R^2 (unadjusted):        R^2 = 0.3987</code></pre>
<div class="figure"><span id="fig:heighthandxyreg"></span>
<img src="bookdown-demo_files/figure-html/heighthandxyreg-1.png" alt="Height/Hand Regression:  In the lmGC function, the parameter graph=TRUE will plot the regression line as well as giving the equation of the regresion line." width="672" />
<p class="caption">
Figure 4.16: Height/Hand Regression: In the lmGC function, the parameter graph=TRUE will plot the regression line as well as giving the equation of the regresion line.
</p>
</div>
<p>So the equation of our regression line is:</p>
<p><span class="math display">\[\hat{y}=41.959349+1.239448 x\]</span></p>
<p>We can now answer the research question two different ways. We can use R as a calculator and plug <span class="math inline">\(x=22\)</span> into the equation above.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="fl">41.95935+1.239448</span>*<span class="dv">22</span></code></pre></div>
<pre><code>## [1] 69.22721</code></pre>
<p>A Penn State student with a right handspan of 22 centimeters will have a predicted height of 69.22721 inches.</p>
<p>Another way to do this is using the <code>predict()</code> function. The <code>predict()</code> function requires two inputs:</p>
<ul>
<li>a linear model,</li>
<li>a value of the explanatory variables, <span class="math inline">\(x\)</span>.</li>
</ul>
<p>In order to use the <code>predict()</code> function, you should store your linear model in a variable.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">handheightmod &lt;-<span class="st"> </span><span class="kw">lmGC</span>(Height~RtSpan,<span class="dt">data=</span>pennstate1)
<span class="kw">predict</span>(handheightmod,<span class="dv">22</span>)</code></pre></div>
<pre><code>## Predict Height is about 69.23,
## give or take 3.158 or so for chance variation.</code></pre>
<p>In addition to the prediction, R gives you a <em>prediction standard error</em> — a rough estimate of how much your prediction of the person’s height is liable to differ from his or her actual height. In general, the regression line’s prediction could easily differ from the actual <span class="math inline">\(y\)</span> value (the height) by as much as a couple of prediction standard errors.</p>
<p>If you would like to have a better feel for where the actual value of <span class="math inline">\(y\)</span> might lie, consider asking for a <em>prediction interval</em>, as follows:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">predict</span>(handheightmod,<span class="dv">22</span>,<span class="dt">level=</span><span class="fl">0.95</span>)</code></pre></div>
<pre><code>## Predict Height is about 69.23,
## give or take 3.158 or so for chance variation.
## 
## 95%-prediction interval:
##           lower.bound         upper.bound          
##           62.997191           75.457220</code></pre>
<p>You can be about 95%-confident that the actual height of a person with a handspan of 22 centimeters is somewhere between 63 and 74.5 inches — the stated bounds of the 95%-prediction interval above.</p>
<p>You can ask for prediction intervals at any level of confidence between 0% and 100%,simply by varying the value of the <code>level</code> parameter. For an 80%-prediction interval, run the command:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">predict</span>(handheightmod,<span class="dv">22</span>,<span class="dt">level=</span><span class="fl">0.80</span>)</code></pre></div>
<pre><code>## Predict Height is about 69.23,
## give or take 3.158 or so for chance variation.
## 
## 80%-prediction interval:
##           lower.bound         upper.bound          
##           65.165568           73.288843</code></pre>
<p>The prediction interval is narrower than before, but you pay a price for the extra precision: now you are only 80%-confident that the actual height lies somewhere inside of the interval.</p>
</div>
<div id="interpretation-of-slope-and-intercept" class="section level4">
<h4><span class="header-section-number">4.2.3.3</span> Interpretation of Slope and Intercept</h4>
<p>It’s also important that we know how to interpret the <em>slope</em> and <em>intercept</em> of a regression line. Let’s take a look at the <code>pushups</code> dataset.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(pushups)
<span class="kw">View</span>(pushups)
<span class="kw">help</span>(pushups)</code></pre></div>
<p>Now, we can view the equation of the regression line as well as the scatterplot with the regression line plotted. See Figure[Pushups].</p>
<pre><code>## 
##  Linear Regression
## 
## Correlation coefficient r =  -0.4675 
## 
## Equation of Regression Line:
## 
##   weight = 247.4886 + -0.8243 * pushups 
## 
## Residual Standard Error: s   = 39.5677 
## R^2 (unadjusted):        R^2 = 0.2185</code></pre>
<div class="figure"><span id="fig:xyweightpushups"></span>
<img src="bookdown-demo_files/figure-html/xyweightpushups-1.png" alt="Pushups:  Scatterplot and Regression line for Pushups versus Weight Relationship" width="672" />
<p class="caption">
Figure 4.17: Pushups: Scatterplot and Regression line for Pushups versus Weight Relationship
</p>
</div>
<ul>
<li><p>What does the intercept mean? 247.49 is the <em>predicted</em> weight of a GC football player who cannot do any pushups in 2 minutes.</p></li>
<li><p>What does the slope mean? The <em>predicted</em> weight of a football player changes by -0.82 pounds as the max number of pushups in two minutes increases by 1. In other words, for every one pushup increase, the predicted weight of the football player decreases by 0.82 pounds. This tells us that there is a <em>negative</em> association between max number of pushups and weight!</p></li>
</ul>
<p><strong>Note:</strong> The interpretation of the intercept doesn’t always make sense! Consider, for example, what would happen if we used <strong>weight</strong> as the explanatory variable and <strong>pushups</strong> as the response. See Figure[Slope/Intercept Interpretation].</p>
<pre><code>## 
##  Linear Regression
## 
## Correlation coefficient r =  -0.4675 
## 
## Equation of Regression Line:
## 
##   pushups = 97.6857 + -0.2651 * weight 
## 
## Residual Standard Error: s   = 22.4414 
## R^2 (unadjusted):        R^2 = 0.2185</code></pre>
<div class="figure"><span id="fig:xypushupsweight"></span>
<img src="bookdown-demo_files/figure-html/xypushupsweight-1.png" alt="Slope/Intercept Interpretation:  Slope and intercept interpretation for the regression line used to predict maximum number of pushups from weight of a football player." width="672" />
<p class="caption">
Figure 4.18: Slope/Intercept Interpretation: Slope and intercept interpretation for the regression line used to predict maximum number of pushups from weight of a football player.
</p>
</div>
<ul>
<li><p>Intercept Interpretation: 247.49 is the <em>predicted</em> maximum number of pushups of a GC football player who weighs 0 pounds can do in 2 minutes. This doesn’t make any logical sense!</p></li>
<li><p>Slope Interpretation: The <em>predicted</em> maximum number of pushups that a football player can do in two minutes changes by -0.82 as the weight of the football player increases by 1 pound. In other words, for every one pound increase in weight, the predicted maximum number of pushups decreases by 0.82.</p></li>
</ul>
</div>
<div id="how-well-does-our-regression-line-fit" class="section level4">
<h4><span class="header-section-number">4.2.3.4</span> How Well does our Regression Line fit?</h4>
<p>If all the data in a scatterplot lie <em>exactly on</em> the regression line, we say that our regression line perfectly explains the data. However, this is rarely the case. We usually have points that do not lie on the regression line. Anywhere that this happens, we have <em>variation</em> that is not explained by the regression line. If the data is not on a line, then a line will not be a <em>perfect</em> explanation of the data.</p>
<p>One way we can measure this variation is the <em>residual standard error</em> — sometimes called RSE, or even <span class="math inline">\(s\)</span>, for short. This quantity does exactly what its name implies - it measures the <em>spread</em> of the residuals (those vertical distances between observations and the regression line). This value is in the output of the <code>lmGC</code> function.</p>
<p>However, we run into a problem when using the residual standard error to measure the variation in the plot. The residual standard error for the <strong>Height</strong> and <strong>RtSpan</strong> data from <code>pennstate1</code> is 3.148589.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">lmGC</span>(Height~RtSpan,<span class="dt">data=</span>pennstate1)</code></pre></div>
<pre><code>## 
##  Linear Regression
## 
## Correlation coefficient r =  0.6314 
## 
## Equation of Regression Line:
## 
##   Height = 41.9593 + 1.2394 * RtSpan 
## 
## Residual Standard Error: s   = 3.1486 
## R^2 (unadjusted):        R^2 = 0.3987</code></pre>
<p>For this model, the unit of measure for height is inches. Consider what happens when we change this model by converting the unit of measure for height to feet. Take a look at the scatterplots and regression lines for these two models. See Figure[Different Units].</p>
<div class="figure"><span id="fig:unitconversionmodels"></span>
<img src="bookdown-demo_files/figure-html/unitconversionmodels-1.png" alt="Different Units:  Compare the scatterplot and regression line for RtSpan (cm) vs. Height (inches) and the scatterplot and regression line for RtSpan (cm) vs. Height (feet)." width="268.8" />
<p class="caption">
Figure 4.19: Different Units: Compare the scatterplot and regression line for RtSpan (cm) vs. Height (inches) and the scatterplot and regression line for RtSpan (cm) vs. Height (feet).
</p>
</div>
<div class="figure"><span id="fig:unitconversionmodels"></span>
<img src="bookdown-demo_files/figure-html/unitconversionmodels-2.png" alt="Different Units:  Compare the scatterplot and regression line for RtSpan (cm) vs. Height (inches) and the scatterplot and regression line for RtSpan (cm) vs. Height (feet)." width="268.8" />
<p class="caption">
Figure 4.20: Different Units: Compare the scatterplot and regression line for RtSpan (cm) vs. Height (inches) and the scatterplot and regression line for RtSpan (cm) vs. Height (feet).
</p>
</div>
<p>This change in unit of the response variable does not affect the way the scatterplot of regression line looks. The regression line did an equally good job of fitting the data, in both scatterplots. It does, however, directly affect the value of the residuals. The residuals in the first plot have a much larger value than the residuals in the second plot. This causes the <em>spread</em> of the residuals (the residual standard error) to be bigger in the first plot. Hence, residual standard error is not the best way of measuring the variation accounted for by the regression line.</p>
<p>Another measure of the “explained variation” in the scatterplot is the <em>squared correlation</em>, <span class="math inline">\(r^2\)</span>. This also measures how well our regression line fits the data. However, it tells us the <em>proportion</em> of variation in the response variable that is explained by the explanatory variable. A change in unit (or scale) will not affect the value of <span class="math inline">\(r^2\)</span>.</p>
</div>
<div id="properties-of-r2" class="section level4">
<h4><span class="header-section-number">4.2.3.5</span> Properties of <span class="math inline">\(r^2\)</span></h4>
<ul>
<li><span class="math inline">\(r^2\)</span> always has a value between 0 and 1.</li>
<li><span class="math inline">\(r^2=1\)</span> implies perfect linear association between explanatory and response variables.</li>
<li><span class="math inline">\(r^2=0\)</span> implies no linear association.</li>
</ul>
<p><strong>Beware</strong>: A low <span class="math inline">\(r^2\)</span> value does not necessarily mean that there is <em>no</em> relationship between the explanatory variable and the response. It might mean that a linear model is not an appropriate model! So, a low <span class="math inline">\(r^2\)</span> value means one of two things for us:</p>
<ul>
<li>There is a linear relationship between the variables, but there’s just alot of scatter in the data.</li>
<li>You might have the wrong model. In other words, the data might not follow a linear pattern. For example, consider the relationship we saw in the curvilinear <code>fuel</code> data from before. See Figure[R-squared for Nonlinear Data].</li>
</ul>
<div class="figure"><span id="fig:rsquaredfuel"></span>
<img src="bookdown-demo_files/figure-html/rsquaredfuel-1.png" alt="R-squared for Nonlinear Data" width="672" />
<p class="caption">
Figure 4.21: R-squared for Nonlinear Data
</p>
</div>
<pre><code>## 
##  Linear Regression
## 
## Correlation coefficient r =  -0.1716 
## 
## Equation of Regression Line:
## 
##   efficiency = 11.0579 + -0.0147 * speed 
## 
## Residual Standard Error: s   = 3.9047 
## R^2 (unadjusted):        R^2 = 0.0295</code></pre>
<p>Here, we get a small <span class="math inline">\(r^2\)</span> value. However, there is certainly a relationship between <strong>efficiency</strong> and <strong>speed</strong> - just not a <em>linear</em> one! It is always important that you visually examine the data before drawing conclusions based on certain statistics!</p>
</div>
</div>
</div>
<div id="cautions" class="section level2">
<h2><span class="header-section-number">4.3</span> Cautions</h2>
<div id="extrapolation" class="section level3">
<h3><span class="header-section-number">4.3.1</span> Extrapolation</h3>
<p>The regression line we found for predicting <strong>Height</strong> from <strong>RtSpan</strong> using the <code>pennstate1</code> dataset, <span class="math inline">\(\hat{y}=41.959349+1.239448x\)</span>. can be used for <em>interpolation</em>, i.e. predicting a height for a person that was not in the original dataset, but is within the range of right handspans covered by the dataset. However, it is inappropriate to use this regression line to predict a height for someone with a hand span that is outside of the range covered by the dataset.</p>
<dl>
<dt>Extrapolation</dt>
<dd><p><em>Extrapolation</em> is using a regression line to predict <span class="math inline">\(\hat{y}\)</span>-values for <span class="math inline">\(x\)</span>-values outside the range of observed <span class="math inline">\(x\)</span>-values.</p>
</dd>
</dl>
<p>Sultan Kosen holds the Guiness World Record for the tallest living male. (His right handspan measures 30.48 cm, which is considerably bigger than all of the hand-spans in our dataset.) If we extrapolate using the regression line from this dataset, then we would predict his height to be <span class="math inline">\(\hat{y}=41.959349+1.239448\cdot 30.48=79.36\)</span> inches <span class="math inline">\(\approx\)</span> 6’ 7.5“. But he was really 8’ 3”! The prediction based on extrapolation was not very accurate.</p>
</div>
<div id="influential-observations" class="section level3">
<h3><span class="header-section-number">4.3.2</span> Influential Observations</h3>
<dl>
<dt>Influential Observations</dt>
<dd><p><em>Influential observations</em> are observations which have a large effect on correlation and regression:</p>
</dd>
</dl>
<ul>
<li>They have extreme <span class="math inline">\(x\)</span>-values.</li>
<li>They inflate or deflate correlation.</li>
<li>They affect the slope of the regression line.</li>
</ul>
<p>Investigate influential observations with the following app.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">require</span>(manipulate)
<span class="kw">Points2Watch</span>()</code></pre></div>
</div>
<div id="association-versus-causation" class="section level3">
<h3><span class="header-section-number">4.3.3</span> Association versus Causation</h3>
<p>Two variables having a high positive (or high negative) correlation between two variables suggests that there is a linear association that exists between them. However, correlation does <em>not</em> imply causation. In other words, strong correlation does not imply that one variable <em>causes</em> the other.</p>
<p>Consider the variables <strong>height</strong> and <strong>fastest</strong> in the <code>m111survey</code> dataset. The scatterplot and correlation coefficient suggest that taller people tend to have driven at a higher maximum speed. See Figure[Height/Fastest Scatterplot].</p>
<div class="figure"><span id="fig:fastestheightxy"></span>
<img src="bookdown-demo_files/figure-html/fastestheightxy-1.png" alt="Height/Fastest Scatterplot" width="672" />
<p class="caption">
Figure 4.22: Height/Fastest Scatterplot
</p>
</div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(height~fastest,<span class="dt">data=</span>m111survey,<span class="dt">use=</span><span class="st">&quot;na.or.complete&quot;</span>)</code></pre></div>
<pre><code>## [1] 0.1708742</code></pre>
<p>There a positive correlation between height and top speed. However, this does not necessarily mean that being tall <em>causes</em> you to drive faster. It’s certainly not the case that tall people can’t help but have a heavy foot! There may be a confounding variable that is (at least partially) responsible for the observed association. One possible confounder is <strong>sex</strong>. See Figure[Height/Fastest by Sex]. This suggests that males tend to drive faster than females. Since males also tend to be taller than females, this helps to explain the pattern we saw in the original scatterplot.</p>
<div class="figure"><span id="fig:fastestheightxysex"></span>
<img src="bookdown-demo_files/figure-html/fastestheightxysex-1.png" alt="Height/Fastest by Sex:  Grouping shows that sex may be a confounding variable that helps to explain why taller people tend to drive faster." width="672" />
<p class="caption">
Figure 4.23: Height/Fastest by Sex: Grouping shows that sex may be a confounding variable that helps to explain why taller people tend to drive faster.
</p>
</div>
</div>
<div id="simpsons-paradox-1" class="section level3">
<h3><span class="header-section-number">4.3.4</span> Simpson’s Paradox</h3>
<p><strong>Recall</strong>: Simpson’s Paradox occurs when the direction of the relationship between two variables is one way when you look at the aggregate data, but turns out the opposite way when you break up the data into subgroups based on a third variable. <em>You saw this back in Chapter 3 with two categorical variables!</em></p>
<p>Simpson’s Paradox can arise with two numerical variables as well!</p>
<p>Let’s look at a new dataset, <code>sat</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(sat)
<span class="kw">View</span>(sat)
<span class="kw">help</span>(sat)</code></pre></div>
<p>We can describe the relationship between <strong>salary</strong> (mean annual teacher salary by state in $1000s) and <strong>sat</strong> (sum of mean Verbal and mean Math scores by state) using the correlation coefficient, scatterplot, and regression line. See Figure[SAT].</p>
<pre><code>## 
##  Linear Regression
## 
## Correlation coefficient r =  -0.4399 
## 
## Equation of Regression Line:
## 
##   sat = 1158.859 + -5.5396 * salary 
## 
## Residual Standard Error: s   = 67.8893 
## R^2 (unadjusted):        R^2 = 0.1935</code></pre>
<div class="figure"><span id="fig:satanalysis"></span>
<img src="bookdown-demo_files/figure-html/satanalysis-1.png" alt="SAT:  Association between Average Annual Teacher Salary and Average Cumulative SAT Score (by state)" width="672" />
<p class="caption">
Figure 4.24: SAT: Association between Average Annual Teacher Salary and Average Cumulative SAT Score (by state)
</p>
</div>
<p>Our regression analysis suggests that as teachers are paid higher salaries, the average SAT score drops. However, our intuition tells us that higher salaries would attract better teachers, who in turn would better prepare students for the SAT. What’s going on here?</p>
<p>Use the following app to investigate what happens when we take into account a third variable, <code>frac</code>. This is the percentage of students in the state who take the SAT.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">require</span>(manipulate)
<span class="kw">DtrellScat</span>(sat~salary|frac,<span class="dt">data=</span>sat)</code></pre></div>
<p>We can see that within most subgroups, the slope of the regression line is positive, while the regression line for the overall data has a negative slope.</p>
<p>How can we explain this paradox?</p>
<p><strong>First Observation:</strong> It turns out that states where education is considered a high priority pay their teachers higher salaries. But since education is a high priority in these states, a high proportion of students in these states want to go to college, so a high proportion of them take the SAT. Similarly, states where education isn’t such an important part of the economy or the culture tend to pay their teachers less, and they also tend to have fewer students taking the SAT. So we’ve got a <strong>positive</strong> association between <strong>frac</strong> and <strong>salary</strong>.</p>
<p>Check this out in Figure[Frac/Salary Scatterplot].</p>
<div class="figure"><span id="fig:salaryfracxy"></span>
<img src="bookdown-demo_files/figure-html/salaryfracxy-1.png" alt="Frac/Salary Scatterplot:  Percentage of students in the state that take the SAT vs. the average annual teacher salary." width="672" />
<p class="caption">
Figure 4.25: Frac/Salary Scatterplot: Percentage of students in the state that take the SAT vs. the average annual teacher salary.
</p>
</div>
<p><strong>Second Observation</strong>: When a high percentage of students in a state take the SAT, this pool of test-takers is bound to include both the very strong students and those who are not so strong, so the mean SAT score is liable to be low. On the other hand, in states where fewer students take the SAT, the students who opt to take the test are likely to be highly motivated, definitely college-bound, very studious individuals. This elite pool tends to boost the mean SAT score for the state. So we’ve got a <strong>negative</strong> association between <strong>frac</strong> and <strong>sat</strong>.</p>
<p>Again, check this out in Figure[Frac/SAT Scatterplot].</p>
<div class="figure"><span id="fig:satfracxy"></span>
<img src="bookdown-demo_files/figure-html/satfracxy-1.png" alt="Frac/SAT Scatterplot:  Percentage of students in the state that take the SAT vs. the average cumulative SAT score." width="672" />
<p class="caption">
Figure 4.26: Frac/SAT Scatterplot: Percentage of students in the state that take the SAT vs. the average cumulative SAT score.
</p>
</div>
<p>Finally, put it together: the positive association between <strong>salary</strong> and <strong>frac</strong> and the negative association between <strong>frac</strong> and <strong>sat</strong> results in the negative association between <strong>salary</strong> and <strong>sat</strong>.</p>
<p>To put it in a nontechnical nutshell: states where education is important tend to pay their teachers well, but they also “handicap” themselves by encouraging most students (including the weaker ones) to take tests like the SAT. The handicap is so pronounced that higher values of <strong>salary</strong> tend to go along with lower values of <strong>sat</strong>.</p>
</div>
</div>
<div id="curvilinear-fits" class="section level2">
<h2><span class="header-section-number">4.4</span> Curvilinear Fits</h2>
<p>Frequently we have brought up the idea that the relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> — our two numerical variables — might not be a linear one. Let’s look into this idea bit further.</p>
<p>Consider the data frame <code>henderson</code> from the <code>tigertats</code> package:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(henderson)
<span class="kw">View</span>(henderson)
<span class="kw">help</span>(henderson)</code></pre></div>
<p>Ricky Henderson, who played in the Major Leagues from 1979 to 2003, is widely considered to be one of the finest leadoff hitters in baseball history. The <code>henderson</code> data frame gives some fo his most important offensive statistics, by season. Let’s have a look at his slugging average (the average number of bases he got per at-bat) over the years (see Figure [Career Slugging]:</p>
<div class="figure"><span id="fig:hendslugplot"></span>
<img src="bookdown-demo_files/figure-html/hendslugplot-1.png" alt="Slugging for Ricky Henderson, 1979-2001" width="672" />
<p class="caption">
Figure 4.27: Slugging for Ricky Henderson, 1979-2001
</p>
</div>
<p>We have included a regression line, but as you can see the fit doesn’t look right at all: the points on the scatter plot don’t appear to follow a line. It’s not just that there is a lot of “scatter” around the regression line; instead it seems that some other pattern – not a linear one — is at work in determining how Ricky’s slugging average varied over the years.</p>
<p>One way to confirm our suspicion is to run a <em>check</em> on the linear fit, using the <code>check</code> parameter for <code>lmGC()</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">lmGC</span>(SLG~Season,<span class="dt">data=</span>henderson,<span class="dt">check=</span><span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## 
##  Linear Regression
## 
## Correlation coefficient r =  -0.2719 
## 
## Equation of Regression Line:
## 
##   SLG = 5.7685 + -0.0027 * Season 
## 
## Residual Standard Error: s   = 0.0661 
## R^2 (unadjusted):        R^2 = 0.0739</code></pre>
<p><img src="bookdown-demo_files/figure-html/hendsluglinecheck-1.png" width="672" /></p>
<p>In addition to the usual linear model information, the scatter plot contains two new features:</p>
<ul>
<li>a <em>loess</em> curve;</li>
<li>an approximate 95%-confidence band around the loess curve.</li>
</ul>
<p>The term “loess” is short for “local estimation”: a loess curve is an attempt to use only the data itself to estimate the “real” deterministic part of the relationship between the <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> variables. In particular, it doesn’t assume that the relationship is a linear one! hence it wobbles around, following the general pattern of the point son the scatter plot.</p>
<p>The confidence band is the slightly shaded area that surrounds the loess curve. A rough-and-ready way to interpret the interval is to say that we are pretty confident that the “real” relationship between <strong>Season</strong> and <strong>SLG</strong> — if it could somehow be graphed on the scatter plot – would lie somewhere within the band. The loess curve is simply our best “data-based” guess at that unknown relationship.</p>
<p>Note that the regression line wanders a bit outside of the band, and is often quite near the edge of it: this is a good indication that the “real” relationship between <strong>Season</strong> and <strong>SLG</strong> is not a linear one.</p>
<p>So we have “checked” the linear fit, and found it wanting. Let’s use our common sense to consider what the “real” relationship might be like.</p>
<p>For many professional athletes, the first couple of years in the majors leagues are tough ones, as they go up against other top-of-the-line players. But after a while they adjust —if they don’t their career stats come to an end quickly! — and a relatively long “peak” period of play ensues. Eventually, though, age and injuries catch up with the athlete, and his/her performance begins to decline.</p>
<p>Hence the relationship between season of play and some performance measure such as slugging average ought to be a curvilinear one, with a rise and then a fall.</p>
<p>Rise-and-fall curvilinear relationships can be modeled mathematically by means of quadratic equations, which have the general form:</p>
<p><span class="math display">\[y=ax^2+bx+c,\]</span></p>
<p>since these equations graph as parabolas. Let’s try to fit a second-degree curve (a parabola) to our data. This is accomplished using a new function, <code>polyfitGC()</code>. The function works like <code>lmGC()</code>, but has a new parameter <code>degree</code> to indicate the degree of the fitting curve:</p>
<ul>
<li><code>degree=2</code> fits a quadratic (a one-humped rise/fall or fall/rise parabola ) to the data;</li>
<li><code>degree=3</code> fits a cubic (as many as two “humps”“);</li>
<li><code>degree=4</code> fits a cubic (as many as three “humps”“);</li>
<li>and so on to higher degrees.</li>
</ul>
<p>Here’s the R-code for our quadratic fit:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">polyfitGC</span>(SLG~Season,<span class="dt">data=</span>henderson,
          <span class="dt">degree=</span><span class="dv">2</span>,<span class="dt">graph=</span><span class="ot">TRUE</span>)</code></pre></div>
<p>The output to the console does not give the equation of the parabola, but we do get the residual standard error and the <span class="math inline">\(R^2\)</span> value. (Note that there is no correlation: <span class="math inline">\(r\)</span> doesn’t make sense outside the context of linear fits.)</p>
<p>The graph looks promising: the parabola does appear to run through the points on the scatter plot a lot better than the line did. Also note that the <span class="math inline">\(R^2\)</span> value is a good bit higher than it was with the linear fit (0.3825 as compared to 0.0739).</p>
<p>We can check this new fit as follows:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">polyfitGC</span>(SLG~Season,<span class="dt">data=</span>henderson,
          <span class="dt">degree=</span><span class="dv">2</span>,<span class="dt">check=</span><span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## Polynomial Regression, Degree = 2
## 
## Residual Standard Error: s   = 0.0553 
## R^2 (unadjusted):        R^2 = 0.3825</code></pre>
<div class="figure"><span id="fig:hend2dcheck"></span>
<img src="bookdown-demo_files/figure-html/hend2dcheck-1.png" alt="Checking Graph for the Quadratic Fit" width="672" />
<p class="caption">
Figure 4.28: Checking Graph for the Quadratic Fit
</p>
</div>
<p>Examining Figure [Checking Graph], we see that the parabola stays well within the band at all times: our quadratic fit looks quite promising as a way to predict <span class="math inline">\(y\)</span> values from known <span class="math inline">\(x\)</span> values!</p>
<p>The the data go only up through the 2001 season, but Henderson played 72 games with the Boston Red Sox in 2002, and 30 games in 2003 for the LA Dodgers. Let’s use the parabola and the linear fit to predict his slugging averages for those two seasons.</p>
<p>First, the prediction based on the linear fit:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">linModel &lt;-<span class="st"> </span><span class="kw">lmGC</span>(SLG~Season,<span class="dt">data=</span>henderson)
<span class="kw">predict</span>(linModel,<span class="dt">x=</span><span class="dv">2002</span>)
<span class="kw">predict</span>(linModel,<span class="dt">x=</span><span class="dv">2003</span>)</code></pre></div>
<p>Now the prediction based on the quadratic fit:</p>
<pre class="reval"><code>quadModel &lt;- polyfitGC(SLG~Season,degree=2,data=henderson)
predict(quadModel,x=2002)
predict(quadModel,x=2003)</code></pre>
<p>Here are the predictions from each model, compared with Henderson’s actual statistics:</p>
<table>
<caption>Predicted/Actual Slugging Averages for R. Henderson</caption>
<thead>
<tr class="header">
<th align="center">Season</th>
<th align="center">Linear Prediction</th>
<th align="center">Quadratic Prediction</th>
<th align="center">Actual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">2002</td>
<td align="center">0.386</td>
<td align="center">0.293</td>
<td align="center">0.352</td>
</tr>
<tr class="even">
<td align="center">2003</td>
<td align="center">0.383</td>
<td align="center">0.267</td>
<td align="center">0.306</td>
</tr>
</tbody>
</table>
<p>The regression line was better for 2002, but it falls too slowly: the parabola makes the better prediction for 2003. If we had to predict how Ricky would have done had he stayed on for the 2004 season, surely we would go with the prediction provided by the quadratic fit!</p>
</div>
<div id="thoughts-on-r-3" class="section level2">
<h2><span class="header-section-number">4.5</span> Thoughts on R</h2>
<div id="new-r-functions-1" class="section level3">
<h3><span class="header-section-number">4.5.1</span> New R Functions</h3>
<p>Know how to use these functions:</p>
<ul>
<li><code>xyplot()</code><br />
</li>
<li><code>lmGC()</code></li>
<li><code>predict()</code></li>
<li><code>polyfitGC()</code></li>
</ul>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="relationships-between-two-factor-variables.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="sampling-and-surveys.html" class="navigation navigation-next " aria-label="Next page""><i class="fa fa-angle-right"></i></a>

<script src="book_assets/gitbook-2.6.7/js/app.min.js"></script>
<script src="book_assets/gitbook-2.6.7/js/lunr.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="book_assets/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/04-TwoNumeric.Rmd",
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
