<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Elementary Statistics with R</title>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
  <meta name="description" content="These are course notes for MAT 111 at Georgetown College. They are greatly in need of revision.">
  <meta name="generator" content="bookdown 0.0.71 and GitBook 2.6.7">

  <meta property="og:title" content="Elementary Statistics with R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="These are course notes for MAT 111 at Georgetown College. They are greatly in need of revision." />
  <meta name="github-repo" content="homerhanumat/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Elementary Statistics with R" />
  
  <meta name="twitter:description" content="These are course notes for MAT 111 at Georgetown College. They are greatly in need of revision." />
  

<meta name="author" content="Rebekah Robinson and Homer White">

<meta name="date" content="2016-05-18">

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="confidence-intervals.html">
<link rel="next" href="goodness-of-fit.html">

<script src="book_assets/jquery-2.2.3/jquery.min.js"></script>
<link href="book_assets/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>


  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Elementary Statistics With R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#what-are-r-and-rstudio"><i class="fa fa-check"></i><b>1.1</b> What are R and RStudio?</a><ul>
<li class="chapter" data-level="1.1.1" data-path="index.html"><a href="index.html#panels-and-tabs"><i class="fa fa-check"></i><b>1.1.1</b> Panels and Tabs</a></li>
<li class="chapter" data-level="1.1.2" data-path="index.html"><a href="index.html#differences-between-rscript-and-rmarkdown-files"><i class="fa fa-check"></i><b>1.1.2</b> Differences Between RScript and RMarkdown Files</a></li>
<li class="chapter" data-level="1.1.3" data-path="index.html"><a href="index.html#basic-r"><i class="fa fa-check"></i><b>1.1.3</b> Basic R</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#lets-play-cards"><i class="fa fa-check"></i><b>1.2</b> Let’s play cards!</a><ul>
<li class="chapter" data-level="1.2.1" data-path="index.html"><a href="index.html#the-game"><i class="fa fa-check"></i><b>1.2.1</b> The Game</a></li>
<li class="chapter" data-level="1.2.2" data-path="index.html"><a href="index.html#the-results"><i class="fa fa-check"></i><b>1.2.2</b> The Results</a></li>
<li class="chapter" data-level="1.2.3" data-path="index.html"><a href="index.html#the-conclusion"><i class="fa fa-check"></i><b>1.2.3</b> The Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#statistics"><i class="fa fa-check"></i><b>1.3</b> Statistics</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#thoughts-on-r"><i class="fa fa-check"></i><b>1.4</b> Thoughts on R</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html"><i class="fa fa-check"></i><b>2</b> Describing Patterns in Data</a><ul>
<li class="chapter" data-level="2.1" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#data-basics"><i class="fa fa-check"></i><b>2.1</b> Data Basics</a><ul>
<li class="chapter" data-level="2.1.1" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#getting-data-in-r"><i class="fa fa-check"></i><b>2.1.1</b> Getting Data in R</a></li>
<li class="chapter" data-level="2.1.2" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#variable-types"><i class="fa fa-check"></i><b>2.1.2</b> Variable Types</a></li>
<li class="chapter" data-level="2.1.3" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#descriptive-statistics"><i class="fa fa-check"></i><b>2.1.3</b> Descriptive Statistics</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#outline"><i class="fa fa-check"></i><b>2.2</b> Outline</a></li>
<li class="chapter" data-level="2.3" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#one-factor-variable"><i class="fa fa-check"></i><b>2.3</b> One Factor Variable</a><ul>
<li class="chapter" data-level="2.3.1" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#tables"><i class="fa fa-check"></i><b>2.3.1</b> Tables</a></li>
<li class="chapter" data-level="2.3.2" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#barcharts."><i class="fa fa-check"></i><b>2.3.2</b> Barcharts.</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#two-factor-variables"><i class="fa fa-check"></i><b>2.4</b> Two Factor Variables</a><ul>
<li class="chapter" data-level="2.4.1" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#two-way-tables"><i class="fa fa-check"></i><b>2.4.1</b> Two-Way Tables</a></li>
<li class="chapter" data-level="2.4.2" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#barcharts-again"><i class="fa fa-check"></i><b>2.4.2</b> Barcharts Again</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#one-numerical-variable"><i class="fa fa-check"></i><b>2.5</b> One Numerical Variable</a><ul>
<li class="chapter" data-level="2.5.1" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#numerical-measures"><i class="fa fa-check"></i><b>2.5.1</b> Numerical Measures</a></li>
<li class="chapter" data-level="2.5.2" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#graphical-tools"><i class="fa fa-check"></i><b>2.5.2</b> Graphical Tools</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#factor-and-numerical-variable"><i class="fa fa-check"></i><b>2.6</b> Factor and Numerical Variable</a><ul>
<li class="chapter" data-level="2.6.1" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#numerical-tools"><i class="fa fa-check"></i><b>2.6.1</b> Numerical Tools</a></li>
<li class="chapter" data-level="2.6.2" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#graphical-tools-1"><i class="fa fa-check"></i><b>2.6.2</b> Graphical Tools</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#choice-of-measures"><i class="fa fa-check"></i><b>2.7</b> Choice of Measures</a><ul>
<li class="chapter" data-level="2.7.1" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#mean-median-and-skewness"><i class="fa fa-check"></i><b>2.7.1</b> Mean, Median and Skewness</a></li>
<li class="chapter" data-level="2.7.2" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#mean-median-and-outliers"><i class="fa fa-check"></i><b>2.7.2</b> Mean, Median and Outliers</a></li>
<li class="chapter" data-level="2.7.3" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#meansd-vs.medianiqr"><i class="fa fa-check"></i><b>2.7.3</b> Mean/SD vs. Median/IQR</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#bell-shaped-distributions"><i class="fa fa-check"></i><b>2.8</b> Bell-Shaped Distributions</a><ul>
<li class="chapter" data-level="2.8.1" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#the-68-95-rule"><i class="fa fa-check"></i><b>2.8.1</b> The 68-95 Rule</a></li>
<li class="chapter" data-level="2.8.2" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#z-scores"><i class="fa fa-check"></i><b>2.8.2</b> <span class="math inline">\(z\)</span>-scores</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#reading-in-statistics"><i class="fa fa-check"></i><b>2.9</b> Reading in Statistics</a></li>
<li class="chapter" data-level="2.10" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#thoughts-on-r-1"><i class="fa fa-check"></i><b>2.10</b> Thoughts on R</a><ul>
<li class="chapter" data-level="2.10.1" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#new-r-functions"><i class="fa fa-check"></i><b>2.10.1</b> New R Functions</a></li>
<li class="chapter" data-level="2.10.2" data-path="describing-patterns-in-data.html"><a href="describing-patterns-in-data.html#those-pesky-formulas"><i class="fa fa-check"></i><b>2.10.2</b> Those Pesky Formulas!</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="relationships-between-two-factor-variables.html"><a href="relationships-between-two-factor-variables.html"><i class="fa fa-check"></i><b>3</b> Relationships Between Two Factor Variables</a><ul>
<li class="chapter" data-level="3.1" data-path="relationships-between-two-factor-variables.html"><a href="relationships-between-two-factor-variables.html#introduction-1"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="relationships-between-two-factor-variables.html"><a href="relationships-between-two-factor-variables.html#the-descriptive-aspect"><i class="fa fa-check"></i><b>3.2</b> The Descriptive Aspect</a><ul>
<li class="chapter" data-level="3.2.1" data-path="relationships-between-two-factor-variables.html"><a href="relationships-between-two-factor-variables.html#terminology-for-two-way-tables"><i class="fa fa-check"></i><b>3.2.1</b> Terminology for Two-Way Tables</a></li>
<li class="chapter" data-level="3.2.2" data-path="relationships-between-two-factor-variables.html"><a href="relationships-between-two-factor-variables.html#detecting-and-describing-relationships"><i class="fa fa-check"></i><b>3.2.2</b> Detecting and Describing Relationships</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="relationships-between-two-factor-variables.html"><a href="relationships-between-two-factor-variables.html#the-idea-of-inference"><i class="fa fa-check"></i><b>3.3</b> The Idea of Inference</a></li>
<li class="chapter" data-level="3.4" data-path="relationships-between-two-factor-variables.html"><a href="relationships-between-two-factor-variables.html#tests-of-significance"><i class="fa fa-check"></i><b>3.4</b> Tests of Significance</a><ul>
<li class="chapter" data-level="3.4.1" data-path="relationships-between-two-factor-variables.html"><a href="relationships-between-two-factor-variables.html#five-step-procedure"><i class="fa fa-check"></i><b>3.4.1</b> Five Step Procedure</a></li>
<li class="chapter" data-level="3.4.2" data-path="relationships-between-two-factor-variables.html"><a href="relationships-between-two-factor-variables.html#more-on-the-chi-square-statistic"><i class="fa fa-check"></i><b>3.4.2</b> More on the Chi-Square Statistic</a></li>
<li class="chapter" data-level="3.4.3" data-path="relationships-between-two-factor-variables.html"><a href="relationships-between-two-factor-variables.html#chisqtestgc"><i class="fa fa-check"></i><b>3.4.3</b> <code>chisqtestGC()</code></a></li>
<li class="chapter" data-level="3.4.4" data-path="relationships-between-two-factor-variables.html"><a href="relationships-between-two-factor-variables.html#working-with-summary-data"><i class="fa fa-check"></i><b>3.4.4</b> Working With Summary Data</a></li>
<li class="chapter" data-level="3.4.5" data-path="relationships-between-two-factor-variables.html"><a href="relationships-between-two-factor-variables.html#simulating-p-values"><i class="fa fa-check"></i><b>3.4.5</b> Simulating P-Values</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="relationships-between-two-factor-variables.html"><a href="relationships-between-two-factor-variables.html#simpsons-paradox"><i class="fa fa-check"></i><b>3.5</b> Simpson’s Paradox</a></li>
<li class="chapter" data-level="3.6" data-path="relationships-between-two-factor-variables.html"><a href="relationships-between-two-factor-variables.html#thoughts-on-r-2"><i class="fa fa-check"></i><b>3.6</b> Thoughts on R</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="relationships-between-two-numerical-variables.html"><a href="relationships-between-two-numerical-variables.html"><i class="fa fa-check"></i><b>4</b> Relationships Between Two Numerical Variables</a><ul>
<li class="chapter" data-level="4.1" data-path="relationships-between-two-numerical-variables.html"><a href="relationships-between-two-numerical-variables.html#outline-1"><i class="fa fa-check"></i><b>4.1</b> Outline</a></li>
<li class="chapter" data-level="4.2" data-path="relationships-between-two-numerical-variables.html"><a href="relationships-between-two-numerical-variables.html#statistical-relationships"><i class="fa fa-check"></i><b>4.2</b> Statistical Relationships</a><ul>
<li class="chapter" data-level="4.2.1" data-path="relationships-between-two-numerical-variables.html"><a href="relationships-between-two-numerical-variables.html#scatterplots"><i class="fa fa-check"></i><b>4.2.1</b> Scatterplots</a></li>
<li class="chapter" data-level="4.2.2" data-path="relationships-between-two-numerical-variables.html"><a href="relationships-between-two-numerical-variables.html#correlation"><i class="fa fa-check"></i><b>4.2.2</b> Correlation</a></li>
<li class="chapter" data-level="4.2.3" data-path="relationships-between-two-numerical-variables.html"><a href="relationships-between-two-numerical-variables.html#regression-equation"><i class="fa fa-check"></i><b>4.2.3</b> Regression Equation</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="relationships-between-two-numerical-variables.html"><a href="relationships-between-two-numerical-variables.html#cautions"><i class="fa fa-check"></i><b>4.3</b> Cautions</a><ul>
<li class="chapter" data-level="4.3.1" data-path="relationships-between-two-numerical-variables.html"><a href="relationships-between-two-numerical-variables.html#extrapolation"><i class="fa fa-check"></i><b>4.3.1</b> Extrapolation</a></li>
<li class="chapter" data-level="4.3.2" data-path="relationships-between-two-numerical-variables.html"><a href="relationships-between-two-numerical-variables.html#influential-observations"><i class="fa fa-check"></i><b>4.3.2</b> Influential Observations</a></li>
<li class="chapter" data-level="4.3.3" data-path="relationships-between-two-numerical-variables.html"><a href="relationships-between-two-numerical-variables.html#association-versus-causation"><i class="fa fa-check"></i><b>4.3.3</b> Association versus Causation</a></li>
<li class="chapter" data-level="4.3.4" data-path="relationships-between-two-numerical-variables.html"><a href="relationships-between-two-numerical-variables.html#simpsons-paradox-1"><i class="fa fa-check"></i><b>4.3.4</b> Simpson’s Paradox</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="relationships-between-two-numerical-variables.html"><a href="relationships-between-two-numerical-variables.html#curvilinear-fits"><i class="fa fa-check"></i><b>4.4</b> Curvilinear Fits</a></li>
<li class="chapter" data-level="4.5" data-path="relationships-between-two-numerical-variables.html"><a href="relationships-between-two-numerical-variables.html#thoughts-on-r-3"><i class="fa fa-check"></i><b>4.5</b> Thoughts on R</a><ul>
<li class="chapter" data-level="4.5.1" data-path="relationships-between-two-numerical-variables.html"><a href="relationships-between-two-numerical-variables.html#new-r-functions-1"><i class="fa fa-check"></i><b>4.5.1</b> New R Functions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="sampling-and-surveys.html"><a href="sampling-and-surveys.html"><i class="fa fa-check"></i><b>5</b> Sampling and Surveys</a><ul>
<li class="chapter" data-level="5.1" data-path="sampling-and-surveys.html"><a href="sampling-and-surveys.html#introduction-2"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="sampling-and-surveys.html"><a href="sampling-and-surveys.html#population-versus-sample"><i class="fa fa-check"></i><b>5.2</b> Population versus Sample</a></li>
<li class="chapter" data-level="5.3" data-path="sampling-and-surveys.html"><a href="sampling-and-surveys.html#types-of-samples"><i class="fa fa-check"></i><b>5.3</b> Types of Samples</a><ul>
<li class="chapter" data-level="5.3.1" data-path="sampling-and-surveys.html"><a href="sampling-and-surveys.html#random-sampling"><i class="fa fa-check"></i><b>5.3.1</b> Random Sampling</a></li>
<li class="chapter" data-level="5.3.2" data-path="sampling-and-surveys.html"><a href="sampling-and-surveys.html#comparison-of-sampling-methods"><i class="fa fa-check"></i><b>5.3.2</b> Comparison of Sampling Methods</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="sampling-and-surveys.html"><a href="sampling-and-surveys.html#bias-in-surveys"><i class="fa fa-check"></i><b>5.4</b> Bias in Surveys</a><ul>
<li class="chapter" data-level="5.4.1" data-path="sampling-and-surveys.html"><a href="sampling-and-surveys.html#selection-bias"><i class="fa fa-check"></i><b>5.4.1</b> Selection Bias</a></li>
<li class="chapter" data-level="5.4.2" data-path="sampling-and-surveys.html"><a href="sampling-and-surveys.html#nonresopnse-bias"><i class="fa fa-check"></i><b>5.4.2</b> Nonresopnse Bias</a></li>
<li class="chapter" data-level="5.4.3" data-path="sampling-and-surveys.html"><a href="sampling-and-surveys.html#response-bias"><i class="fa fa-check"></i><b>5.4.3</b> Response Bias</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="sampling-and-surveys.html"><a href="sampling-and-surveys.html#thoughts-on-r-4"><i class="fa fa-check"></i><b>5.5</b> Thoughts on R</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="design-of-studies.html"><a href="design-of-studies.html"><i class="fa fa-check"></i><b>6</b> Design of Studies</a><ul>
<li class="chapter" data-level="6.1" data-path="design-of-studies.html"><a href="design-of-studies.html#observational-studies-and-experiments"><i class="fa fa-check"></i><b>6.1</b> Observational Studies and Experiments</a></li>
<li class="chapter" data-level="6.2" data-path="design-of-studies.html"><a href="design-of-studies.html#why-perform-experiments"><i class="fa fa-check"></i><b>6.2</b> Why Perform Experiments?</a></li>
<li class="chapter" data-level="6.3" data-path="design-of-studies.html"><a href="design-of-studies.html#experimental-designs"><i class="fa fa-check"></i><b>6.3</b> Experimental Designs</a><ul>
<li class="chapter" data-level="6.3.1" data-path="design-of-studies.html"><a href="design-of-studies.html#completely-randomized-designs"><i class="fa fa-check"></i><b>6.3.1</b> Completely Randomized Designs</a></li>
<li class="chapter" data-level="6.3.2" data-path="design-of-studies.html"><a href="design-of-studies.html#randomized-block-designs"><i class="fa fa-check"></i><b>6.3.2</b> Randomized Block Designs</a></li>
<li class="chapter" data-level="6.3.3" data-path="design-of-studies.html"><a href="design-of-studies.html#matched-pair-designs"><i class="fa fa-check"></i><b>6.3.3</b> Matched Pair Designs</a></li>
<li class="chapter" data-level="6.3.4" data-path="design-of-studies.html"><a href="design-of-studies.html#repeated-measure-designs"><i class="fa fa-check"></i><b>6.3.4</b> Repeated-Measure Designs</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="design-of-studies.html"><a href="design-of-studies.html#considerations-about-experiments"><i class="fa fa-check"></i><b>6.4</b> Considerations About Experiments</a><ul>
<li class="chapter" data-level="6.4.1" data-path="design-of-studies.html"><a href="design-of-studies.html#reproducibility"><i class="fa fa-check"></i><b>6.4.1</b> Reproducibility</a></li>
<li class="chapter" data-level="6.4.2" data-path="design-of-studies.html"><a href="design-of-studies.html#subjects-and-the-population"><i class="fa fa-check"></i><b>6.4.2</b> Subjects and the Population</a></li>
<li class="chapter" data-level="6.4.3" data-path="design-of-studies.html"><a href="design-of-studies.html#statistical-significance"><i class="fa fa-check"></i><b>6.4.3</b> Statistical Significance</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="design-of-studies.html"><a href="design-of-studies.html#terminology-for-experiments"><i class="fa fa-check"></i><b>6.5</b> Terminology for Experiments</a></li>
<li class="chapter" data-level="6.6" data-path="design-of-studies.html"><a href="design-of-studies.html#thoughts-on-r-5"><i class="fa fa-check"></i><b>6.6</b> Thoughts on R</a><ul>
<li class="chapter" data-level="6.6.1" data-path="design-of-studies.html"><a href="design-of-studies.html#new-r-functions-2"><i class="fa fa-check"></i><b>6.6.1</b> New R-functions</a></li>
<li class="chapter" data-level="6.6.2" data-path="design-of-studies.html"><a href="design-of-studies.html#book-chapter-notation"><i class="fa fa-check"></i><b>6.6.2</b> “Book-Chapter” Notation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="basic-probability.html"><a href="basic-probability.html"><i class="fa fa-check"></i><b>7</b> Basic Probability</a><ul>
<li class="chapter" data-level="7.1" data-path="basic-probability.html"><a href="basic-probability.html#introduction-3"><i class="fa fa-check"></i><b>7.1</b> Introduction</a></li>
<li class="chapter" data-level="7.2" data-path="basic-probability.html"><a href="basic-probability.html#probability"><i class="fa fa-check"></i><b>7.2</b> Probability</a><ul>
<li class="chapter" data-level="7.2.1" data-path="basic-probability.html"><a href="basic-probability.html#subjective-probability"><i class="fa fa-check"></i><b>7.2.1</b> Subjective Probability</a></li>
<li class="chapter" data-level="7.2.2" data-path="basic-probability.html"><a href="basic-probability.html#theoretical-probability"><i class="fa fa-check"></i><b>7.2.2</b> Theoretical Probability</a></li>
<li class="chapter" data-level="7.2.3" data-path="basic-probability.html"><a href="basic-probability.html#long-run-frequency-probability"><i class="fa fa-check"></i><b>7.2.3</b> Long-run Frequency Probability</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="basic-probability.html"><a href="basic-probability.html#what-is-a-random-variable"><i class="fa fa-check"></i><b>7.3</b> What is a Random Variable?</a><ul>
<li class="chapter" data-level="7.3.1" data-path="basic-probability.html"><a href="basic-probability.html#notation"><i class="fa fa-check"></i><b>7.3.1</b> Notation</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="basic-probability.html"><a href="basic-probability.html#discrete-random-variables"><i class="fa fa-check"></i><b>7.4</b> Discrete Random Variables</a><ul>
<li class="chapter" data-level="7.4.1" data-path="basic-probability.html"><a href="basic-probability.html#probability-distribution-functions-for-discrete-random-variables"><i class="fa fa-check"></i><b>7.4.1</b> Probability Distribution Functions for Discrete Random Variables</a></li>
<li class="chapter" data-level="7.4.2" data-path="basic-probability.html"><a href="basic-probability.html#expectation-of-discrete-random-variables"><i class="fa fa-check"></i><b>7.4.2</b> Expectation of Discrete Random Variables</a></li>
<li class="chapter" data-level="7.4.3" data-path="basic-probability.html"><a href="basic-probability.html#standard-deviation-of-discrete-random-variables"><i class="fa fa-check"></i><b>7.4.3</b> Standard Deviation of Discrete Random Variables</a></li>
<li class="chapter" data-level="7.4.4" data-path="basic-probability.html"><a href="basic-probability.html#using-ev-and-sd-to-evaluate-a-game"><i class="fa fa-check"></i><b>7.4.4</b> Using EV and SD to Evaluate a Game</a></li>
<li class="chapter" data-level="7.4.5" data-path="basic-probability.html"><a href="basic-probability.html#independence"><i class="fa fa-check"></i><b>7.4.5</b> Independence</a></li>
<li class="chapter" data-level="7.4.6" data-path="basic-probability.html"><a href="basic-probability.html#a-special-discrete-random-variable-binomial-random-variable"><i class="fa fa-check"></i><b>7.4.6</b> A Special Discrete Random Variable: Binomial Random Variable</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="basic-probability.html"><a href="basic-probability.html#continuous-random-variables"><i class="fa fa-check"></i><b>7.5</b> Continuous Random Variables</a><ul>
<li class="chapter" data-level="7.5.1" data-path="basic-probability.html"><a href="basic-probability.html#probability-density-functions-for-continuous-random-variables"><i class="fa fa-check"></i><b>7.5.1</b> Probability Density Functions for Continuous Random Variables</a></li>
<li class="chapter" data-level="7.5.2" data-path="basic-probability.html"><a href="basic-probability.html#a-special-continuous-random-variable-normal-random-variable"><i class="fa fa-check"></i><b>7.5.2</b> A Special Continuous Random Variable: Normal Random Variable</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="basic-probability.html"><a href="basic-probability.html#approximating-binomial-probabilities"><i class="fa fa-check"></i><b>7.6</b> Approximating Binomial Probabilities</a></li>
<li class="chapter" data-level="7.7" data-path="basic-probability.html"><a href="basic-probability.html#thoughts-on-r-6"><i class="fa fa-check"></i><b>7.7</b> Thoughts on R</a><ul>
<li class="chapter" data-level="7.7.1" data-path="basic-probability.html"><a href="basic-probability.html#new-r-functions-3"><i class="fa fa-check"></i><b>7.7.1</b> New R Functions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html"><i class="fa fa-check"></i><b>8</b> Probability in Sampling</a><ul>
<li class="chapter" data-level="8.1" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#the-population-and-the-sample"><i class="fa fa-check"></i><b>8.1</b> The Population and the Sample</a><ul>
<li class="chapter" data-level="8.1.1" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#parameters"><i class="fa fa-check"></i><b>8.1.1</b> Parameters</a></li>
<li class="chapter" data-level="8.1.2" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#statistics-1"><i class="fa fa-check"></i><b>8.1.2</b> Statistics</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#from-questions-to-parameters"><i class="fa fa-check"></i><b>8.2</b> From Questions to Parameters</a><ul>
<li class="chapter" data-level="8.2.1" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#one-mean"><i class="fa fa-check"></i><b>8.2.1</b> One Mean</a></li>
<li class="chapter" data-level="8.2.2" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#one-proportion"><i class="fa fa-check"></i><b>8.2.2</b> One Proportion</a></li>
<li class="chapter" data-level="8.2.3" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#difference-of-two-means"><i class="fa fa-check"></i><b>8.2.3</b> Difference of Two Means</a></li>
<li class="chapter" data-level="8.2.4" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#difference-of-two-proportions"><i class="fa fa-check"></i><b>8.2.4</b> Difference of Two Proportions</a></li>
<li class="chapter" data-level="8.2.5" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#mean-of-differences"><i class="fa fa-check"></i><b>8.2.5</b> Mean of Differences</a></li>
<li class="chapter" data-level="8.2.6" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#the-basic-five-parameters"><i class="fa fa-check"></i><b>8.2.6</b> The “Basic Five” Parameters</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#parameters-in-experiments"><i class="fa fa-check"></i><b>8.3</b> Parameters in Experiments</a><ul>
<li class="chapter" data-level="8.3.1" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#anchoring-in-m111survey"><i class="fa fa-check"></i><b>8.3.1</b> Anchoring in m111survey</a></li>
<li class="chapter" data-level="8.3.2" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#knife-or-gun-again"><i class="fa fa-check"></i><b>8.3.2</b> Knife or Gun (Again)</a></li>
<li class="chapter" data-level="8.3.3" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#more-anchoring"><i class="fa fa-check"></i><b>8.3.3</b> More Anchoring</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#ev-and-sd-of-estimators"><i class="fa fa-check"></i><b>8.4</b> EV and SD of Estimators</a><ul>
<li class="chapter" data-level="8.4.1" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#estimating-one-mean"><i class="fa fa-check"></i><b>8.4.1</b> Estimating One Mean</a></li>
<li class="chapter" data-level="8.4.2" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#estimating-the-difference-of-two-means"><i class="fa fa-check"></i><b>8.4.2</b> Estimating the Difference of Two Means</a></li>
<li class="chapter" data-level="8.4.3" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#estimating-one-proportion"><i class="fa fa-check"></i><b>8.4.3</b> Estimating One Proportion</a></li>
<li class="chapter" data-level="8.4.4" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#estimating-the-difference-of-two-proportions"><i class="fa fa-check"></i><b>8.4.4</b> Estimating the Difference of Two Proportions</a></li>
<li class="chapter" data-level="8.4.5" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#estimating-the-mean-of-differences"><i class="fa fa-check"></i><b>8.4.5</b> Estimating the Mean of Differences</a></li>
<li class="chapter" data-level="8.4.6" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#properties-of-ev-and-sd-of-estimators"><i class="fa fa-check"></i><b>8.4.6</b> Properties of EV and SD of Estimators</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#estimators-shape-of-the-distribution"><i class="fa fa-check"></i><b>8.5</b> Estimators: Shape of the Distribution</a></li>
<li class="chapter" data-level="8.6" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#probability-for-estimators"><i class="fa fa-check"></i><b>8.6</b> Probability for Estimators</a></li>
<li class="chapter" data-level="8.7" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#inference-with-estimators"><i class="fa fa-check"></i><b>8.7</b> Inference With Estimators</a><ul>
<li class="chapter" data-level="8.7.1" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#we-are-not-deities"><i class="fa fa-check"></i><b>8.7.1</b> We Are Not Deities</a></li>
<li class="chapter" data-level="8.7.2" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#practice-with-estimator-and-se"><i class="fa fa-check"></i><b>8.7.2</b> Practice With Estimator and SE</a></li>
<li class="chapter" data-level="8.7.3" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#the-68-95-rule-for-estimation"><i class="fa fa-check"></i><b>8.7.3</b> The 68-95 Rule for Estimation</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#summary-of-formulas"><i class="fa fa-check"></i><b>8.8</b> Summary of Formulas</a></li>
<li class="chapter" data-level="8.9" data-path="probability-in-sampling.html"><a href="probability-in-sampling.html#thoughts-on-r-7"><i class="fa fa-check"></i><b>8.9</b> Thoughts on R</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="confidence-intervals.html"><a href="confidence-intervals.html"><i class="fa fa-check"></i><b>9</b> Confidence Intervals</a><ul>
<li class="chapter" data-level="9.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#introduction-4"><i class="fa fa-check"></i><b>9.1</b> Introduction</a></li>
<li class="chapter" data-level="9.2" data-path="confidence-intervals.html"><a href="confidence-intervals.html#chapter-outline"><i class="fa fa-check"></i><b>9.2</b> Chapter Outline</a></li>
<li class="chapter" data-level="9.3" data-path="confidence-intervals.html"><a href="confidence-intervals.html#one-population-mean-mu"><i class="fa fa-check"></i><b>9.3</b> One Population Mean <span class="math inline">\(\mu\)</span></a><ul>
<li class="chapter" data-level="9.3.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#the-four-steps"><i class="fa fa-check"></i><b>9.3.1</b> The Four Steps</a></li>
<li class="chapter" data-level="9.3.2" data-path="confidence-intervals.html"><a href="confidence-intervals.html#under-the-hood"><i class="fa fa-check"></i><b>9.3.2</b> Under the Hood</a></li>
<li class="chapter" data-level="9.3.3" data-path="confidence-intervals.html"><a href="confidence-intervals.html#additional-example-and-further-ideas"><i class="fa fa-check"></i><b>9.3.3</b> Additional Example, and Further Ideas</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="confidence-intervals.html"><a href="confidence-intervals.html#difference-of-two-population-means-mu_1-mu_2"><i class="fa fa-check"></i><b>9.4</b> Difference of Two Population Means, <span class="math inline">\(\mu_1-\mu_2\)</span></a><ul>
<li class="chapter" data-level="9.4.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#the-four-steps-1"><i class="fa fa-check"></i><b>9.4.1</b> The Four Steps</a></li>
<li class="chapter" data-level="9.4.2" data-path="confidence-intervals.html"><a href="confidence-intervals.html#under-the-hood-1"><i class="fa fa-check"></i><b>9.4.2</b> Under the Hood</a></li>
<li class="chapter" data-level="9.4.3" data-path="confidence-intervals.html"><a href="confidence-intervals.html#additional-example"><i class="fa fa-check"></i><b>9.4.3</b> Additional Example</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="confidence-intervals.html"><a href="confidence-intervals.html#mean-of-differences-mu_d"><i class="fa fa-check"></i><b>9.5</b> Mean of Differences, <span class="math inline">\(\mu_d\)</span></a><ul>
<li class="chapter" data-level="9.5.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#the-four-steps-2"><i class="fa fa-check"></i><b>9.5.1</b> The Four Steps</a></li>
<li class="chapter" data-level="9.5.2" data-path="confidence-intervals.html"><a href="confidence-intervals.html#under-the-hood-2"><i class="fa fa-check"></i><b>9.5.2</b> Under the Hood</a></li>
<li class="chapter" data-level="9.5.3" data-path="confidence-intervals.html"><a href="confidence-intervals.html#additional-example-1"><i class="fa fa-check"></i><b>9.5.3</b> Additional Example</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="confidence-intervals.html"><a href="confidence-intervals.html#one-population-proportion-p"><i class="fa fa-check"></i><b>9.6</b> One Population Proportion, <span class="math inline">\(p\)</span></a><ul>
<li class="chapter" data-level="9.6.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#the-four-steps-3"><i class="fa fa-check"></i><b>9.6.1</b> The Four Steps</a></li>
<li class="chapter" data-level="9.6.2" data-path="confidence-intervals.html"><a href="confidence-intervals.html#under-the-hood-3"><i class="fa fa-check"></i><b>9.6.2</b> Under the Hood</a></li>
<li class="chapter" data-level="9.6.3" data-path="confidence-intervals.html"><a href="confidence-intervals.html#additional-example-2"><i class="fa fa-check"></i><b>9.6.3</b> Additional Example</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="confidence-intervals.html"><a href="confidence-intervals.html#difference-of-two-population-proportions-p_1-p_2"><i class="fa fa-check"></i><b>9.7</b> Difference of Two Population Proportions, <span class="math inline">\(p_1-p_2\)</span></a><ul>
<li class="chapter" data-level="9.7.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#the-four-steps-4"><i class="fa fa-check"></i><b>9.7.1</b> The Four Steps</a></li>
<li class="chapter" data-level="9.7.2" data-path="confidence-intervals.html"><a href="confidence-intervals.html#under-the-hood-4"><i class="fa fa-check"></i><b>9.7.2</b> Under the Hood</a></li>
<li class="chapter" data-level="9.7.3" data-path="confidence-intervals.html"><a href="confidence-intervals.html#additional-example-3"><i class="fa fa-check"></i><b>9.7.3</b> Additional Example</a></li>
</ul></li>
<li class="chapter" data-level="9.8" data-path="confidence-intervals.html"><a href="confidence-intervals.html#thoughts-on-r-8"><i class="fa fa-check"></i><b>9.8</b> Thoughts on R</a><ul>
<li class="chapter" data-level="9.8.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#new-r-functions-4"><i class="fa fa-check"></i><b>9.8.1</b> New R Functions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html"><i class="fa fa-check"></i><b>10</b> Tests of Significance</a><ul>
<li class="chapter" data-level="10.1" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#introduction-5"><i class="fa fa-check"></i><b>10.1</b> Introduction</a></li>
<li class="chapter" data-level="10.2" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#one-population-mean-mu-1"><i class="fa fa-check"></i><b>10.2</b> One Population Mean <span class="math inline">\(\mu\)</span></a><ul>
<li class="chapter" data-level="10.2.1" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#introductory-research-question"><i class="fa fa-check"></i><b>10.2.1</b> Introductory Research Question</a></li>
<li class="chapter" data-level="10.2.2" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#the-five-steps"><i class="fa fa-check"></i><b>10.2.2</b> The Five Steps</a></li>
<li class="chapter" data-level="10.2.3" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#under-the-hood-and-further-ideas"><i class="fa fa-check"></i><b>10.2.3</b> Under the Hood, and Further Ideas</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#difference-of-two-population-means-mu_1-mu_2-1"><i class="fa fa-check"></i><b>10.3</b> Difference of Two Population Means, <span class="math inline">\(\mu_1-\mu_2\)</span></a><ul>
<li class="chapter" data-level="10.3.1" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#the-difference-of-two-means"><i class="fa fa-check"></i><b>10.3.1</b> The Difference of Two Means</a></li>
<li class="chapter" data-level="10.3.2" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#the-five-steps-1"><i class="fa fa-check"></i><b>10.3.2</b> The Five Steps</a></li>
<li class="chapter" data-level="10.3.3" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#under-the-hood-5"><i class="fa fa-check"></i><b>10.3.3</b> Under the Hood</a></li>
<li class="chapter" data-level="10.3.4" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#additional-examples"><i class="fa fa-check"></i><b>10.3.4</b> Additional Examples</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#mean-of-differences-mu_d-1"><i class="fa fa-check"></i><b>10.4</b> Mean of Differences <span class="math inline">\(\mu_d\)</span></a><ul>
<li class="chapter" data-level="10.4.1" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#introductory-research-question-1"><i class="fa fa-check"></i><b>10.4.1</b> Introductory Research Question</a></li>
<li class="chapter" data-level="10.4.2" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#the-five-steps-2"><i class="fa fa-check"></i><b>10.4.2</b> The Five Steps</a></li>
<li class="chapter" data-level="10.4.3" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#under-the-hood-6"><i class="fa fa-check"></i><b>10.4.3</b> Under the Hood</a></li>
<li class="chapter" data-level="10.4.4" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#additional-examples-1"><i class="fa fa-check"></i><b>10.4.4</b> Additional Examples</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#one-population-proportion-p-1"><i class="fa fa-check"></i><b>10.5</b> One Population Proportion <span class="math inline">\(p\)</span></a><ul>
<li class="chapter" data-level="10.5.1" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#the-five-steps-3"><i class="fa fa-check"></i><b>10.5.1</b> The Five Steps</a></li>
<li class="chapter" data-level="10.5.2" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#under-the-hood-7"><i class="fa fa-check"></i><b>10.5.2</b> Under the Hood</a></li>
<li class="chapter" data-level="10.5.3" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#additional-examples-2"><i class="fa fa-check"></i><b>10.5.3</b> Additional Examples</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#difference-of-two-proportions-p_1-p_2"><i class="fa fa-check"></i><b>10.6</b> Difference of Two Proportions <span class="math inline">\(p_1-p_2\)</span></a><ul>
<li class="chapter" data-level="10.6.1" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#the-five-steps-4"><i class="fa fa-check"></i><b>10.6.1</b> The Five Steps</a></li>
<li class="chapter" data-level="10.6.2" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#working-with-summary-data-1"><i class="fa fa-check"></i><b>10.6.2</b> Working With Summary Data</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#further-considerations-about-significance-tests"><i class="fa fa-check"></i><b>10.7</b> Further Considerations About Significance Tests</a><ul>
<li class="chapter" data-level="10.7.1" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#types-of-error"><i class="fa fa-check"></i><b>10.7.1</b> Types of Error</a></li>
<li class="chapter" data-level="10.7.2" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#the-dangers-of-limited-reporting"><i class="fa fa-check"></i><b>10.7.2</b> The Dangers of Limited Reporting</a></li>
<li class="chapter" data-level="10.7.3" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#the-dangers-of-data-snooping"><i class="fa fa-check"></i><b>10.7.3</b> The Dangers of Data-Snooping</a></li>
</ul></li>
<li class="chapter" data-level="10.8" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#thoughts-about-r"><i class="fa fa-check"></i><b>10.8</b> Thoughts About R</a><ul>
<li class="chapter" data-level="10.8.1" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#new-code-to-learn"><i class="fa fa-check"></i><b>10.8.1</b> New Code to Learn?</a></li>
<li class="chapter" data-level="10.8.2" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#old-descriptive-friends"><i class="fa fa-check"></i><b>10.8.2</b> Old Descriptive Friends</a></li>
<li class="chapter" data-level="10.8.3" data-path="tests-of-significance-1.html"><a href="tests-of-significance-1.html#adding-a-variable-to-a-data-frame"><i class="fa fa-check"></i><b>10.8.3</b> Adding a Variable to a Data Frame</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="goodness-of-fit.html"><a href="goodness-of-fit.html"><i class="fa fa-check"></i><b>11</b> Goodness of Fit</a><ul>
<li class="chapter" data-level="11.1" data-path="goodness-of-fit.html"><a href="goodness-of-fit.html#the-gamblers-die"><i class="fa fa-check"></i><b>11.1</b> The Gambler’s Die</a></li>
<li class="chapter" data-level="11.2" data-path="goodness-of-fit.html"><a href="goodness-of-fit.html#chisqtestgc-for-goodness-of-fit"><i class="fa fa-check"></i><b>11.2</b> chisqtestGC() for Goodness of Fit</a><ul>
<li class="chapter" data-level="11.2.1" data-path="goodness-of-fit.html"><a href="goodness-of-fit.html#the-gamblers-die-as-a-test-of-significance"><i class="fa fa-check"></i><b>11.2.1</b> The Gambler’s Die as a Test of Significance</a></li>
<li class="chapter" data-level="11.2.2" data-path="goodness-of-fit.html"><a href="goodness-of-fit.html#facts-about-chi2-goodness-of-fit"><i class="fa fa-check"></i><b>11.2.2</b> Facts About <span class="math inline">\(\chi^2\)</span> Goodness of Fit</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="goodness-of-fit.html"><a href="goodness-of-fit.html#further-example-seating-preference"><i class="fa fa-check"></i><b>11.3</b> Further Example: Seating Preference</a></li>
<li class="chapter" data-level="11.4" data-path="goodness-of-fit.html"><a href="goodness-of-fit.html#further-example-nexus-attendance"><i class="fa fa-check"></i><b>11.4</b> Further Example: Nexus Attendance</a></li>
<li class="chapter" data-level="11.5" data-path="goodness-of-fit.html"><a href="goodness-of-fit.html#further-example-too-good-to-be-true"><i class="fa fa-check"></i><b>11.5</b> Further Example: Too Good to be True?</a></li>
<li class="chapter" data-level="11.6" data-path="goodness-of-fit.html"><a href="goodness-of-fit.html#thoughts-about-r-1"><i class="fa fa-check"></i><b>11.6</b> Thoughts About R</a><ul>
<li class="chapter" data-level="11.6.1" data-path="goodness-of-fit.html"><a href="goodness-of-fit.html#names-for-elements-in-a-list"><i class="fa fa-check"></i><b>11.6.1</b> Names for Elements in a List</a></li>
<li class="chapter" data-level="11.6.2" data-path="goodness-of-fit.html"><a href="goodness-of-fit.html#quick-null-probabilities"><i class="fa fa-check"></i><b>11.6.2</b> Quick Null Probabilities</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html"><i class="fa fa-check"></i><b>12</b> Appendix: Geek Notes</a><ul>
<li class="chapter" data-level="12.1" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#chapter-2"><i class="fa fa-check"></i><b>12.1</b> Chapter 2</a><ul>
<li class="chapter" data-level="12.1.1" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#more-on-structure"><i class="fa fa-check"></i><b>12.1.1</b> More on Structure</a></li>
<li class="chapter" data-level="12.1.2" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#fancier-histograms"><i class="fa fa-check"></i><b>12.1.2</b> Fancier Histograms</a></li>
<li class="chapter" data-level="12.1.3" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#combined-plots"><i class="fa fa-check"></i><b>12.1.3</b> Combined Plots</a></li>
<li class="chapter" data-level="12.1.4" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#adding-rugs"><i class="fa fa-check"></i><b>12.1.4</b> Adding Rugs</a></li>
<li class="chapter" data-level="12.1.5" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#tuning-density-plots"><i class="fa fa-check"></i><b>12.1.5</b> Tuning Density Plots</a></li>
<li class="chapter" data-level="12.1.6" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#more-on-standard-deviation"><i class="fa fa-check"></i><b>12.1.6</b> More on Standard Deviation</a></li>
<li class="chapter" data-level="12.1.7" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#cleveland-dotplots"><i class="fa fa-check"></i><b>12.1.7</b> Cleveland Dotplots</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#chapter-3"><i class="fa fa-check"></i><b>12.2</b> Chapter 3</a><ul>
<li class="chapter" data-level="12.2.1" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#fixed-and-random-effects-in-simulation"><i class="fa fa-check"></i><b>12.2.1</b> Fixed and Random effects in Simulation</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#chapter-4"><i class="fa fa-check"></i><b>12.3</b> Chapter 4</a><ul>
<li class="chapter" data-level="12.3.1" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#point-shapes-in-scatterplots-using-pch"><i class="fa fa-check"></i><b>12.3.1</b> Point Shapes in Scatterplots using <code>pch</code></a></li>
<li class="chapter" data-level="12.3.2" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#scatterplot-matrix"><i class="fa fa-check"></i><b>12.3.2</b> Scatterplot Matrix</a></li>
<li class="chapter" data-level="12.3.3" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#the-rationale-for-values-of-the-correlation-coefficient-r"><i class="fa fa-check"></i><b>12.3.3</b> The Rationale for Values of the Correlation Coefficient, <span class="math inline">\(r\)</span></a></li>
<li class="chapter" data-level="12.3.4" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#computation-of-the-coefficients-in-the-regression-equation"><i class="fa fa-check"></i><b>12.3.4</b> Computation of the Coefficients in the Regression Equation</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#chapter-5"><i class="fa fa-check"></i><b>12.4</b> Chapter 5</a><ul>
<li class="chapter" data-level="12.4.1" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#the-rbind-function"><i class="fa fa-check"></i><b>12.4.1</b> The <code>rbind()</code> Function</a></li>
<li class="chapter" data-level="12.4.2" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#the-cbind-function"><i class="fa fa-check"></i><b>12.4.2</b> The <code>cbind()</code> Function</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#chapter-6"><i class="fa fa-check"></i><b>12.5</b> Chapter 6</a><ul>
<li class="chapter" data-level="12.5.1" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#the-role-of-limits-in-density-plots"><i class="fa fa-check"></i><b>12.5.1</b> The Role of Limits in Density Plots</a></li>
<li class="chapter" data-level="12.5.2" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#more-about-legends"><i class="fa fa-check"></i><b>12.5.2</b> More about Legends</a></li>
<li class="chapter" data-level="12.5.3" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#more-on-strip-plots"><i class="fa fa-check"></i><b>12.5.3</b> More on Strip-plots</a></li>
<li class="chapter" data-level="12.5.4" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#assessing-statistical-significance"><i class="fa fa-check"></i><b>12.5.4</b> Assessing Statistical Significance</a></li>
<li class="chapter" data-level="12.5.5" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#interaction"><i class="fa fa-check"></i><b>12.5.5</b> Interaction</a></li>
</ul></li>
<li class="chapter" data-level="12.6" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#chapter-8"><i class="fa fa-check"></i><b>12.6</b> Chapter 8</a><ul>
<li class="chapter" data-level="12.6.1" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#we-lied-about-the-sd-formulas"><i class="fa fa-check"></i><b>12.6.1</b> We Lied About the SD Formulas!</a></li>
<li class="chapter" data-level="12.6.2" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#are-we-only-ever-interested-in-population-parameters"><i class="fa fa-check"></i><b>12.6.2</b> Are We Only Ever Interested in Population Parameters?</a></li>
</ul></li>
<li class="chapter" data-level="12.7" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#chapter-9"><i class="fa fa-check"></i><b>12.7</b> Chapter 9</a><ul>
<li class="chapter" data-level="12.7.1" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#distinction-between-t-and-z-in-confidence-intervals-for-means"><i class="fa fa-check"></i><b>12.7.1</b> Distinction Between <span class="math inline">\(t\)</span> and <span class="math inline">\(z\)</span> in Confidence Intervals for Means</a></li>
<li class="chapter" data-level="12.7.2" data-path="appendix-geek-notes.html"><a href="appendix-geek-notes.html#how-does-r-find-df"><i class="fa fa-check"></i><b>12.7.2</b> How Does R Find <span class="math inline">\(df\)</span>?</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Elementary Statistics with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="tests-of-significance-1" class="section level1">
<h1><span class="header-section-number">Chapter 10</span> Tests of Significance</h1>
<div id="introduction-5" class="section level2">
<h2><span class="header-section-number">10.1</span> Introduction</h2>
<p>Confidence intervals aim to answer the question:</p>
<blockquote>
<p><em>Given the data at hand, within what range of values does the parameter of interest probably lie?</em></p>
</blockquote>
<p>Now we will turn to another important type of question in statistical inference:</p>
<blockquote>
<p><em>Based on the data at hand, is it reasonable to believe that the parameter of interest is a particular given value?</em></p>
</blockquote>
<p>When we address such a question, we perform a <em>test of hypothesis</em> (also called a <em>test of significance</em>).</p>
<p>In this Chapter we will look at significance tests for each of the Basic Five parameters, one by one. Although the parameters will vary from one research question to another, a test of hypothesis always follows the standard five-step format we studied back in Chapter 4. In what follows, we will go through each of the Basic Five parameters one by one. Our procedure will be as follows:</p>
<ol style="list-style-type: decimal">
<li>State a Research Question that turns out to involve the parameter of interest.</li>
<li>Write out all five steps of the test, calling a “packaged” R-function, the output of which we will use to fill in some of the steps. These functions produce confidence intervals for the parameter in question, so you will have met them already in the previous chapter on confidence intervals.</li>
<li>Look “under the hood” of the test just a bit, to see how the packaged function is getting the test statistic and the P-value. We may also introduce some concepts or terminology that apply to all tests of significance, or to all tests involving one of the Basic Five.</li>
<li>We will try one or two other examples involving the same parameter.</li>
</ol>
<p>After each parameter has been covered, we will discuss some general issues in hypothesis testing. These considerations will apply to all of the tests introduced in this chapter, as well as to the chi-square test from Chapter 4.</p>
<p>Finally, we will undertake a “Grand Review”, in which we practice moving from a Research Question to the proper inferential procedures to address that question.</p>
</div>
<div id="one-population-mean-mu-1" class="section level2">
<h2><span class="header-section-number">10.2</span> One Population Mean <span class="math inline">\(\mu\)</span></h2>
<div id="introductory-research-question" class="section level3">
<h3><span class="header-section-number">10.2.1</span> Introductory Research Question</h3>
<p>Consider the following Research Question concerning the <code>mat111survey</code> data:</p>
<blockquote>
<p><em>Does the data provide strong evidence that the mean fastest speed for all Georgetown College exceeds 100 mph?</em></p>
</blockquote>
</div>
<div id="the-five-steps" class="section level3">
<h3><span class="header-section-number">10.2.2</span> The Five Steps</h3>
<p>Clearly, the parameter of interest is a single population mean. Unlike the situation with the chi-square test, the debate is about the value of a parameter. Hence Step One should include a clear definition of the parameter of interest, followed by a statement of Null and Alternative Hypotheses that lay out views concerning the value of this parameter.</p>
<p><strong>Step One</strong>: <em>Definition of parameter and statement of hypotheses</em>.</p>
<p>We define the parameter first. Let</p>
<blockquote>
<p><span class="math inline">\(\mu\)</span> = the mean fastest driving speed of ALL Georgetown College students.</p>
</blockquote>
<p>Now that we have defined the parameter of interest, we can state our hypotheses in terms of that parameter, using the symbol we have defined:</p>
<blockquote>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu = 100.\)</span></p>
</blockquote>
<blockquote>
<p><span class="math inline">\(H_a\)</span>: <span class="math inline">\(\mu &gt; 100.\)</span></p>
</blockquote>
<p><strong>Step Two:</strong> <em>Safety Check and Reporting the Value of the Test Statistic</em></p>
<p>Just as <code>chisqtestGC()</code> was the work-horse for the <span class="math inline">\(\chi^2\)</span> test for relationship between two factor variables, so in this Chapter there is an R-function that does much of the computational work we need for tests involving population means. In this case the function is the very same one that produced confidence intervals for us, namely: <code>ttestGC()</code>. We simply need to provide a couple of extra arguments in order to alert it to our need for a test of significance:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ttestGC</span>(~fastest,<span class="dt">data=</span>m111survey,<span class="dt">mu=</span><span class="dv">100</span>,
         <span class="dt">alternative=</span><span class="st">&quot;greater&quot;</span>)</code></pre></div>
<p>The <code>mu</code> argument specifies the so-called “Null value”—the value that the Null hypothesis asserts for the parameter <span class="math inline">\(\mu\)</span>. The <code>alternative</code> argument indicates the “direction” of the Alternative Hypothesis—in this case, the Alternative asserts that <span class="math inline">\(\mu\)</span> is <em>greater</em> than 100.</p>
<p>When we run the code above, we get results that will help us through Steps Two through Four in a test of significance.</p>
<p>The first thing we will do is the “safety check”. For each of the Basic Five parameters, the test of significance is built upon the same mathematical ideas that are used in the construction of a confidence interval. Hence the conditions for reliability of the tests are the same as for those of confidence intervals. In this case, we ask that the sample be roughly normal in shape, or that the sample size be at least 30. Hence we pay attention to the “Descriptive Results” first:</p>
<pre><code>## Descriptive Results:
## 
##  variable  mean    sd  n
##   fastest 105.9 20.88 71</code></pre>
<p>We see that the sample size was <span class="math inline">\(n=71\)</span>, quite large enough to trust the approximation-routines that R uses for inferential procedures involving a mean.</p>
<p>The other element of the safety check is to ask whether our sample is like a simple random sample from the population. As we have seen with the <code>mat111survey</code> data, this is a debatable point: the sample consists of all students in MAT 111 from a particular semester, so it’s not really a random sample. On the other hand, for a question like “fastest speed ever driven”, it might be equivalent to a random sample. At any rate, we don’t have much reason to believe that there is a relationship between one’s fastest driving speed and whether or not one enrolls in MAT 111.</p>
<p>So much for the safety check. Now let’s go for the test statistic.</p>
<p>The test statistic in this test is called <em>t</em>. From the <code>ttestGC()</code> output, we see:</p>
<pre><code>##   Test Statistic:        t = 2.382</code></pre>
<p>Apparently the test statistic is <span class="math inline">\(t=2.382\)</span>.</p>
<p><strong>Step Three:</strong> <em>Statement and Interpretation of the P-value</em></p>
<p>Again we read, from the function output, that:</p>
<pre><code>##   P-value:       P = 0.009974</code></pre>
<p>The <span class="math inline">\(p\)</span>-value is about 0.01, or 1%.</p>
<p>In this test, the way to interpret the P-value is as follows:</p>
<blockquote>
<p><strong>P-value Interpretation</strong>: <em>If the mean fastest speed of all GC students is 100 mph, then there is about a 1% chance that the test statistic will be at least as big as the test statistic that we actually got.</em></p>
</blockquote>
<p><strong>Step Four:</strong> <em>Decision</em></p>
<p>As we see from the interpretation of the P-value, a low P-value makes the Null appear to be implausible. Since P &lt; 0.05 for us, we <em>reject the Null Hypothesis.</em></p>
<p><strong>Step Five:</strong> <em>Write a Conclusion</em></p>
<p>As in Chapter Three, this should be a complete sentence in nontechnical language that says how much evidence the data provided for the Alternative Hypothesis. Our conclusion this time is:</p>
<blockquote>
<p><em>This data provides strong evidence that the mean fastest speed for all GC students is greater than 100 mph.</em></p>
</blockquote>
</div>
<div id="under-the-hood-and-further-ideas" class="section level3">
<h3><span class="header-section-number">10.2.3</span> Under the Hood, and Further Ideas</h3>
<div id="t-statistic-formula" class="section level4">
<h4><span class="header-section-number">10.2.3.1</span> t-Statistic Formula</h4>
<p>The formula for the t-statistic is:</p>
<p><span class="math display">\[t = \frac{\bar{x}-\mu_0}{s/\sqrt{n}},\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(\bar{x}\)</span> is the sample mean,</li>
<li><span class="math inline">\(\mu_0\)</span> is what the Null hypothesis thinks that <span class="math inline">\(\mu\)</span> is, and</li>
<li><span class="math inline">\(s/\sqrt{n}\)</span> is the SE for <span class="math inline">\(\bar{x}\)</span>, the same standard error that we have met in previous chapters.</li>
</ul>
<p>Remember that the EV of <span class="math inline">\(\bar{x}\)</span> is just <span class="math inline">\(\mu\)</span>, the mean of the population from which the sample was drawn. The Null believes that <span class="math inline">\(\mu\)</span> is <span class="math inline">\(\mu_0\)</span>, so the Null expects <span class="math inline">\(\bar{x}\)</span> to be about <span class="math inline">\(\mu_0\)</span>, give or take some for chance error. The numerator in the formula, <span class="math inline">\(\bar{x}-\mu_0\)</span>, is often called the <em>observed difference</em>, because it gives the difference between the sample mean that was actually observed and what a believer in the Null would expect that sample mean to be.</p>
<p>The denominator of the t-statistic gives the SE for <span class="math inline">\(\bar{x}\)</span>, which means that is gives the amount by which <span class="math inline">\(\bar{x}\)</span> is liable to differ from the mean of the population. So if the Null is right, then <span class="math inline">\(\bar{x}\)</span> says about how big the observed difference is liable to be.</p>
<p>The t-statistic divided the observed difference by the standard error. Hence the t-statistic is <em>comparing</em> the observed difference with how big the difference should be, if the Null is right. Another way of putting it is:</p>
<blockquote>
<p><em>The t-statistic tells us how many stnadard errors the sample mean is above or below the value that the Null expects.</em></p>
</blockquote>
<p>Consider the test statistic in our first example:</p>
<p><span class="math display">\[t \sim 2.38.\]</span></p>
<p>If we had wanted to, we could have computed the t-statistic from other elements of the test output. Part of the output gives:</p>
<pre><code>## Estimate of mu:   105.9 
## SE(x.bar):    2.478 </code></pre>
<p>So the observed difference is</p>
<p><span class="math display">\[\bar{x}-\mu_0=105.9-100-5.9\]</span></p>
<p>miles per hour. Dividing this by the standard error 2.478, we get:</p>
<p><span class="math display">\[t=\frac{5.9}{2.478} \approx 2.38.\]</span></p>
<p>The results tell us that our sample mean was 2.38 SEs above the value (100 mph) that the Null was expecting it to be. A little bit of give-and-take—due to chance error in the sampling process—is understandable, but these results are more than two SEs above what the Null would expect. Even before we look at the P-value, a large t-statistic tells us that the Null Hypothesis is implausible!</p>
<p>A t-statistic functions analogously to the z-score that we met back in Chapter 2. Just as a z-score tells us how many SDs an individual is above or below the mean for its groups, so the t-statistic tells us how many SEs the estimator is above or below what the Null expects it to be.</p>
</div>
<div id="how-the-p-value-is-computed" class="section level4">
<h4><span class="header-section-number">10.2.3.2</span> How the P-value is Computed</h4>
<p>The P-value in this test is supposed to be the probability – given that the Null Hypothesis is true—of getting a t-statistic at least as big as 2.38, the test statistic that we actually got. Therefore, in order to compute this probability we have to know something about the distribution of the test statistic when the Null is true (sometimes this is called the <em>Null distribution</em> of t).</p>
<p>The key to the null distribution of t lies in a new family of distributions called the <em>t-family</em>. There is one member of the t-family for each positive integer, and this positive integer is called the <em>degrees of freedom</em> of the distribution. The distributions are all continuous, so they all have density curves. The following app lets you explore them:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">require</span>(manipulate)
<span class="kw">tExplore</span>()</code></pre></div>
<p>Over a hundred years ago, William Gossett, the person who discovered the t-statistic, was able to relate the t-statistic to the t-curves.</p>
<p>He found that if:</p>
<ul>
<li>you take a random sample of size <span class="math inline">\(n\)</span>, at least 2, and</li>
<li>the population you sample from is normally distributed, and</li>
<li>the Null Hypothesis is true</li>
</ul>
<p>then</p>
<ul>
<li>the t-statistic has the same distribution as the t-curve whose degrees of freedom is one less than the sample size <span class="math inline">\(n\)</span>.</li>
</ul>
<p>So to find the P-value for your test, we only have to find the area under a t-curve with 70 degrees of freedom (one less than our sample size of 71), past our t-value 2.3818. We can do this with the r-function <code>ptGC()</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ptGC</span>(<span class="fl">2.3818</span>,<span class="dt">region=</span><span class="st">&quot;above&quot;</span>,<span class="dt">df=</span><span class="dv">70</span>)</code></pre></div>
<pre><code>## [1] 0.009975159</code></pre>
<p>The shaded area is the P-value!</p>
<p>If you would like to see a graph of the P-value along with the results of the t-test, then in the <code>ttestGC()</code> function, simply set the argument <code>graph</code> to <code>TRUE</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ttestGC</span>(~fastest,<span class="dt">data=</span>m111survey,<span class="dt">mu=</span><span class="dv">100</span>,
         <span class="dt">alternative=</span><span class="st">&quot;greater&quot;</span>,<span class="dt">graph=</span><span class="ot">TRUE</span>)</code></pre></div>
</div>
<div id="importance-of-safety-checks" class="section level4">
<h4><span class="header-section-number">10.2.3.3</span> Importance of Safety Checks</h4>
<p>According to the mathematics that Gosset worked out, the P-value given by R’s routine is exactly correct only when we have a taken a random sample from a population that is EXACTLY normal in shape. Of course this never occurs in practice.</p>
<p>However, the P-value given by the <code>ttestGC()</code> is approximately correct if the population from which the sample is drawn is approximately bell-shaped. We can’t examine the entire population, but we could look at a histogram or a boxplot of the sample to see if <em>the sample</em> is approximately bell-shaped. If a histogram or boxplot of the sample reveals not too much skewness and no terribly large outliers, we take it as evidence that the population is roughly bell-shaped, in which case the Null distribution of the test statistic has approximately a t-distribution and so R’s P-value is approximately correct.</p>
<p>In general, the larger the sample size, the better the t-curve approximation is, even if the underlying population is far from normal. As a rule of thumb: when the sample size is more than 30, we accept the approximation given by the <code>ttestGC()</code> function, even if a histogram of the sample shows skewness and/or outliers.</p>
<p>In order to judge the effect of using the t-curve to approximate P-values, try the app <code>tSampler()</code> on a skewed population:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">require</span>(manipulate)
<span class="kw">tSampler</span>(~income,<span class="dt">data=</span>imagpop)</code></pre></div>
<p>Try first at a very small sample size, such as <span class="math inline">\(n=2\)</span>, building the density curve for the t-statistics. After you have had enough, compare the density curve for your t-statistics with the t-curve that would give the correct distribution of the t-statistic if the underlying population were normal. Try again for a larger sample size, such as <span class="math inline">\(n=30\)</span>.</p>
</div>
<div id="further-examples" class="section level4">
<h4><span class="header-section-number">10.2.3.4</span> Further Examples</h4>
<div id="a-one-sided-less-than-test" class="section level5">
<h5><span class="header-section-number">10.2.3.4.1</span> A One-Sided “Less Than” Test</h5>
<p>Consider the following:</p>
<blockquote>
<p><strong>Research Question</strong>: <em>The mean GPA of all UK students is known to be 3.3. Does the <code>mat111survey</code> data provide strong evidence that the mean GPA of all GC students is lower than this?</em></p>
</blockquote>
<p><strong>Step One:</strong> Definition of parameter and statement of hypotheses.</p>
<p>Let</p>
<blockquote>
<p><span class="math inline">\(\mu\)</span> = the mean GPA of all GC students.</p>
</blockquote>
<p>Then our hypotheses are:</p>
<blockquote>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu=3.3\)</span></p>
</blockquote>
<blockquote>
<p><span class="math inline">\(H_a\)</span>: <span class="math inline">\(\mu &lt; 3.3\)</span></p>
</blockquote>
<p><strong>Note</strong>: This time, the alternative involves a “less than” statement. Both the original example and this example are “one-sided” tests, but the “side” differs.</p>
<p><strong>Step Two</strong>: Safety Check and Test Statistic.</p>
<p>Again we run the test to extract information needed for steps Two through Four:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ttestGC</span>(~GPA,<span class="dt">data=</span>m111survey,
         <span class="dt">mu=</span><span class="fl">3.3</span>,<span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>)</code></pre></div>
<p>For the safety check, let’s first see if we have more than 30 students in the sample (if we do, we don’t have to make a histogram or boxplot of the sample).</p>
<pre><code>##  variable  mean     sd  n
##       GPA 3.195 0.5067 70</code></pre>
<p>Only one student did not report a GPA. The sample size is 70, which is bigger than 30, so we are safe to proceed.</p>
<p>Next we get the test statistic:</p>
<pre><code>##   Test Statistic:        t = -1.733</code></pre>
<p>The test statistic is -1.73, so our sample mean of 3.19 was 1.73 SEs below what the Null was expecting.</p>
<p><strong>Step Three:</strong> Statement of the P-value</p>
<pre><code>##   P-value:       P = 0.04382</code></pre>
<p>The P-value was 0.044. It’s important to interpret it:</p>
<blockquote>
<p><strong>Interpretation of the P-value</strong>: <em>If the mean GPA of all GC students is the same as it is at UK, then there is only about a 4.4% chance of getting a test statistic less than or equal to the one we actually got.</em></p>
</blockquote>
<p><strong>Note:</strong> When the alternative hypothesis involves “less than” then the P-value is the chance of getting results <em>less</em> than what we actually got, rather than greater than what we got. The P-value appears as a shaded area in Figure [One-Sided Less-Than P-Value].</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ptGC</span>(-<span class="fl">1.73</span>,<span class="dt">region=</span><span class="st">&quot;below&quot;</span>,<span class="dt">df=</span><span class="dv">70</span>,<span class="dt">graph=</span>T)</code></pre></div>
<div class="figure"><span id="fig:pvalueless"></span>
<img src="bookdown-demo_files/figure-html/pvalueless-1.png" alt="One-Sided Less-Than P-Value." width="672" />
<p class="caption">
Figure 10.1: One-Sided Less-Than P-Value.
</p>
</div>
<pre><code>## [1] 0.04401866</code></pre>
<p><strong>Step Four:</strong> Decision</p>
<p>Since the P-value was &lt; 0.05, we reject the Null Hypothesis.</p>
<p><strong>Step Five:</strong> Conclusion</p>
<p>This data provided strong evidence that the mean GPA at GC is less than it is at UK.</p>
</div>
<div id="a-test-from-summary-data" class="section level5">
<h5><span class="header-section-number">10.2.3.4.2</span> A Test From Summary Data</h5>
<p>Sometimes you do not have access to the raw data in a data frame, and only summary statistics are available. You can still perform tests, if you are given sufficient summary information.</p>
<p>Suppose, for example, that the mean length of 16 randomly-caught Great White sharks is 14 feet, and that the standard deviation of the lengths is 3 feet. You are told that a histogram of the 16 weights looked fairly bell-shaped. You are asked to say whether the data provide strong evidence that the mean length of all Great Whites is less than 15 feet.</p>
<p><strong>Step One</strong>: Definition of parameter and statement of hypotheses.</p>
<p>Let</p>
<blockquote>
<p><span class="math inline">\(\mu\)</span> = the mean length of ALL Great White sharks.</p>
</blockquote>
<p>Then our hypotheses are:</p>
<blockquote>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu\)</span> = 15</p>
</blockquote>
<blockquote>
<p><span class="math inline">\(H_a\)</span>: <span class="math inline">\(\mu\)</span> &lt; 15</p>
</blockquote>
<p><strong>Step Two</strong>: Safety Check and Test Statistic</p>
<p>The sample size is 16 which is less than 30, but you are told that the sample is roughly normal. On that basis you hope that the population is roughly normal, so you decide that the P-value provided by <code>ttestGC()</code> is approximately correct.</p>
<p>The protocol for entering summary data is the same as it was for confidence intervals, except that you add the <code>mu</code> and <code>alternative</code> arguments:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ttestGC</span>(<span class="dt">mean=</span><span class="dv">14</span>,<span class="dt">sd=</span><span class="dv">3</span>,<span class="dt">n=</span><span class="dv">16</span>,,<span class="dt">mu=</span><span class="dv">15</span>,<span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>)</code></pre></div>
<pre><code>## 
## 
## Inferential Procedures for One Mean mu:
## 
## 
## Descriptive Results:
## 
##  mean sd  n
##    14  3 16
## 
## 
## Inferential Results:
## 
## Estimate of mu:   14 
## SE(x.bar):    0.75 
## 
## 95% Confidence Interval for mu:
## 
##           lower.bound         upper.bound          
##           -Inf                15.314788            
## 
## Test of Significance:
## 
##  H_0:  mu = 15 
##  H_a:  mu &lt; 15 
## 
##  Test Statistic:     t = -1.333 
##  Degrees of Freedom:   15 
##  P-value:        P = 0.1012</code></pre>
<p>We see that the test statistic is t = -1.33</p>
<p><strong>Step Three</strong>: P-value.</p>
<p>The P-value is 0.10.</p>
<blockquote>
<p><strong>Interpretation of P-value</strong>: <em>If the mean length of all Great White sharks is 15 feet, then there is about a 10% chance of getting a t-statistic of -1.33 or less, as we got in our study.</em></p>
</blockquote>
<p><strong>Step Four:</strong> Decision</p>
<p>Since P &gt; 0.05, we do not reject the Null Hypothesis.</p>
<p><strong>Step Five</strong>: Conclusion</p>
<p>The data did not provide strong evidence that the mean length of all Great Whites is less than 15 feet.</p>
</div>
</div>
</div>
</div>
<div id="difference-of-two-population-means-mu_1-mu_2-1" class="section level2">
<h2><span class="header-section-number">10.3</span> Difference of Two Population Means, <span class="math inline">\(\mu_1-\mu_2\)</span></h2>
<div id="the-difference-of-two-means" class="section level3">
<h3><span class="header-section-number">10.3.1</span> The Difference of Two Means</h3>
<p>We will consider the following Research Question concerning the <code>mat111survey</code> data:</p>
<blockquote>
<p><strong>Research Question</strong>: <em>Does the data provide strong evidence that GC males drive faster, on average, than GC females do?</em></p>
</blockquote>
</div>
<div id="the-five-steps-1" class="section level3">
<h3><span class="header-section-number">10.3.2</span> The Five Steps</h3>
<p><strong>Step One</strong>: Define parameters and state hypotheses.</p>
<p>Although we are interested in only one number (the difference of two means) we have to define both population means in order to talk about that difference. Here we go:</p>
<p>Let</p>
<blockquote>
<p><span class="math inline">\(\mu_1\)</span> = the mean fastest speed of all GC females.</p>
</blockquote>
<blockquote>
<p><span class="math inline">\(\mu_2\)</span> = the mean fastest speed of all GC males.</p>
</blockquote>
<p>Now we can state the Hypotheses:</p>
<blockquote>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_1-\mu_2 = 0\)</span></p>
</blockquote>
<blockquote>
<p><span class="math inline">\(H_a\)</span>: <span class="math inline">\(\mu_1-\mu_2 &lt; 0\)</span></p>
</blockquote>
<p><strong>Step Two</strong>: Safety Check and Test Statistic.</p>
<p>As usual, we run the test in order to gather information needed for steps Two through Four:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ttestGC</span>(fastest~sex,<span class="dt">data=</span>m111survey,<span class="dt">mu=</span><span class="dv">0</span>,<span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>)</code></pre></div>
<p>This time, the <code>mu</code> argument specifies the Null value of <span class="math inline">\(\mu_1-\mu_2\)</span>.</p>
<p>Just as with confidence intervals, the results of the packaged test that R performs are trustworthy only if the following are true:</p>
<blockquote>
<ol style="list-style-type: decimal">
<li>Either we took two independent random samples from two populations, or we did a completely randomized experiment and the two samples are the two treatment groups in that experiment</li>
<li>Both populations are roughly normal, or else the sample sizes are both “large enough” (30 or more will do).</li>
</ol>
</blockquote>
<p>We’ll assume that the sample of males and the sample of females are like SRSs from their respective populations (at least as far as fastest speed is concerned),so Part 1 is OK. As for Part 2, it is doubtful that the two populations of fastest speeds are normal, but from the Descriptive Results (below) we see that our samples are indeed “big enough”:</p>
<pre><code>##   group  mean    sd  n
##  female 100.7 17.82 38
##    male 113.9 22.81 30</code></pre>
<p>Both sample sizes exceed 30. We squeaked by! If one of them had been less than 30 then we would have made a histogram of it and checked for strong skewness/outliers.</p>
<p>As for the test statistic, it is:</p>
<pre><code>##   Test Statistic:        t = -2.725 </code></pre>
<p>We see that the value of the t-statistic is <span class="math inline">\(t = -2.735\)</span>.</p>
<p><strong>Step Three:</strong> P-Value</p>
<p>From the output, we see that:</p>
<pre><code>##   P-value:       P = 0.004289</code></pre>
<p>The P-value is about 0.0043, or 0.43%.</p>
<blockquote>
<p><strong>Interpretation of P-value</strong>: <em>If males and females at GC drive equally fast on average, then there is only about a 0.43% chance of getting a t-statistic less than or equal to -2.735, as we did in our study.</em></p>
</blockquote>
<p><strong>Step Four:</strong> Decision about Null Hypothesis</p>
<p>Since P &lt; 0.05, we reject <span class="math inline">\(H_0\)</span>.</p>
<p><strong>Step Five:</strong> Conclusion</p>
<p>This data provided strong evidence that GC females drive slower than GC males do, on average.</p>
</div>
<div id="under-the-hood-5" class="section level3">
<h3><span class="header-section-number">10.3.3</span> Under the Hood</h3>
<div id="the-formula-for-the-t-statistic" class="section level4">
<h4><span class="header-section-number">10.3.3.1</span> The Formula for the t-statistic</h4>
<p>When we are testing the difference between two means, the formula for the t-statistic is:</p>
<p><span class="math display">\[t = \frac{\bar{x}_1-\bar{x}_2}{\sqrt{s_1^2/n_1+s_2^2/n_2}},\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(\bar{x}_1-\bar{x}_2\)</span> is the difference between the sample means</li>
<li><span class="math inline">\(\sqrt{s_1^2/n_1+s_2^2/n_2}\)</span> is the SE for the difference</li>
</ul>
<p>Remember that if the Null is right, then <span class="math inline">\(\mu_1-\mu_2\)</span> is 0, so the EV of <span class="math inline">\(\bar{x}_1-\bar{x}_2\)</span> is 0. Hence the Null is expecting that the numerator of the t-statistic will work out to around 0, give or take a SE or two.</p>
<p>Therefore, just as in the case of one mean, the t-statistic compares the observed difference with the likely size of the observed difference, by dividing the former quantity by the latter.</p>
<p>This is a common pattern for the test statistics for Basic Five parameters:</p>
<p><span class="math display">\[\text{test statistic} = \frac{\text{observed difference}}{\text{SE for the difference}}.\]</span></p>
<p>Therefore when the test statistic is big, we know that the observed difference is many standard errors away from what the Null expects, and that looks bad for the Null Hypothesis.</p>
</div>
<div id="order-of-groups-1" class="section level4">
<h4><span class="header-section-number">10.3.3.2</span> Order of Groups</h4>
<p>In the foregoing example, note that we have a one-sided “less than” alternative hypothesis, even though the research question asked if there was strong evidence that the mean speed of all GC males is GREATER than the mean speed of all GC females. This is because we have defined our first mean <span class="math inline">\(\mu_1\)</span> as the mean speed of all females, so males being faster would imply that <span class="math inline">\(\mu_1-\mu_2\)</span> is negative. R has certain defaults, usually involving alphabetical order, for which population to consider as the “first” one. If we wish to override these defaults we can do so, using the <code>first</code> argument:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ttestGC</span>(fastest~sex,<span class="dt">data=</span>m111survey,
         <span class="dt">mu=</span><span class="dv">0</span>,<span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>,
         <span class="dt">first=</span><span class="st">&quot;male&quot;</span>)</code></pre></div>
</div>
<div id="the-degrees-of-freedom-in-two-samples" class="section level4">
<h4><span class="header-section-number">10.3.3.3</span> The Degrees of Freedom in Two Samples</h4>
<p>Look at the stated Degrees of Freedom in the output for our test:</p>
<pre><code>##   Degrees of Freedom:      55.49 </code></pre>
<p>It is not a whole number, nor it does not have any clear relationship to the sizes of the two samples (40 females, 31 males). What is going on, here?</p>
<p>The explanation is that when we are dealing with the two-sample t-test, then even if both populations are both perfectly normal the t-statistic does not necessarily have a distribution that is exactly the same as one of the t-curves. Instead, R searches for a t-curve that statistical theory suggests will have a distribution fairly similar to the Null distribution of the t-statistic, and it computes the P-value on the basis of that particular t-curve. The “closest” t-curve in this case turns out to have 55.49 degrees of freedom. (Yes, t-curves can have fractional degrees of freedom!)</p>
<p>Fortunately this is not an issue with which we will have to concern ourselves very much. We only need to pay attention to it if we plan to make pictures of the P-values, like the one in Figure [P-Value in Two-Sample Test]:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ptGC</span>(-<span class="fl">2.735</span>,<span class="dt">region=</span><span class="st">&quot;below&quot;</span>,<span class="dt">df=</span><span class="fl">55.49</span>,<span class="dt">graph=</span>T)</code></pre></div>
<div class="figure"><span id="fig:twosamppvalue"></span>
<img src="bookdown-demo_files/figure-html/twosamppvalue-1.png" alt="P-Value in Two-Sample Test" width="672" />
<p class="caption">
Figure 10.2: P-Value in Two-Sample Test
</p>
</div>
<pre><code>## [1] 0.004179397</code></pre>
</div>
</div>
<div id="additional-examples" class="section level3">
<h3><span class="header-section-number">10.3.4</span> Additional Examples</h3>
<div id="a-randomized-experiment" class="section level4">
<h4><span class="header-section-number">10.3.4.1</span> A Randomized Experiment</h4>
<p>Recall the <code>attitudes</code> experiment. One of the Research Questions we considered back in Chapter Six was the question</p>
<blockquote>
<p><strong>Research Question</strong>: <em>Does the data provide stronge evidence that the suggested race of the defendant was a factor in the sentence recommended by survey participants?</em></p>
</blockquote>
<p>First, let’s take a look at the data again:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(attitudes)
<span class="kw">View</span>(attitudes)
<span class="kw">help</span>(attitudes)</code></pre></div>
<p>Let’s also remind ourselves of the relationship we found in the data:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">favstats</span>(sentence~def.race,<span class="dt">data=</span>attitudes)</code></pre></div>
<pre><code>##   def.race min Q1 median Q3 max     mean       sd   n missing
## 1    black   3 15     25 40  50 27.77500 14.94891 120       1
## 2    white   4 10     25 40  50 25.84694 15.75602 147       0</code></pre>
<p>The defendant whose name suggested he was Black got sentenced to about two years more, on average, than the defendant with the White-sounding name. This goes along with some suspicion we might have that there was some lingering racial prejudice among at least some of the (mostly White) survey participants.</p>
<p>Let us now address our Research Question with a test of significance.</p>
<p><strong>Step One</strong>: Define parameters and state hypotheses</p>
<p>As for the parameters, let:</p>
<blockquote>
<p><span class="math inline">\(\mu_1\)</span> = the mean sentence recommended by all 267 survey participants, if all of the them were to look at a form in which the suggested race of the defendant was Black</p>
</blockquote>
<blockquote>
<p><span class="math inline">\(\mu_2\)</span> = the mean sentence recommended by all 267 survey participants, if all of the them were to look at a form in which the suggested race of the defendant was White</p>
</blockquote>
<p>(You may wish to Review Chapter 8 on how to define parameters of interest when an experiment has been conducted).</p>
<p>Now for the hypotheses:</p>
<blockquote>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_1-\mu_2 = 0\)</span></p>
</blockquote>
<blockquote>
<p><span class="math inline">\(H_a\)</span>: <span class="math inline">\(\mu_1-\mu_2 &gt; 0\)</span></p>
</blockquote>
<p><strong>Step Two:</strong> Safety Check and Test Statistic</p>
<p>Once again, we begin by running the test code:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ttestGC</span>(sentence~def.race,<span class="dt">data=</span>attitudes,
         <span class="dt">mu=</span><span class="dv">0</span>,<span class="dt">alternative=</span><span class="st">&quot;greater&quot;</span>)</code></pre></div>
<p>Safety Check: It was a matter of chance which participant was assigned which type of survey form, so we conducted a randomized experiment. As for the underlying population being roughly normal, we don’t have to worry about that because the descriptive results in the output shows us that both sample sizes were well above 30:</p>
<pre><code>##  group  mean    sd   n
##  black 27.77 14.95 120
##  white 25.85 15.76 147</code></pre>
<p>As for the test statistic, we see:</p>
<pre><code>##   Test Statistic:        t = 1.023 </code></pre>
<p>The observed difference between the treatment group means is about 1 SD above the value of 0 that the Null expects.</p>
<p><strong>Step Three:</strong> P-value</p>
<p>From the output we find that the P-value is 0.1536.</p>
<blockquote>
<p><strong>Interpretation of P-Value</strong>: <em>If the sentences recommended by the students in the study were, on average, unaffected by the suggested race of the defendant, then there is about a 15.36% chance of getting a test statistic at least a big as the one we got.</em></p>
</blockquote>
<p><strong>Step Four:</strong> Decision</p>
<p>Since P &gt; 0.05, we do not reject the Null Hypothesis.</p>
<p><strong>Step Five:</strong> Conclusion</p>
<p>This study did not provide strong evidence that the students in the survey were affected by race when they recommended a sentence.</p>
</div>
<div id="a-two-sided-test" class="section level4">
<h4><span class="header-section-number">10.3.4.2</span> A Two-Sided Test</h4>
<p>So far all of the tests we have conducted have been <em>one-sided</em>: either the Alternative Hypothesis states that the value of the parameter is GREATER than the Null’s value. or else it says that the parameter is LESS than the Null’s value.</p>
<p>A one sided-test comes along with a one-sided approach to computing a P-value.</p>
<p>For example, when the alternative says GREATER, then the P-value is the chance of the test statistic being equal to or GREATER THAN the value we actually observed for it. On the other hand, when the alternative says LESS, then the P-value is the chance of the test statistic being LESS THAN or equal to the value we actually observed for it.</p>
<p>As a rule, people work with a one-sided Alternative Hypothesis if they have some good reason to suspect—prior to examining the data in the study at hand—that the value of the parameter lies on the side of the Null’s value that is specified by the Alternative. For example, in the “race and recommended sentence” study in the first example of this section, we might have had some prior data or other knowledge that suggests that GC students might be inclined to mete out heavier sentences to a black defendant, and we are using the study to check that view. In that case the one-sided hypothesis would be an appropriate choice.</p>
<p>But suppose that we really don’t have any prior reason to believe that a black defendant would be treated worse, and that we are conducting the study just to see if race makes a difference in sentencing, <em>one way or the other</em>. In that case, a <em>two-sided</em> test of significance might be more appropriate.</p>
<p>Let’s re-do the race and sentencing test, but this time in a two-sided way:</p>
<p><strong>Step One</strong>: Define parameters and state hypotheses</p>
<p>This is the same as before. Let</p>
<blockquote>
<p><span class="math inline">\(\mu_1\)</span> = the mean sentence recommended by all 267 survey participants, if all of the them were to look at a form in which the suggested race of the defendant was Black</p>
</blockquote>
<blockquote>
<p><span class="math inline">\(\mu_2\)</span> = the mean sentence recommended by all 267 survey participants, if all of the them were to look at a form in which the suggested race of the defendant was White</p>
</blockquote>
<p>Now for the hypotheses:</p>
<blockquote>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_1-\mu_2 = 0\)</span></p>
</blockquote>
<blockquote>
<p><span class="math inline">\(H_a\)</span>: <span class="math inline">\(\mu_1-\mu_2 \neq 0\)</span></p>
</blockquote>
<p><strong>Step Two:</strong> Safety Check and Test Statistic</p>
<p>Safety Check: Same as before. Randomized experiment, large group sizes: we are safe.</p>
<p>For the test statistic, we run the test with the <code>alternative</code> argument set to “two.sided”:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ttestGC</span>(sentence~def.race,<span class="dt">data=</span>attitudes,
       <span class="dt">mu=</span><span class="dv">0</span>,<span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)</code></pre></div>
<pre><code>## 
## 
## Inferential Procedures for the Difference of Two Means mu1-mu2:
##  (Welch&#39;s Approximation Used for Degrees of Freedom)
##   sentence grouped by def.race 
## 
## 
## Descriptive Results:
## 
##  group  mean    sd   n
##  black 27.77 14.95 120
##  white 25.85 15.76 147
## 
## 
## Inferential Results:
## 
## Estimate of mu1-mu2:  1.928 
## SE(x1.bar - x2.bar):  1.884 
## 
## 95% Confidence Interval for mu1-mu2:
## 
##           lower.bound         upper.bound          
##           -1.782671           5.638793             
## 
## Test of Significance:
## 
##  H_0:  mu1-mu2 = 0 
##  H_a:  mu1-mu2 != 0 
## 
##  Test Statistic:     t = 1.023 
##  Degrees of Freedom:   259.1 
##  P-value:        P = 0.3072</code></pre>
<p>Again see that t is about 1.02. The observed difference between the treatment group means is about 1 SD above the value of 0 that the Null expects.</p>
<p><strong>Step Three:</strong> P-value</p>
<p>This time P-value is 0.3072, as compared to 0.1536 in the one-sided test. What has happened?</p>
<p>In a two-sided test, the P-value is the probability (assuming that the Null is true) of getting a test statistic <em>at least as far from zero</em> (either on the positive or the negative side) as the test statistic that we actually got. Graphically, it looks like Figure [Two-Sided P-Value]:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ptGC</span>(<span class="kw">c</span>(-<span class="fl">1.02</span>,<span class="fl">1.02</span>),<span class="dt">region=</span><span class="st">&quot;outside&quot;</span>,
     <span class="dt">df=</span><span class="fl">259.052</span>,<span class="dt">graph=</span><span class="ot">TRUE</span>)</code></pre></div>
<div class="figure"><span id="fig:twosidedp"></span>
<img src="bookdown-demo_files/figure-html/twosidedp-1.png" alt="Two-Sided P-Value" width="672" />
<p class="caption">
Figure 10.3: Two-Sided P-Value
</p>
</div>
<pre><code>## [1] 0.3086801</code></pre>
<p>Due to the symmetry of the t-curve, a two-sided P-value will generally be twice the corresponding one-sided P-value.</p>
<p>The reason we incorporate both “sides” of the shaded area into the P-value is that at the outset we were indifferent as to whether <span class="math inline">\(\mu_1=\mu_2\)</span> was positive or negative. The one-sided hypothesis is offered presumably by someone who already has some prior evidence suggesting that the test statistic should turn out a particular way—either positive or negative. Since the P-value measures strength of evidence against the Null, with smaller P-values providing more evidence against the Null, it makes sense that for the same test statistic a one-sided test should return a smaller P-value than a two-sided test. The one sided-test has the evidence from the current data <em>together with some prior evidence</em>, whereas the two-sided test has only the evidence from the current data.</p>
<p>How do we interpret the P-value in a two-sided test? We simply talk about “distance from zero.” So for this study we say:</p>
<blockquote>
<p><em>If the suggested race of defendant has no effect on recommended sentence, then there is about a 30.72% chance of getting a t-statistic at least as far from zero as the one we got in our study.</em></p>
</blockquote>
<p><strong>Step Four:</strong> Decision</p>
<p>Since P &gt; 0.05, we do not reject the Null Hypothesis.</p>
<p><strong>Step Five:</strong> Conclusion</p>
<p>This study did not provide strong evidence that the students in the survey were affected by race when they recommended a sentence.</p>
</div>
</div>
</div>
<div id="mean-of-differences-mu_d-1" class="section level2">
<h2><span class="header-section-number">10.4</span> Mean of Differences <span class="math inline">\(\mu_d\)</span></h2>
<p>In this case we usually have paired data.</p>
<div id="introductory-research-question-1" class="section level3">
<h3><span class="header-section-number">10.4.1</span> Introductory Research Question</h3>
<p>Recall the <code>labels</code> data, where participants were asked to rate peanut butter from a jar labeled Jiff, and to rate peanut butter from a jar labeled Great Value, when—unknown to the subjects—both jars contained the same peanut butter.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(labels)
<span class="kw">View</span>(labels)
<span class="kw">help</span>(labels)</code></pre></div>
<p>Recall that subjects tended to rate the Jiff-labeled jar higher:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">diff &lt;-<span class="st"> </span>labels$jiffrating-labels$greatvaluerating
<span class="kw">favstats</span>(diff)</code></pre></div>
<pre><code>##  min Q1 median Q3 max     mean       sd  n missing
##   -5  1    2.5  4   8 2.366667 2.809876 30       0</code></pre>
<p>But does this data provide strong evidence that the GC population as a whole (not just this sample of 30 students) would rate Jiff higher? In order to address this question, we perform a test of significance:</p>
</div>
<div id="the-five-steps-2" class="section level3">
<h3><span class="header-section-number">10.4.2</span> The Five Steps</h3>
<p><strong>Step One</strong>: Define parameters and state hypotheses.</p>
<p>The study had a repeated measures design (every participant was measured twice). The parameter of interest is</p>
<blockquote>
<p><span class="math inline">\(\mu_d\)</span> = mean difference in ratings (Jiff minus Great Value) for ALL Georgetown College students</p>
</blockquote>
<p>As for hypotheses:</p>
<blockquote>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_d = 0\)</span> (jar makes no difference)</p>
</blockquote>
<blockquote>
<p><span class="math inline">\(H_a\)</span>: <span class="math inline">\(\mu_d &gt; 0\)</span> (Jiff jar rated higher, on average)</p>
</blockquote>
<p>We chose the one-sided alternative because Jiff is the more expensive brand, and we have some reasons—based on prior studies about price and perception of quality—to believe that pricier brands are perceived to be of higher quality.</p>
<p><strong>Step Two</strong>: Safety Check and Test Statistic.</p>
<p>Hopefully the 30 students in the study were like a random sample from the GC population. The sample size is right at the boundary-value of 30, so let’s go ahead and look at a graph of the sample of differences, checking for strong skewness or big outliers.</p>
<div class="figure"><span id="fig:diffhistogramratings"></span>
<img src="bookdown-demo_files/figure-html/diffhistogramratings-1.png" alt="Rating Differences" width="672" />
<p class="caption">
Figure 10.4: Rating Differences
</p>
</div>
<p>A histogram of the differences is shown in Figure [Rating Differences]. There is a little skewness to the left, perhaps, but not nearly enough to worry about, especially considering our reasonably large sample size. We are safe.</p>
<p>For the test statistic and other information in steps Two through Four, we run <code>ttestGC()</code>, using a special formula-style for matched pairs or repeated-measures data:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ttestGC</span>(~jiffrating-greatvaluerating,
         <span class="dt">data=</span>labels,<span class="dt">mu=</span><span class="dv">0</span>,<span class="dt">alternative=</span><span class="st">&quot;greater&quot;</span>)</code></pre></div>
<pre><code>## 
## 
## Inferential Procedures for the Difference of Means mu-d:
##   jiffrating minus greatvaluerating 
## 
## 
## Descriptive Results:
## 
##                     Difference mean.difference sd.difference  n
##  jiffrating - greatvaluerating           2.367          2.81 30
## 
## 
## Inferential Results:
## 
## Estimate of mu-d:     2.367 
## SE(d.bar):    0.513 
## 
## 95% Confidence Interval for mu-d:
## 
##           lower.bound         upper.bound          
##           1.494996            Inf                  
## 
## Test of Significance:
## 
##  H_0:  mu-d = 0 
##  H_a:  mu-d &gt; 0 
## 
##  Test Statistic:     t = 4.613 
##  Degrees of Freedom:   29 
##  P-value:        P = 3.711e-05</code></pre>
<p>The t-statistic is about 4.6133. The mean of the sample differences in ratings is 4.6 SDs above what the Null expects it to be!</p>
<p><strong>Step Three:</strong> P-value</p>
<p>Once again, R finds an approximate P-value by using a t-curve (with degrees of freedom one less than the number of pairs in the sample). As we can read from the test output, the P-value is <span class="math inline">\(3.7 \times 10^{-5}\)</span>, or 0.000037 or about 0.00004, which is very small indeed. The interpretation is:</p>
<blockquote>
<p><strong>Interpretation of P-Value</strong>: <em>If ratings are unaffected by labels, then there is only about 4 in 100,000 chance of getting a t-statistic at least as big as the one we got in our study.</em></p>
</blockquote>
<p><strong>Step Four</strong>: Decision</p>
<p>Since P &lt; 0.05, we reject the Null.</p>
<p><strong>Step Five:</strong> Conclusion</p>
<p>This data provided very strong evidence that on average people will rate the peanut butter with a more expensive brand-label more highly than the same peanut butter labeled with a less-expensive brand name.</p>
</div>
<div id="under-the-hood-6" class="section level3">
<h3><span class="header-section-number">10.4.3</span> Under the Hood</h3>
<p>The formula for the t-statistic is:</p>
<p><span class="math display">\[t = \frac{\hat{d}-\mu_{d,0}}{s_d/\sqrt{n}},\]</span></p>
<p>where</p>
<ul>
<li><span class="math inline">\(\hat{d}\)</span> is the mean of the sample differences</li>
<li><span class="math inline">\(\mu_{d,0}\)</span> is what the Null Hypothesis believes <span class="math inline">\(\mu_d\)</span> is (usually this is 0)</li>
<li><span class="math inline">\(s_d/\sqrt{n}\)</span> is the SE for <span class="math inline">\(\hat{d}\)</span></li>
</ul>
<p>So once again the t-statistic follows the familiar pattern:</p>
<p><span class="math display">\[\text{test statistic} = \frac{\text{observed difference}}{\text{SE for the difference}}.\]</span></p>
<p>It tells us how many SEs the estimator <span class="math inline">\(\hat{d}\)</span> is above or below what the Null expects it to be.</p>
<p>This familiar pattern—which applies to each of the three Basic Five parameters involving means—-deserves a name. Let’s call it a <em>z-score-style</em> statistic, since it works like a z-score, measuring the number of SEs the estimator is above or below what the Null expects the parameter to be.</p>
</div>
<div id="additional-examples-1" class="section level3">
<h3><span class="header-section-number">10.4.4</span> Additional Examples</h3>
<div id="height-and-ideal-height" class="section level4">
<h4><span class="header-section-number">10.4.4.1</span> Height and Ideal Height</h4>
<p>Recall that in the <code>m111survey</code> participants were asked their height, and the ideal height that they wanted to be. Let’s consider the following</p>
<blockquote>
<p><strong>Research Question</strong>: <em>Does the study provide strong evidence that, on average, the ideal height of GC students differs from their actual height?</em></p>
</blockquote>
<p><strong>Step One</strong> Define Parameter and State Hypotheses</p>
<p>Let</p>
<blockquote>
<p><span class="math inline">\(\mu_d\)</span> = the mean difference (ideal height minus actual height) for all GC students</p>
</blockquote>
<p>Then our hypotheses are:</p>
<blockquote>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_d = 0\)</span></p>
</blockquote>
<blockquote>
<p><span class="math inline">\(H_a\)</span>: <span class="math inline">\(\mu_d \neq 0\)</span></p>
</blockquote>
<p>Note that we have here a two-sided test. Apparently we did not have any prior idea as to whether students want to be taller than they are, on average, or shorter than they are on average.</p>
<p><strong>Step Two</strong> Safety Check and Test Statistic</p>
<p>We get the information we need:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ttestGC</span>(~ideal_ht-height,<span class="dt">data=</span>m111survey,
         <span class="dt">mu=</span><span class="dv">0</span>,<span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)</code></pre></div>
<pre><code>## 
## 
## Inferential Procedures for the Difference of Means mu-d:
##   ideal_ht minus height 
## 
## 
## Descriptive Results:
## 
##         Difference mean.difference sd.difference  n
##  ideal_ht - height           1.946         3.206 69
## 
## 
## Inferential Results:
## 
## Estimate of mu-d:     1.946 
## SE(d.bar):    0.3859 
## 
## 95% Confidence Interval for mu-d:
## 
##           lower.bound         upper.bound          
##           1.175528            2.715776             
## 
## Test of Significance:
## 
##  H_0:  mu-d = 0 
##  H_a:  mu-d != 0 
## 
##  Test Statistic:     t = 5.041 
##  Degrees of Freedom:   68 
##  P-value:        P = 3.652e-06</code></pre>
<p>There are 69 people who gave usable answers, so the sample is large enough that we don’t have to verify that it looks roughly normal. Also, we are assuming that the sample is like a simple random sample, as far as variables like height are concerned, so we are safe to proceed.</p>
<p>The t-statistic is about 5.04. The sample mean of differences is more than 5 SEs above what the Null expected it to be!</p>
<p><strong>Step Three</strong>: P-value</p>
<p>The P-value is <span class="math inline">\(3.65 \times 10^{-6}\)</span>, about 3 in a million.</p>
<blockquote>
<p><strong>Interpretation of P-Value</strong>: <em>If on average GC students desire to be no taller and no shorter than they actually are, then there is only about a 3 in one million chance of getting a test-statistic at least as far from 0 as the one we got in this study.</em></p>
</blockquote>
<p><strong>Step Four</strong>: Decision</p>
<p>P &lt; 0.05, so we reject the Null.</p>
<p><strong>Step Five</strong>: Conclusion</p>
<p>This study provided very strong evidence that on average GC students want to be taller than they actually are.</p>
<div id="tests-and-confidence-intervals" class="section level5">
<h5><span class="header-section-number">10.4.4.1.1</span> Tests and Confidence Intervals</h5>
<p>In the output from the previous example, look at the confidence interval for <span class="math inline">\(\mu_d\)</span> that is provided. (Recall that by default it is a 95%-confidence interval.) Notice that it does not contain 0, so according to the way we interpret confidence intervals we are confident that <span class="math inline">\(\mu_d\)</span> does not equal 0. Of course 0 is what the Null Hypothesis believes <span class="math inline">\(\mu_d\)</span> is, so we could just as well say that we are confident that the Null is false.</p>
<p>This is an example of a relationship that holds quite generally between two-sided tests and two-sided confidence intervals:</p>
<blockquote>
<p><strong>Test-Interval Relationship</strong>: When a 95% confidence interval for the population parameter does not contain the Null value <span class="math inline">\(\mu_0\)</span> for that parameter, then the P-value for a two-sided test</p>
</blockquote>
<blockquote>
<p><span class="math inline">\(H_0\)</span> <span class="math inline">\(\mu = \mu_0\)</span></p>
</blockquote>
<blockquote>
<p><span class="math inline">\(H_a\)</span> <span class="math inline">\(\mu \neq \mu_0\)</span></p>
</blockquote>
<blockquote>
<p>will give a P-value less than 0.05, and so the Null will be rejected when the cut-off value <span class="math inline">\(\alpha\)</span> is 0.05.</p>
</blockquote>
<p>Also:</p>
<blockquote>
<p>When a 95% confidence interval for the population parameter DOES contain the Null value <span class="math inline">\(\mu_0\)</span> for that parameter, then the P-value for a two-sided test will give a P-value greater than 0.05, and so the Null will not be rejected when the cut-off value <span class="math inline">\(\alpha\)</span> is 0.05.</p>
</blockquote>
<p>This all makes, sense, because a confidence interval gives the set of values for the population parameter that could be considered reasonable, based on the data at hand. When a particular value is inside the interval, it is reasonable. When outside, it is not reasonable.</p>
<p>The relationship also holds for other confidence levels, provided that you adjust the cut-off value <span class="math inline">\(\alpha\)</span>. In general:</p>
<blockquote>
<p>When a <span class="math inline">\(100 \times(1-\alpha)\)</span>% confidence interval for the population parameter does not contain the Null value <span class="math inline">\(\mu_0\)</span> for that parameter, then the P-value for a two-sided test will give a P-value less than <span class="math inline">\(\alpha\)</span>.</p>
</blockquote>
<blockquote>
<p>When a <span class="math inline">\(100 \times (1-\alpha)\)</span>% confidence interval for the population parameter DOES contain the Null value <span class="math inline">\(\mu_0\)</span> for that parameter, then the P-value for a two-sided test will give a P-value greater than <span class="math inline">\(\alpha\)</span>.</p>
</blockquote>
<p>You may also have noticed that in one sided tests, the <code>ttestGC()</code> function produces one-sided confidence intervals. Recall for example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(fastest~sex,<span class="dt">data=</span>m111survey,<span class="dt">mu=</span><span class="dv">0</span>,<span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>)</code></pre></div>
<p>The one-sided 95% confidence interval extended from negative infinity to -5.17. This interval does not contain zero, which is the Null’s value for <span class="math inline">\(\mu_1-\mu_2\)</span>, and so the Null is rejected with a P-value of less than 0.05.</p>
<p>The relationship between tests and confidence intervals holds not only for two-sided tests and two-sided intervals, but also for one-sided tests and the corresponding one-sided confidence intervals.</p>
</div>
</div>
<div id="repeated-measures-or-two-independent-samples" class="section level4">
<h4><span class="header-section-number">10.4.4.2</span> Repeated Measures, or Two Independent Samples?</h4>
<p>Let’s look again at the <code>labels</code> data. By now we are convinced that the data provide strong evidence that GC students (the population from which the data was drawn) are inclined to rate the same product more highly when it is packaged as an “expensive” product that when it as packaged as “cheap”. But notice that in addition to recording the ratings, researchers also recorded the sex of each participant in the study. This raises another interesting research question:</p>
<blockquote>
<p><strong>Research Question</strong>: <em>Who will be more affected, on average, by the label on a product: a GC female or a GC male?</em></p>
</blockquote>
<p>The original study had a repeated measures design, which resulted in the parameter of interest being a difference of two means. However, when we take sex into consideration things change substantially. Although we still think about the difference between the ratings, we are primarily interested in whether the mean difference for all GC females and the mean differences for all GC guys differ. Thus, the parameter of interest will be a differences of means, where each mean is itself a mean of differences!</p>
<p>Here are the five steps:</p>
<p><strong>Step One</strong>: Definition of Parameters and Statement of Hypotheses</p>
<p>Let</p>
<blockquote>
<p><span class="math inline">\(\mu_d^f\)</span> = the mean difference in rating (Jiff minus Great Value) for all GC females, if all of them could have participated in this study.</p>
</blockquote>
<blockquote>
<p><span class="math inline">\(\mu_d^m\)</span> = the mean difference in rating (Jiff minus Great Value) for all GC males, if all of them could have participated in this study.</p>
</blockquote>
<p>The hypotheses are:</p>
<blockquote>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_d^f - \mu_d^m = 0\)</span></p>
</blockquote>
<blockquote>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_d^f - \mu_d^m \neq 0\)</span></p>
</blockquote>
<p>We chose a two-sided test because we do not have any prior evidence indicating that the difference is positive, or that it is negative.</p>
<p><strong>Step Two</strong> Safety Check and Test Statistic</p>
<p>This time we are dealing with two independent (and hopefully random) samples from our two populations. The samples sizes, though, are not so large:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">diff &lt;-<span class="st"> </span>labels$jiffrating -<span class="st"> </span>labels$greatvaluerating</code></pre></div>
<p>[Note that the sample mean difference for the females was a good bit larger than the sample mean difference for the males.]</p>
<p>We have only 15 students in each sample. Since these sample sizes are less than our “safe level” of 30, we really ought to examine them to see if they show signs of strong skewness or outliers.</p>
<div class="figure"><span id="fig:diffsbysex"></span>
<img src="bookdown-demo_files/figure-html/diffsbysex-1.png" alt="Rating Differences for Males and for Females" width="672" />
<p class="caption">
Figure 10.5: Rating Differences for Males and for Females
</p>
</div>
<p>The results appear in Figure [Rating Differences for Males and Females]. There is some left skewness in the sample of males. We will go ahead and perform the test, but the P-value should be considered a bit dodgy.</p>
<p>For the test, we need to add the differences to our data frame. We accomplish this step as follows:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">labels$diff &lt;-<span class="st"> </span>diff</code></pre></div>
<p>Now R will recognize <strong>diff</strong> and process it appropriately, with the usual formula-data input:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ttestGC</span>(diff~sex,<span class="dt">data=</span>labels,
         <span class="dt">mu=</span><span class="dv">0</span>,<span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)</code></pre></div>
<pre><code>## 
## 
## Inferential Procedures for the Difference of Two Means mu1-mu2:
##  (Welch&#39;s Approximation Used for Degrees of Freedom)
##   diff grouped by sex 
## 
## 
## Descriptive Results:
## 
##   group  mean    sd  n
##  female 3.533 2.264 15
##    male 1.200 2.883 15
## 
## 
## Inferential Results:
## 
## Estimate of mu1-mu2:  2.333 
## SE(x1.bar - x2.bar):  0.9465 
## 
## 95% Confidence Interval for mu1-mu2:
## 
##           lower.bound         upper.bound          
##           0.389583            4.277084             
## 
## Test of Significance:
## 
##  H_0:  mu1-mu2 = 0 
##  H_a:  mu1-mu2 != 0 
## 
##  Test Statistic:     t = 2.465 
##  Degrees of Freedom:   26.51 
##  P-value:        P = 0.02047</code></pre>
<p>The value of the t-statistic is 2.47. The observed difference between the sample mean differences for the females and the males is 2.47 SEs above 0 (the value the Null expected it to be).</p>
<p><strong>Step Three</strong>: P-value.</p>
<p>The two-sided P-value is 0.02047.</p>
<p><strong>Step Four</strong>: Decision</p>
<p>Since P &lt; 0.05, we reject the Null.</p>
<p><strong>Step Five</strong>: Conclusion</p>
<p>This data provided strong evidence that GC females are more affected by labels than GC males are.</p>
<p>We might wonder what this all means. Do GC females pay more attention to their surroundings—in particular, to labels on products?? Who knows!</p>
</div>
</div>
</div>
<div id="one-population-proportion-p-1" class="section level2">
<h2><span class="header-section-number">10.5</span> One Population Proportion <span class="math inline">\(p\)</span></h2>
<p>Recall the distribution of the variable <strong>sex</strong> in the <code>m111survey</code> data:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rowPerc</span>(<span class="kw">xtabs</span>(~sex,<span class="dt">data=</span>m111survey))</code></pre></div>
<pre><code>##    
## sex female  male Total
##      56.34 43.66   100</code></pre>
<p>56% of the sample—-more than half—were females. This suggests the following:</p>
<blockquote>
<p><strong>Research Question</strong>: <em>Does this data constitute strong evidence that a majority of the GC student body are female?</em></p>
</blockquote>
<div id="the-five-steps-3" class="section level3">
<h3><span class="header-section-number">10.5.1</span> The Five Steps</h3>
<p><strong>Step One</strong>: Definition of Parameter and Statement of Hypotheses</p>
<p>Let</p>
<blockquote>
<p><span class="math inline">\(p\)</span> = the proportion of females in the GC student population</p>
</blockquote>
<p>Then our hypotheses are:</p>
<blockquote>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(p = 0.50\)</span></p>
</blockquote>
<blockquote>
<p><span class="math inline">\(H_a\)</span>: <span class="math inline">\(p &gt; 0.50\)</span></p>
</blockquote>
<p>We chose 0.50 as the Null value for <span class="math inline">\(p\)</span>, because we wonder if females are in the majority (proportion bigger than 0.5) at GC. Choosing the Null in this way allows the Alternative to express the idea that females are in the majority. If we had let the Null say something else (<span class="math inline">\(p= 0.48\)</span> for example) then the Alternative (<span class="math inline">\(p &gt; 0.48\)</span>) would leave a bit of room for females NOT be in the majority.</p>
<p><strong>Step Two</strong>: Safety Check and Test Statistic</p>
<p>As with confidence intervals for one population proportion, the safety check for significance tests includes thinking about whether our sample is like a simple random sample—at least with respect to the variables we are measuring. In this study, our sample consists of all the students taking MAT 111 in a given semester. Now people often take MAT 111 for reasons connected to the requirements of their prospective major. If the two sexes differ with regard to what majors they prefer, then this sample could be a biased one. On these grounds, our test is going to be a bit untrustworthy.</p>
<p>Let’s go ahead and run the test. As with confidence intervals, when we are interested in a single proportion we can use <code>binomtestGC()</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">binomtestGC</span>(~sex,<span class="dt">data=</span>m111survey,<span class="dt">p=</span><span class="fl">0.5</span>,
            <span class="dt">alternative=</span><span class="st">&quot;greater&quot;</span>,<span class="dt">success=</span><span class="st">&quot;female&quot;</span>)</code></pre></div>
<pre><code>## Exact Binomial Procedures for a Single Proportion p:
##  Variable under study is sex 
## 
## Descriptive Results:  40 successes in 71 trials
## 
## Inferential Results:
## 
## Estimate of p:    0.5634 
## SE(p.hat):    0.0589 
## 
## 95% Confidence Interval for p:
## 
##           lower.bound         upper.bound          
##           0.458929            1.000000             
## 
## Test of Significance:
## 
##  H_0:  p = 0.5 
##  H_a:  p &gt; 0.5 
## 
##  P-value:        P = 0.1712</code></pre>
<p>Notice what we had to do in order to get all that we needed for the test:</p>
<ul>
<li>we had to specify the Null value for <span class="math inline">\(p\)</span> by using the <code>p</code> argument;</li>
<li>we had to set <code>alternative</code> to “greater” in order to accommodate our one-sided Alternative Hypothesis;</li>
<li>we had to say what the proportion is a proportion of: is it a proportion of females or a proportion of males? We accomplished this by specifying what we considered to be a success when the sample was tallied. Since we are interested in the proportion of females, we counted the females as a success, so we set the <code>success</code> argument to “female”.</li>
</ul>
<p>Looking at the output, you might wonder what the test statistic is. In <code>binomtestGC()</code>, it’s pretty simple: it’s just the number of females: 40 out of the 71 people sampled.</p>
<p><strong>Step Three</strong> The P-value</p>
<p>This is 0.1712. It is the probability of getting at least 40 females in a sample of size 71, if the population consists of 50% females. So we might interpret the P-value as follows:</p>
<blockquote>
<p><strong>Interpretation of P-Value</strong>: <em>If only half of the GC population is female, then there is about a 17% chance of getting at least as many females (40) as we actually got in our sample.</em></p>
</blockquote>
<p><strong>Step Four</strong> Decision</p>
<p>We do not reject the Null, since the P-value is above our standard cut-off of 5%.</p>
<p><strong>Step Five</strong>: Conclusion</p>
<p>This survey data did not provide strong evidence that females are in the majority at Georgetown College.</p>
</div>
<div id="under-the-hood-7" class="section level3">
<h3><span class="header-section-number">10.5.2</span> Under the Hood</h3>
<p>Note that the test statistic did not follow the “z-score” pattern of the three previous tests involving means. The test statistic is simply the observed number of successes.</p>
<p><code>binomtestGC()</code> gets its P-value straight from the binomial distribution. If we wanted, we could get the same P-value using the familiar <strong>pbinomGC</strong> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pbinomGC</span>(<span class="dv">39</span>,<span class="dt">region=</span><span class="st">&quot;above&quot;</span>,<span class="dt">size=</span><span class="dv">71</span>,<span class="dt">prob=</span><span class="fl">0.5</span>)</code></pre></div>
<p>It may be worth recalling that, as with any test function in the <code>tigerstats</code> package, you can get a graph of the P-value simply by setting the argument <code>graph</code> to <code>TRUE</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">binomtestGC</span>(~sex,<span class="dt">data=</span>m111survey,<span class="dt">p=</span><span class="fl">0.5</span>,
            <span class="dt">alternative=</span><span class="st">&quot;greater&quot;</span>,<span class="dt">success=</span><span class="st">&quot;female&quot;</span>,
            <span class="dt">graph=</span><span class="ot">TRUE</span>)</code></pre></div>
<p>Now we know from Chapter 7 that when the number of trials <span class="math inline">\(n\)</span> is large enough, then the distribution of a binomial random variable looks very much like a normal curve. In fact, when this is so, <code>binomtestGC()</code> will actually use a normal curve to approximate the P-value!</p>
<p>There is another test that makes use of the normal approximation in order to get the P-value, and it is encapsulated in the <code>proptestGC()</code> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">proptestGC</span>(~sex,<span class="dt">data=</span>m111survey,<span class="dt">p=</span><span class="fl">0.50</span>,
        <span class="dt">alternative=</span><span class="st">&quot;greater&quot;</span>,<span class="dt">success=</span><span class="st">&quot;female&quot;</span>)</code></pre></div>
<pre><code>## 
## 
## Inferential Procedures for a Single Proportion p:
##  Variable under study is sex 
##  Continuity Correction Applied to Test Statistic
## 
## 
## Descriptive Results:
## 
##  female  n estimated.prop
##      40 71         0.5634
## 
## 
## Inferential Results:
## 
## Estimate of p:    0.5634 
## SE(p.hat):    0.05886 
## 
## 95% Confidence Interval for p:
## 
##           lower.bound         upper.bound          
##           0.466564            1.000000             
## 
## Test of Significance:
## 
##  H_0:  p = 0.5 
##  H_a:  p &gt; 0.5 
## 
##  Test Statistic:     z = 0.9571 
##  P-value:        P = 0.1692</code></pre>
<p>Here the test statistic is</p>
<p><span class="math display">\[z=\frac{\hat{p}-p_0}{\sqrt{\frac{\hat{p}(1-\hat{p})}{n}}},\]</span></p>
<p>where</p>
<ul>
<li><span class="math inline">\(\hat{p}\)</span> is the sample proportion,</li>
<li><span class="math inline">\(p_0\)</span> is the Null value of <span class="math inline">\(p\)</span>,</li>
<li>the denominator is the standard error of <span class="math inline">\(\hat{p}\)</span>.</li>
</ul>
<p>Like the test statistics for means, it is “z-score style”: it measures how many standard errors the sample proportion is above or below what the Null Hypothesis expects it to be.</p>
<p>When the sample size is large enough and the Null is true, the distribution of this test statistic is approximately normal with mean 0 and standard deviation 1. in other words, it has the standard normal distribution. Therefore the P-value comes from looking at the area under the standard normal curve past the value of the test statistic. (We also apply a small <em>continuity correction</em> in order to improve the approximation; consult GeekNotes for details.)</p>
<p>Many people will say that the sample should contain at least 10 successes and 10 failures in order to qualify as “big enough.” (The <code>binomtestGC()</code> gives an “exact” P-value and is not subject to this restriction.)</p>
<p>For tests involving a single proportion, you may use either <code>proptestGC()</code> or <code>bimom.testGC()</code>. The choice is up to you, but we have a slight preference for <code>binom.testgC()</code>, since it delivers “exact”&quot; P-values regardless of the samples size.</p>
</div>
<div id="additional-examples-2" class="section level3">
<h3><span class="header-section-number">10.5.3</span> Additional Examples</h3>
<div id="an-esp-experiment-summary-data-and-care-in-drawing-conclusions" class="section level4">
<h4><span class="header-section-number">10.5.3.1</span> An ESP Experiment: Summary Data, and Care in Drawing Conclusions</h4>
<p>The following example deals with a study that was actually conducted at the University of California at Davis around the year 1970.</p>
<p>The researcher, a para-psychologist named Charles Tart, was looking for evidence of extrasensory perception (ESP) in human beings. Tart designed a machine that he called the “Aquarius”, which could generate numbers. He set the machine to generate either 1, 2, 3, or 4. For each subject in the study, the Aquarius machine generated 500 numbers, and after each number was generated the subject was asked to guess the number. After each guess was submitted, the machine would show the subject the “correct” number by flashing one of four numbered lights, and then would generate the next number.</p>
<p>One study involved fifteen subjects, who made a total of</p>
<p><span class="math display">\[15 \times 500 = 7500\]</span></p>
<p>guesses. Out of this total, 2006 of the guesses were correct.</p>
<p>Let’s think about these results. If the subjects have no ESP at all, then it would seem that they would be reduced to guessing randomly, in which case the chance of a correct guess should be 1 in 4, or 0.25. Then the number <span class="math inline">\(X\)</span> of correct guesses in these 7500 tries would be a binomial random variable, with <span class="math inline">\(n=7500\)</span> trials and chance of success <span class="math inline">\(p=0.25\)</span>. The expected number of correct guesses would then be:</p>
<p><span class="math display">\[np = 0.25 \times 7500 = 1875.\]</span></p>
<p>The observed number of correct guesses was 2006, which is 131 more than expected. We wonder if this observation constitutes strong evidence that at least some of the subjects had at least some ESP powers.</p>
<p>Let’s try a test of significance to find out:</p>
<p><strong>Step One</strong>: Define Parameter and State Hypotheses.</p>
<p>Let</p>
<blockquote>
<p><span class="math inline">\(p\)</span> = probability that a subject will guess correctly.</p>
</blockquote>
<p>Then our hypotheses are:</p>
<blockquote>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(p = 0.25\)</span></p>
</blockquote>
<p>The Null expresses the view that the subjects have no ESP; they are just randomly guessing.</p>
<blockquote>
<p><span class="math inline">\(H_a\)</span>: <span class="math inline">\(p &gt; 0.25\)</span></p>
</blockquote>
<p>The Alternative expresses the view that the subjects can do something better than guess randomly.</p>
<p><strong>Step Two</strong>: Safety Check and Test Statistic.</p>
<p>The test statistic is easy: it’s the 2006 correct guesses. As for the safety check: we are not picking from a population so we don’t have to check whether we have taken a simple random sample from a population. If the Null is right, the subjects are just guessing randomly, so the number of correct guesses would be <code>binom(7500,0.25)</code>, as explained above.</p>
<p><strong>Step Three</strong>: P-value</p>
<p>Let’s run the test. we have summary data, so we don’t have to specify what counts as a success; we only need to enter the number of successes and the number of trials:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">binomtestGC</span>(<span class="dv">2006</span>,<span class="dt">n=</span><span class="dv">7500</span>,<span class="dt">p=</span><span class="fl">0.25</span>,<span class="dt">alternative=</span><span class="st">&quot;greater&quot;</span>)</code></pre></div>
<pre><code>## Exact Binomial Procedures for a Single Proportion p:
##  Results based on Summary Data
## 
## Descriptive Results:  2006 successes in 7500 trials
## 
## Inferential Results:
## 
## Estimate of p:    0.2675 
## SE(p.hat):    0.0051 
## 
## 95% Confidence Interval for p:
## 
##           lower.bound         upper.bound          
##           0.259061            1.000000             
## 
## Test of Significance:
## 
##  H_0:  p = 0.25 
##  H_a:  p &gt; 0.25 
## 
##  P-value:        P = 3e-04</code></pre>
<p>Hmm, the P-value is very small: about 0.0003.</p>
<blockquote>
<p><strong>Interpretation of P-Value</strong>: <em>If all of the subjects had only a 25% chance of guessing correctly, then there is only about a 3 in 10,000 chance that they would get a total of at least 2006 correct guesses, as they did in this study.</em></p>
</blockquote>
<p><strong>Step Four</strong>: Decision</p>
<p>We reject the Null, since the P-value was so very small.</p>
<p><strong>Step Five</strong>: This study provided very strong evidence that at least some of the subjects in the study had more than a 1-in-4 chance of guessing correctly.</p>
<p>Notice how carefully the conclusion was framed, in terms of the probability of a correct guess rather than whether or not anyone has ESP. The reason for this caution is that the test of significance only addresses the mathematical end of things: in particular, it does not address whether the study was designed well enough so that a <span class="math inline">\(p\)</span> being larger than 0.25 would be <em>the very same thing as</em> some subjects possessing ESP powers.</p>
<p>It turned out, in fact, that there was a problem with the design of the study: the machine’s random-number generation program was defective, in such a way that it rarely generated the same number twice in a row. Some of the subjects probably recognized this pattern and adopted the strategy of guessing randomly one of the three numbers that had not been generated in the previous round. These subjects would then improve their chance to 1-in-3 for the rest of their trials.</p>
<p>There is an important moral to this story:</p>
<blockquote>
<p><em>A significance test only tells you whether or not it is reasonable to believe that the results could be obtained by chance if the Null is true. It does NOT tell you how the Alternative Hypothesis should be interpreted. When the study has a flawed design, the results of the test will not mean what you expect them to mean!</em></p>
</blockquote>
</div>
</div>
</div>
<div id="difference-of-two-proportions-p_1-p_2" class="section level2">
<h2><span class="header-section-number">10.6</span> Difference of Two Proportions <span class="math inline">\(p_1-p_2\)</span></h2>
<p>Recall that in the <code>mat111survey</code>, participants were asked their sex, and were also asked whether they believed in love at first sight. The results were as follows:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">SexLove &lt;-<span class="st"> </span><span class="kw">xtabs</span>(~sex+love_first,<span class="dt">data=</span>m111survey)
<span class="kw">rowPerc</span>(SexLove)</code></pre></div>
<pre><code>##         love_first
## sex          no    yes  Total
##   female  55.00  45.00 100.00
##   male    74.19  25.81 100.00</code></pre>
<p>In the sample, the females were much more likely than the males to believe in love at first sight (45% vs. 25.81%), but these figures are based on fairly small samples. We wonder whether they provide strong evidence that in the GC population at large females are more likely than males to believe in love at first sight.</p>
<p>Now this is a question about the relationship between two categorical variables, so we could address it with the chi-square test from Chapter 3:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">chisqtestGC</span>(SexLove)</code></pre></div>
<p>However, <em>when the explanatory and reponse variables both have only two values</em>, then it is possible to construe the question as a question about the difference between two proportions. A two-proportions test confers some advantages in terms of how much information we extract from the data.</p>
<div id="the-five-steps-4" class="section level3">
<h3><span class="header-section-number">10.6.1</span> The Five Steps</h3>
<p><strong>Step One</strong>: Definition of Parameters and Statement of Hypotheses</p>
<p>Let</p>
<blockquote>
<p><span class="math inline">\(p_1\)</span> = the proportion of all GC females who believe in love at first sight</p>
</blockquote>
<blockquote>
<p><span class="math inline">\(p_2\)</span> = the proportion of all GC males who believe in love at first sight</p>
</blockquote>
<p>The our hypotheses are:</p>
<blockquote>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(p_1 - p_2 = 0\)</span></p>
</blockquote>
<blockquote>
<p><span class="math inline">\(H_a\)</span>: <span class="math inline">\(p_1 - p_2 &gt; 0\)</span></p>
</blockquote>
<p><strong>Step Two</strong>: Safety Check and Test Statistic</p>
<p>The Safety Check is the same as for confidence intervals:</p>
<ul>
<li>We should have taken two independent simple random samples from two populations, OR we should have done a completely randomized experiment with two treatment groups;</li>
<li>the sample size should be “large enough” (see below).</li>
</ul>
<p>In this current case, we have two samples from two populations (the GC gals and the GC guys). There is some concern as to whether the samples are really “like” simple random samples, but since one’s decision to take MAT111 (and hence get into the survey) is probably unrelated to whether one believes in love at first sight, maybe we can count ourselves as “safe” on this point.</p>
<p>As for a “large enough” sample size, we plan to use <code>proptestGC()</code>, just as we used it to make confidence intervals for <span class="math inline">\(p_1-p_2\)</span>. Hence the safety criteria are the same: if the number of yesses and nos in both samples exceeds 10, then we can trust the approximation to the P-value that the test provides. If in one of the samples there are not at least ten yesses, and not at lest ten nos, then the computer will issue a warning.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">proptestGC</span>(~sex+love_first,<span class="dt">data=</span>m111survey,
        <span class="dt">success=</span><span class="st">&quot;yes&quot;</span>,<span class="dt">p=</span><span class="dv">0</span>,<span class="dt">alternative=</span><span class="st">&quot;greater&quot;</span>)</code></pre></div>
<p>The descriptive results are given first:</p>
<pre><code>##        yes  n estimated.prop
## female  18 40         0.4500
## male     8 31         0.2581</code></pre>
<p>From these results we can see that there are fewer than ten males who answered “yes”, and sure enough the routine delivers its warning:</p>
<pre><code>## WARNING:  In at least one of the two groups, 
## number of successes or number of failures is below 10.
## The normal approximation for confidence intervals
## and P-value may be unreliable.</code></pre>
<p>For the sake of seeing the entire example, we will proceed anyway.</p>
<p>When we come to the inferential results, we see the estimator <span class="math inline">\(\hat{p}_1-\hat{p}_2\)</span>, and the standard error of this estimate:</p>
<pre><code>## Estimate of p1-p2:   0.1919 
## SE(p1.hat - p2.hat):  0.1112 </code></pre>
<p>Note that the estimate is not even two standard errors above the value of 0 that the Null expects it to be. The results of this study are not very surprising, if the Null is in fact correct.</p>
<p>The formula for the test statistic is:</p>
<p><span class="math display">\[z=\frac{\hat{p}_1-\hat{p}_2}{\sqrt{\frac{\hat{p}_1(1-\hat{p}_1)}{n_1}+\frac{\hat{p}_2(1-\hat{p}_2)}{n_2}}},\]</span></p>
<p>so once again it has “z-score style”, telling us how many SEs the estimator is above or below the 0 that the Null expects. In this case its numerical value, according to the output, is:</p>
<pre><code>##   Test Statistic:        z = 1.726 </code></pre>
<p><strong>Step Three</strong>: P-Value</p>
<p>The output says that the P-value for the one-sided test is:</p>
<pre><code>##   P-value:       P = 0.04216</code></pre>
<p>According to this test, if in the GC population females are equally likely to believe in love at first sight, then there is about a 4.2% chance for the differences between the sample proportions (45%-25.8%) to be at least a big as it was observed to be.</p>
<p><strong>Step Four</strong>: Decision</p>
<p>Since <span class="math inline">\(P = 0.042 &lt; 0.05\)</span>, we reject the Null.</p>
<p><strong>Step Five</strong>: Conclusion</p>
<p>This data provided strong evidence that GC females are more likely than GC males to believe in love at first sight.</p>
<p>We stress, though, that we completed the test in the presence of a warning from R. There do exist other routines that attempt to provide better approximations to the P-value when samples are small, and they result in somewhat different conclusions. (One such test is <code>prop.test()</code>; see the GeekNotes.)</p>
</div>
<div id="working-with-summary-data-1" class="section level3">
<h3><span class="header-section-number">10.6.2</span> Working With Summary Data</h3>
<p>Imagine an experiment in which there are 2000 subjects who are randomly divided into two groups of size 1000 each. All subjects get a shot in mid-October. Member of Group A (control) gets a shot that feels just like getting a flu vaccine but which actually delivers an inert substance, whereas every member of group B gets a shot containing the current flu vaccine. (Note the blinding.) Doctors monitor the subjects until Spring, and record whether or not each subject caught the flu. Of the 1000 members of Group A, 80 got the flu, whereas of the 1000 members of Group B, 40 got the flu. We are interested in the following:</p>
<blockquote>
<p><strong>Research Question</strong>: <em>Do the results provide strong evidence that the flu vaccine was effective in reducing the risk of flu that year?</em></p>
</blockquote>
<p>We have summary data, so we use <code>proptestGC()</code> for summary data just as we did for confidence intervals.</p>
<p><strong>Step One</strong>: Define parameters and state hypotheses.</p>
<p>Let:</p>
<blockquote>
<p><span class="math inline">\(p_1\)</span> = the proportion of all 2000 subjects who would have caught the flu, if all of them had been given the inert substance</p>
</blockquote>
<blockquote>
<p><span class="math inline">\(p_2\)</span> = the proportion of all 2000 subjects who would have caught the flu, if all of them had been given the real flu vaccine</p>
</blockquote>
<p>Then the hypotheses are:</p>
<blockquote>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(p_1-p_2 = 0\)</span></p>
</blockquote>
<blockquote>
<p><span class="math inline">\(H_a\)</span>: <span class="math inline">\(p_1-p_2 &gt; 0\)</span></p>
</blockquote>
<p><strong>Step Two</strong>: Safety Check and Test Statistic</p>
<p>Let’s run the test:</p>
<ul>
<li>We need to tell R the number of successes in the two samples, and we do this by putting <code>c(80,40)</code> into an argument called <code>x</code>.</li>
<li>We also need to tell R the sample sizes, so we put <code>c(1000,1000)</code> into an argument called <code>n</code>.</li>
<li>We tell R that the Null thinks <span class="math inline">\(p_1-p_2\)</span> is 0, by setting an argument <code>p</code> to 0.</li>
<li>Finally, we tell R what the alternative hypothesis looks like, by setting <code>alternative</code> to <code>two.sided</code>:</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">proptestGC</span>(<span class="dt">x=</span><span class="kw">c</span>(<span class="dv">80</span>,<span class="dv">40</span>),<span class="dt">n=</span><span class="kw">c</span>(<span class="dv">1000</span>,<span class="dv">1000</span>),
          <span class="dt">p=</span><span class="dv">0</span>,<span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)</code></pre></div>
<pre><code>## 
## 
## Inferential Procedures for the Difference of Two Proportions p1-p2:
##  Results taken from summary data.
## 
## 
## Descriptive Results:
## 
##         successes    n estimated.prop
## Group 1        80 1000           0.08
## Group 2        40 1000           0.04
## 
## 
## Inferential Results:
## 
## Estimate of p1-p2:    0.04 
## SE(p1.hat - p2.hat):  0.01058 
## 
## 95% Confidence Interval for p1-p2:
## 
##           lower.bound         upper.bound          
##           0.019258            0.060742             
## 
## Test of Significance:
## 
##  H_0:  p1-p2 = 0
##  H_a:  p1-p2 != 0
## 
##  Test Statistic:     z = 3.78 
##  P-value:        P = 0.0001571</code></pre>
<p>There was no warning, so the sample sizes were big enough. Also, we did a randomized experiment, so we are safe to proceed.</p>
<p>The test statistic is <span class="math inline">\(z=3.78\)</span>, indicating that the difference in sample proportions (8% in the control group vs. 4% in the vaccine group) was about 3.78 standard errors bigger than the Null expected it to be.</p>
<p><strong>Step Three</strong>: P-value</p>
<p>The P-value was quite small, about 0.00016.</p>
<blockquote>
<p><strong>Interpretation of P-Value</strong>: <em>If the vaccine is doing no good, then there is only about a 16 in 100,000 chance of getting a test statistic at least as far from 0 as the one we got in our study.</em></p>
</blockquote>
<p><strong>Step Four</strong>: Decision</p>
<p>Since <span class="math inline">\(P=0.00016 &lt; 0.05\)</span>, we reject the Null.</p>
<p><strong>Step Five</strong>: Conclusion</p>
<p>This experiment provided strong evidence that the vaccine helps to prevent flu.</p>
<p>By the way: if the vaccine was effective, why was it not perfect? 40 out of 1000 people using the vaccine got the flu anyway! There are two reasons why flu vaccines are not completely effective:</p>
<ol style="list-style-type: decimal">
<li>The flu vaccine is based on a “dead virus”, so it takes a while—usually about two weeks—for the body to recognize its existence and to develop the appropriate antibodies. During that period a person who is exposed to the flu could easily “catch” it.</li>
<li>The flu vaccine is designed each year by scientists at the Center for Disease Control, who make the best prediction they can as to which strains of flu are most likely to be prevalent in the coming winter. The vaccine is based on these strains, and is not guaranteed to work against all possible strains to which a person might be exposed.</li>
</ol>
</div>
</div>
<div id="further-considerations-about-significance-tests" class="section level2">
<h2><span class="header-section-number">10.7</span> Further Considerations About Significance Tests</h2>
<p>As we have covered each of the Basic Five in this Chapter and in Chapter Three, we have run across ideas that apply to all significance tests. Here is a quick rundown of what we have learned so far:</p>
<ul>
<li>The Five-Step logic applies to all significance tests.</li>
<li>If your test concerns one or more parameters, then you need to define your parameters and then use the symbols for those parameters to state your hypotheses.</li>
<li>The hypotheses always talk about what’s going on in the population(s), not the samples. (If we did an experiment, then the hypotheses talk about what would happen if all the subjects were given each of the treatments.)</li>
<li>The Null is the hypothesis that says that there is no pattern in the population.</li>
<li>The Alternative always involves an inequality.</li>
<li>Tests involving one of the Basic Five can be either one-side or two-sided. This affects the computation of P-values.</li>
<li>It’s always useful to stop and think about the test statistic. With the exception of <code>binomtestGC()</code> the test statistic is “z-score style”, and it tells you how many SEs the estimator is above or below what the Null expects. When it is far from 0, that’s bad for the Null!</li>
<li>P-values can always be interpreted according to following format: <em>If [the Null is True], then there is about a [P-value] chance of getting a test statistic at least as extreme as the one we actually got in this study.</em></li>
<li>We can run tests straight from a data frame using formula-data input, or we can enter summary data.</li>
<li>Tests only check the Null Hypothesis in mathematical form. They don’t check whether the study was well-designed (see the ESP example).</li>
<li>There is a correspondence between tests and confidence intervals that basically says: when the interval does not contain the Null’s belief about the parameter, then the test will reject the Null, and when the interval contains the Null’s belief the test will not reject the Null.</li>
</ul>
<p>There are some additional concepts that apply to all significance tests, and in this section we will consider some of them.</p>
<div id="types-of-error" class="section level3">
<h3><span class="header-section-number">10.7.1</span> Types of Error</h3>
<p>There is no guarantee that Step Four (the Decision) in a test of significance will be correct. That’s because the sample is based on chance. No matter how much the sample estimator for the population parameters differs from what the Null expects it to be, the difference COULD POSSIBLY be due to our having drawn a really rare, unlikely sort of sample. So even when we reject the Null based on a low P-value, the Null could be correct anyway. The error that we make in such a situation is called a <em>Type-I Error</em>.</p>
<p>It goes the other way around, too: we might fail to reject the Null when it is in fact false. Such an error is called a <em>Type-II Error.</em></p>
<p>The fact that a test can deliver an error is not a sign that the testing procedure is bad. On the contrary, just as a well-designed formula for a 95%-confidence interval SHOULD fail to contain the population parameter 5% of the time in repeated sampling, so a well-designed test of significance with a 5% cut-off standard SHOULD commit a Type-I error 5% of the time in repeated sampling, if the Null is in fact correct.</p>
<p>The only way never to commit a Type-I error is to NEVER reject the Null. But if that’s your plan, then you might as well not collect any data at all: it won’t affect your decision about the Null Hypothesis!</p>
<p>When the Null is false, you are correct when you reject the Null. The probability of rejecting the Null when it is, in fact, false is called the <em>power</em> of the test. The power depends on “how false”&quot; the Null actually is. The more the Null’s belief about the parameter differs from what the parameter actually is, the higher the power should be.</p>
<p>Sample size makes a difference, too. If the Null is, in fact, false then you are more likely to be able to detect that fact using a large sample than you are using a small one. Tests that are based on large samples are therefore more powerful than tests based on small samples.</p>
<p>The app below illustrates the idea we have broached concerning Type-I and Type-II errors. The app draws random samples from a population that is normally distributed, computes a confidence interval based on the sample, and performs a two-sided test for the mean of the population, too.</p>
<p>In all scenarios, the true mean of the population is <span class="math inline">\(\mu = 170\)</span>.</p>
<p>When you choose to draw one sample per mouse click, you will see a histogram of of the sample in blue. You will also see a confidence interval in yellow, with the sample mean as a blue dot in the middle of that interval. In the console, you will get the results of a two-sided test for where the null says that <span class="math inline">\(\mu\)</span> is 170 (that is, <span class="math inline">\(\mu_0=170\)</span>). You can vary the true population mean <span class="math inline">\(\mu\)</span> with a slider.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">require</span>(manipulate)
<span class="kw">Type12Errors</span>()</code></pre></div>
<p>To start out, keep the true population mean <span class="math inline">\(\mu\)</span> set at 170, so that the null is actually true. This means that whenever the tests rejects the Null, a Type-I error has been made. Click through a number of samples one at a time. Then try many samples (a hundred, or a thousand). What proportion of the time do you get a Type-I error?</p>
<p>Next, move the <span class="math inline">\(\mu\)</span> slider a bit away from 170. Now the Null is false, so whenever you reject it you have not made an error. Try lots of samples: what happens to the proportion of rejections, in the long run, after many samples?</p>
<p>Next. keeping <span class="math inline">\(\mu\)</span> where it is, move up the sample size <span class="math inline">\(n\)</span>, and run one sample at a time. What happens to the confidence intervals: are they wider than before, or narrower? What proportion of the time do you correctly reject the Null? Is it higher or lower than it was when the sample size was smaller?</p>
<p>Some Basic Ideas Learned From the the App:</p>
<ul>
<li>The test is designed so that if the Null is true and your cut-off value (aka <em>level of significance</em>) is <span class="math inline">\(\alpha\)</span>, then the test will incorrectly reject the Null (i.e. commit a Type-I Error) <span class="math inline">\(100\alpha\)</span> percent of the time.</li>
<li>The further the Null’s belief is from the actual value of the population parameter, the more likely it is that the test will reject the Null (i.e., the more powerful the test is).</li>
<li>The bigger the sample size, the more powerful the test will be when the Null is false. When the sample size is very large, even a Null that is only a “little bit” false is quite likely to be rejected.</li>
</ul>
<p>The last point is especially important. When the sample size is very large, the test is very likely to detect the difference between a false Null belief and the true parameter value, even when the two are very close together. A large-sample test can thus provide strong evidence for what amounts to a very weak pattern in the population. Hence you should always keep in mind:</p>
<blockquote>
<p><em>Strong evidence for a relationship is not the same thing as evidence for a strong relationship.</em></p>
</blockquote>
</div>
<div id="the-dangers-of-limited-reporting" class="section level3">
<h3><span class="header-section-number">10.7.2</span> The Dangers of Limited Reporting</h3>
<p>Suppose that you have twenty friends, and you are interested in knowing whether any of them possess powers of telekinesis (TK for short). Telekinesis (if such a thing exists at all) is the ability to move objects by mental intention alone, without touching them.</p>
<p>You perform the following test with each of your friends: you flip a fair coin 100 times, after instructing your friend to attempt to make the coin land Heads simply by concentrating on it.</p>
<p>You get the following results:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">CoinData</code></pre></div>
<pre><code>##    heads
## 1     57
## 2     54
## 3     57
## 4     61
## 5     45
## 6     52
## 7     60
## 8     52
## 9     48
## 10    57
## 11    58
## 12    58
## 13    51
## 14    46
## 15    49
## 16    53
## 17    51
## 18    51
## 19    48
## 20    46</code></pre>
<p>Hmm, one of your friends (Friend Number Four) got 61 Heads in 100 flips. That seems like a lot. If your friend has no TK—so that the coin has the usual 50% chance of landings heads—then the chance of 61 or more heads is pretty small:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pbinomGC</span>(<span class="dv">60</span>,<span class="dt">region=</span><span class="st">&quot;above&quot;</span>,<span class="dt">size=</span><span class="dv">100</span>,<span class="dt">prob=</span><span class="fl">0.5</span>)</code></pre></div>
<pre><code>## [1] 0.0176001</code></pre>
<p>If you run a <code>binomtestGC()</code> on your friend’s results, you get the same information:</p>
<p><strong>Step One</strong>: Define Parameter and State the Hypotheses</p>
<p>Let</p>
<blockquote>
<p><span class="math inline">\(p\)</span> = chance that coin lands Heads when Friend Number Four concentrates on it.</p>
</blockquote>
<p>The hypotheses are:</p>
<blockquote>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(p = 0.50\)</span> (Friend #4 has no TK powers)</p>
</blockquote>
<blockquote>
<p><span class="math inline">\(H_a\)</span>: <span class="math inline">\(p &gt; 0.50\)</span> (Friend #4 has some TK powers)</p>
</blockquote>
<p><strong>Step Two</strong>: Safety Check and Test Statistic</p>
<p>We flipped the coin randomly so we are safe. The test statistic is 61, the number of Heads our friend got.</p>
<p><strong>Step Three</strong>: P-value</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">binomtestGC</span>(<span class="dv">61</span>,<span class="dt">n=</span><span class="dv">100</span>,<span class="dt">p=</span><span class="fl">0.5</span>,<span class="dt">alternative=</span><span class="st">&quot;greater&quot;</span>)</code></pre></div>
<pre><code>## Exact Binomial Procedures for a Single Proportion p:
##  Results based on Summary Data
## 
## Descriptive Results:  61 successes in 100 trials
## 
## Inferential Results:
## 
## Estimate of p:    0.61 
## SE(p.hat):    0.0488 
## 
## 95% Confidence Interval for p:
## 
##           lower.bound         upper.bound          
##           0.523094            1.000000             
## 
## Test of Significance:
## 
##  H_0:  p = 0.5 
##  H_a:  p &gt; 0.5 
## 
##  P-value:        P = 0.0176</code></pre>
<p>Sure enough, the P-value is 0.0176.</p>
<p><strong>Step Four</strong>: Decision</p>
<blockquote>
<p>Since P &lt; 0.05, we reject the Null.</p>
</blockquote>
<p><strong>Step Five</strong>: Conclusion</p>
<blockquote>
<p>Our data (the 100 coin flips in the presence of Friend Number Four) provide strong evidence that when Friend Four concentrates on this coin he/she has more than a 50% chance of making it land Heads.</p>
</blockquote>
<p>There is nothing wrong with any step in this test, and yet it seems quite wrong to conclude that Friend Number Four actually has some TK powers.</p>
<p>Why? Because your friend was only one of twenty people tested. When you test a lot of people, then even if none of them have TK you would expect a few of them to get an unusually large number of heads, just by chance, right?</p>
<p>Just as with any test of significance, <code>binomtestGC()</code> considers ONLY the data that you present to it. When it is allowed to consider ONLY the results from Friend Number Four, R leads you to a perfectly reasonable conclusion: those 100 flips, <em>when considered in isolation from other data</em>, provide strong evidence for some TK powers in Friend Four.</p>
<p>But it’s not right to consider the 100 flips in isolation. Instead, should we not at least take into account that our friend’s results were the maximum out of a study involving twenty friends?</p>
<p>Perhaps a more relevant P-value for this situation—one that takes more of the data into account—is the probability of at least one person getting 61 or more heads when 20 people, none of whom have TK, participate in a study like this.</p>
<p>If you run the following R code, you will teach R a function that conducts the entire study and returns the maximum number of heads achieved by any friend</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">HeadMax &lt;-<span class="st"> </span>function(<span class="dt">friends=</span><span class="dv">20</span>,<span class="dt">flips=</span><span class="dv">100</span>,<span class="dt">coin=</span><span class="fl">0.5</span>) {
  <span class="kw">return</span>(<span class="kw">max</span>(<span class="kw">rbinom</span>(friends,<span class="dt">size=</span>flips,<span class="dt">prob=</span>coin)))}</code></pre></div>
<p>Now run the function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">HeadMax</span>(<span class="dt">friends=</span><span class="dv">20</span>,<span class="dt">flips=</span><span class="dv">100</span>)</code></pre></div>
<p>Re-run the function a number of times. Do you notice that it is not such a rare thing at all for at least one person to get at least 61 heads?</p>
<p>In fact, if you were to run the function many times and keep track of the results, you would find that—even if there is no such thing as TK—there is about a 30% chance that at least one friend will get 61 or more heads. When you think of it this way, you see that 61 heads is not strong evidence for TK!</p>
<p>The moral of the story is this:</p>
<blockquote>
<p><em>Tests of significance consider only the data presented to them.</em></p>
</blockquote>
<p>If you use a test that is based on only a limited portion of the data, the test does not deliver meaningful results. Instead:</p>
<ul>
<li>Report all relevant data you have collected.</li>
<li>Look for ways to incorporate all of the relevant data when you are testing for statistical significance.</li>
</ul>
</div>
<div id="the-dangers-of-data-snooping" class="section level3">
<h3><span class="header-section-number">10.7.3</span> The Dangers of Data-Snooping</h3>
<p>The example in the previous section may seem somewhat artificial. After all, you are an honest-to-good scientist—or at least you are planning to take some honest-to-good science classes—and you know that real, honest scientists do not knowingly limit their reporting to just those portions of the data that point in an interesting direction.</p>
<p>But it’s amazing how much we can limit our reporting without even knowing it.</p>
<p>For example, consider the <code>attitudes</code> data. If you need a reminder, run:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(attitudes)
<span class="kw">View</span>(attitudes)
<span class="kw">help</span>(attitudes)</code></pre></div>
<p>As you will recall, there was a limited number of primary research questions that guided the design of the <code>attitudes</code> study:</p>
<ul>
<li>Does suggested race of defendant affect the sentence recommended?</li>
<li>Does suggested race of victim affect the sentence recommended?</li>
<li>Does the way one lost one’s money affect the decision about whether to attend the concert anyway?</li>
</ul>
<p>But the researchers could not resist the urge to collect some other information beyond what was needed to narrowly address the primary research questions. For example, the researcher got information on the sex, class rank and intended major of each participant.</p>
<p>There is nothing wrong at all with the urge to collect extra data. In fact it’s a wonderful human trait, is it not?</p>
<p>And of course there is nothing at all wrong with the urge to explore the data thus collected. It’s a rich data set (there are a lot of variables), so there are many research questions one could raise.</p>
<p>For example, we might explore the</p>
<blockquote>
<p><strong>Research Question</strong>: <em>Who is harder on crime: a GC female or a GC male?</em></p>
</blockquote>
<p>When you think about the kinds of variables involved in this question (explanatory = <strong>sex</strong> is a factor, response = <strong>sentence</strong> is numerical) you see that <code>favstats()</code> will provide useful descriptive statistics:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">favstats</span>(sentence~sex,<span class="dt">data=</span>attitudes)</code></pre></div>
<pre><code>##      sex min   Q1 median Q3 max     mean       sd   n missing
## 1 female   3 15.0     25 40  50 27.30793 15.46790 164       1
## 2   male   3 12.5     25 40  50 25.76699 15.31832 103       0</code></pre>
<p>Hmm, nothing much seems to be going on here.</p>
<p>Let’s try another</p>
<blockquote>
<p><strong>Research Question</strong>: <em>Who is more likely to decide to attend the rock concert anyway: a GC female or a GC male</em></p>
</blockquote>
<p>Again, we work our way from research question to variable to type of each variable to exploration technique and we hit upon the following R code:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">SexRock &lt;-<span class="st"> </span><span class="kw">xtabs</span>(~sex+conc.decision,<span class="dt">data=</span>attitudes)
SexRock</code></pre></div>
<pre><code>##         conc.decision
## sex      buy not.buy
##   female 112      53
##   male    64      39</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rowPerc</span>(SexRock)</code></pre></div>
<pre><code>##         conc.decision
## sex         buy not.buy  Total
##   female  67.88   32.12 100.00
##   male    62.14   37.86 100.00</code></pre>
<p>Hmm, apparently there not much going on in the way of a relationship between sex and decision to attend a rock concert.</p>
<p>Still another</p>
<blockquote>
<p><strong>Research Question</strong>: <em>Who is harder on crime: A GC student who would decide to atttend the rock concert or a GC student who decide not to attend?</em></p>
</blockquote>
<p>Again we check:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">favstats</span>(sentence~conc.decision,<span class="dt">data=</span>attitudes)</code></pre></div>
<pre><code>##   conc.decision min Q1 median Q3 max     mean       sd   n missing
## 1           buy   3 15     25 45  50 28.15143 15.70951 175       1
## 2       not.buy   3 10     20 30  50 23.97826 14.48453  92       0</code></pre>
<p>Interesting: in the survey those who chose to attend (let’s call them “Big Spenders”) recommended sentences for the defendant that were, on average, five years longer than the sentences recommended by the Thrifty types—the ones who chose not to attend.</p>
<p>Let’s check it out graphically: Figure [Sentences and Ticket Decision] shows the results. The plot thickens! The distributions are fairly similar in shape, but it appears that the Big Spender group had a substantially higher proportion of people who recommended the maximum sentence of 50 years: that pulled up their mean sentence.</p>
<div class="figure"><span id="fig:setenceticket"></span>
<img src="bookdown-demo_files/figure-html/setenceticket-1.png" alt="Sentence and Ticket Decision" width="672" />
<p class="caption">
Figure 10.6: Sentence and Ticket Decision
</p>
</div>
<p>Let’s test to see if these results are statistically significant. We won’t write out all five steps, but instead let’s just peek at the test output. (We’ll choose a two-sided test, because we had no advance evidence that Big Spenders should be harder on crime that Thrifty people.)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ttestGC</span>(sentence~conc.decision,<span class="dt">data=</span>attitudes,
         <span class="dt">mu=</span><span class="dv">0</span>,<span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)</code></pre></div>
<pre><code>## 
## 
## Inferential Procedures for the Difference of Two Means mu1-mu2:
##  (Welch&#39;s Approximation Used for Degrees of Freedom)
##   sentence grouped by conc.decision 
## 
## 
## Descriptive Results:
## 
##    group  mean    sd   n
##      buy 28.15 15.71 175
##  not.buy 23.98 14.48  92
## 
## 
## Inferential Results:
## 
## Estimate of mu1-mu2:  4.173 
## SE(x1.bar - x2.bar):  1.921 
## 
## 95% Confidence Interval for mu1-mu2:
## 
##           lower.bound         upper.bound          
##           0.384772            7.961563             
## 
## Test of Significance:
## 
##  H_0:  mu1-mu2 = 0 
##  H_a:  mu1-mu2 != 0 
## 
##  Test Statistic:     t = 2.172 
##  Degrees of Freedom:   198.6 
##  P-value:        P = 0.03102</code></pre>
<p>Hmm, the P-value is about 0.03. It appears that we have some strong evidence here that GC Big Spenders are harder on crime than GC Thrifties are.</p>
<p>Do you see what’s going on here? We have followed a natural and perfectly commendable human urge to paw through the available data, formulating research questions as we go and investigating them with appropriate descriptive techniques, deciding to run an inferential test only when descriptive techniques turned up an interesting pattern in the data. Although our intentions were quite honest, we are acting very much like the person in the previous section who decided to run <code>binomtestGC()</code> on the one friend who “produced” an intriguingly-large number of heads! This time, though, instead of testing on a limited amount of relevant data, we are testing on a <em>limited number of aspects</em> of the data. We are looking at the data from many different angles, as it were, and choosing to test on the angles that look “pretty”.</p>
<p>Even a totally ordinary piece of furniture (for example) can look “pretty” from a particular point of view, in a particular light, etc.</p>
<p>This practice—pawing through a rich data set, examining it from different points of view and performing tests on the basis of interesting patterns that we happen to notice when looking at the data from some of those vantage points—is called <em>data-snooping</em>.</p>
<dl>
<dt>Data Snooping</dt>
<dd><p><em>Data Snooping</em> is the practice of looking through a data set for patterns that interest us and performing inferential procedures on patterns that we notice, rather than limiting our tests to specific Research Questions that we had in mind prior to collecting the data.</p>
</dd>
</dl>
<p>Data snooping is not an inherently evil practice: on the contrary, it is an expression of two excellent human traits: curiosity, and the ability to detect many types of patterns. The problem is that the more curious we are, and the better we are at noticing patterns, the more likely it is that our data-snooping will lead us to report results as statistically significant when in fact they are only due to random quirks in the data.</p>
<p>The problem is especially acute because—unlike the “limited reporting” example of the previous section, where we can correct ourselves by taking all of the data into account—we don’t really know what <em>kinds</em> of patterns we as humans are disposed to find intriguing: we don’t know what constitutes the “set of all aspects” that have to be taken into account when one attempts to adjust the P-values for the tests on those particular aspects that, for one reason or another, got us excited.</p>
<p>This is really interesting: we have identified a problem in how to assess rationally what our observations entail, but this problem does not arise from our not knowing something about how the data was collected, nor does it arise from our not knowing something about the population. It arises from our not knowing something about <em>ourselves</em>.</p>
<p>There is no fool-proof solution to the problem of data-snooping. As a general rule of thumb, though, we should keep clearly in mind the distinction between:</p>
<ul>
<li>those research questions that we had in mind prior to collecting the data (<em>Primary Questions</em>) versus</li>
<li>those research questions that occur to us as we examine the collected data in all of its richness (<em>Secondary Questions</em>).</li>
</ul>
<p>Results of tests on Primary Questions should be taken more seriously than results of tests on Secondary Questions. The Results for Secondary Questions may be worth reporting to others (especially if they provide exceedingly strong evidence for a pattern), but we should be clear when we report them that the results were based on patterns that we noticed AFTER having examined the data. Perhaps in the future other researchers could treat them as Primary Questions, should they conduct a study similar to ours. If the same pattern persists in study after study, then we can be more and more certain that it is not due to chance variation in the data collection process, but reflects instead a pattern in the population itself.</p>
</div>
</div>
<div id="thoughts-about-r" class="section level2">
<h2><span class="header-section-number">10.8</span> Thoughts About R</h2>
<div id="new-code-to-learn" class="section level3">
<h3><span class="header-section-number">10.8.1</span> New Code to Learn?</h3>
<p>Functions for tests are the same as for confidence intervals! However, you have to consider some additional arguments. You need to pay attention to:</p>
<ul>
<li>the argument that sets the Null value for the parameter:
<ul>
<li><code>mu</code> in tests involving means</li>
<li><code>p</code> in tests involving proportions</li>
<li><code>prob</code> in <code>binomtestGC()</code></li>
</ul></li>
<li>the <code>alternative</code> argument that specifies the “side” of the test
<ul>
<li>“greater”</li>
<li>“less”</li>
<li>“two.sided”</li>
</ul></li>
</ul>
<p>The default value of <code>alternative</code> is “two.sided”, so if you want a two-sided test you need not mention <code>alternative</code> in your call to the function. For example, the following two functions calls will deliver exactly the same results:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ttestGC</span>(~fastest,<span class="dt">data=</span>m111survey,
       <span class="dt">mu=</span><span class="dv">100</span>)
<span class="kw">ttestGC</span>(~fastest,<span class="dt">data=</span>m111survey,
       <span class="dt">mu=</span><span class="dv">100</span>,<span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)</code></pre></div>
</div>
<div id="old-descriptive-friends" class="section level3">
<h3><span class="header-section-number">10.8.2</span> Old Descriptive Friends</h3>
<p>When you perform safety checks in the tests involving means and you have access to the original data rather than just a summary of it, then you may have to make graphs of your samples in order to check for skewness and outliers. For this you will revisit some old friends from Chapter Two. You should be fine with:</p>
<ul>
<li><code>histogram()</code></li>
<li><code>bwplot()</code></li>
</ul>
</div>
<div id="adding-a-variable-to-a-data-frame" class="section level3">
<h3><span class="header-section-number">10.8.3</span> Adding a Variable to a Data Frame</h3>
<p>On rare occasions you may need to add a variable to a data frame prior to running a test involving that variable. This occurred to us once, in the Research Question about whether women or men are more affected by the label on a jar of peanut butter. In order to add a variable <strong>Var</strong> to a data frame <code>MyData</code>, simply write:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">MyData$Var &lt;-<span class="st"> </span>Var</code></pre></div>
<p>The length of <strong>Var</strong> must be the same as the number of rows in the data frame.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="confidence-intervals.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="goodness-of-fit.html" class="navigation navigation-next " aria-label="Next page""><i class="fa fa-angle-right"></i></a>

<script src="book_assets/gitbook-2.6.7/js/app.min.js"></script>
<script src="book_assets/gitbook-2.6.7/js/lunr.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="book_assets/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/10-Tests.Rmd",
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
